// Sample MCQ questions for each skill - Level 1 (40 unique questions per skill)
export interface SampleQuestion {
  question_text: string;
  options: { text: string; is_correct: boolean }[];
  marks: number;
}

// Level 2 theory questions - descriptive written answers
export interface TheoryQuestion {
  question_text: string;
  expected_answer: string;
  marks: number;
}

export const theoryQuestions: Record<string, TheoryQuestion[]> = {
  Java: [
    { question_text: "Explain the concept of Object-Oriented Programming (OOP) and its four main pillars with examples in Java.", expected_answer: "OOP is a programming paradigm based on objects. The four pillars are: 1) Encapsulation - bundling data and methods together (e.g., private fields with getters/setters), 2) Inheritance - deriving new classes from existing ones using 'extends', 3) Polymorphism - objects taking multiple forms through method overriding and overloading, 4) Abstraction - hiding implementation details using abstract classes and interfaces.", marks: 1 },
    { question_text: "What is the difference between an abstract class and an interface in Java? When would you use each?", expected_answer: "Abstract classes can have both abstract and concrete methods, constructors, and instance variables. Interfaces (pre-Java 8) only have abstract methods and constants. Use abstract classes when sharing code among related classes; use interfaces for unrelated classes that share a contract. Java 8+ interfaces can have default methods.", marks: 1 },
    { question_text: "Explain exception handling in Java. What is the difference between checked and unchecked exceptions?", expected_answer: "Exception handling uses try-catch-finally blocks. Checked exceptions (e.g., IOException) must be caught or declared with 'throws' at compile time. Unchecked exceptions (e.g., NullPointerException, RuntimeException) don't require explicit handling. The finally block always executes regardless of exception occurrence.", marks: 1 },
    { question_text: "Describe the Java Collections Framework. What are the differences between List, Set, and Map?", expected_answer: "The Collections Framework provides data structures and algorithms. List (ArrayList, LinkedList) maintains insertion order and allows duplicates. Set (HashSet, TreeSet) stores unique elements. Map (HashMap, TreeMap) stores key-value pairs with unique keys. Each has different performance characteristics for add, remove, and search operations.", marks: 1 },
    { question_text: "What is multithreading in Java? Explain how to create threads and the concept of synchronization.", expected_answer: "Multithreading allows concurrent execution of two or more threads. Threads can be created by extending Thread class or implementing Runnable interface. Synchronization prevents race conditions when multiple threads access shared resources using the 'synchronized' keyword, locks, or concurrent utilities from java.util.concurrent package.", marks: 1 },
    { question_text: "Explain the concept of JVM, JRE, and JDK. How does Java achieve platform independence?", expected_answer: "JDK (Java Development Kit) includes JRE and development tools. JRE (Java Runtime Environment) includes JVM and libraries. JVM (Java Virtual Machine) executes bytecode. Java achieves platform independence because source code compiles to bytecode (.class files) which runs on any platform with a JVM installed.", marks: 1 },
    { question_text: "What is garbage collection in Java? How does it work and what are the different types of garbage collectors?", expected_answer: "Garbage collection automatically reclaims memory from objects no longer referenced. The JVM identifies unreachable objects and frees their memory. Types include Serial GC, Parallel GC, CMS (Concurrent Mark Sweep), and G1 (Garbage First). Objects are promoted through generations (Young, Old, Permanent) based on survival through GC cycles.", marks: 1 },
    { question_text: "Explain the concept of generics in Java. Why are they useful and how do type bounds work?", expected_answer: "Generics provide compile-time type safety by parameterizing types. They eliminate type casting and prevent ClassCastException at runtime. Type bounds restrict generic types: upper bound (extends) limits to a type and its subtypes, lower bound (super) limits to a type and its supertypes. Wildcards (?) represent unknown types.", marks: 1 },
    { question_text: "What is the difference between String, StringBuilder, and StringBuffer in Java?", expected_answer: "String is immutable - every modification creates a new object. StringBuilder is mutable and not thread-safe, offering better performance for single-threaded string manipulation. StringBuffer is mutable and thread-safe (synchronized methods) but slower than StringBuilder. Use String for constants, StringBuilder for single-threaded manipulation, StringBuffer for multi-threaded scenarios.", marks: 1 },
    { question_text: "Explain the SOLID principles of object-oriented design with Java examples.", expected_answer: "S - Single Responsibility: A class should have one reason to change. O - Open/Closed: Open for extension, closed for modification. L - Liskov Substitution: Subtypes must be substitutable for their base types. I - Interface Segregation: Prefer small, specific interfaces over large general ones. D - Dependency Inversion: Depend on abstractions, not concrete implementations.", marks: 1 },
  ],
  Python: [
    { question_text: "Explain the difference between lists, tuples, and sets in Python. When would you use each?", expected_answer: "Lists are mutable, ordered sequences allowing duplicates (e.g., [1,2,3]). Tuples are immutable, ordered sequences (e.g., (1,2,3)), used for fixed data and as dictionary keys. Sets are mutable, unordered collections of unique elements (e.g., {1,2,3}), used for membership testing and eliminating duplicates.", marks: 1 },
    { question_text: "What are decorators in Python? Explain how they work with an example.", expected_answer: "Decorators are functions that modify the behavior of other functions without changing their source code. They take a function as argument and return a modified function. Using @decorator syntax, they wrap the original function. Common uses include logging, authentication, and caching. Example: @staticmethod, @property, or custom decorators using functools.wraps.", marks: 1 },
    { question_text: "Explain Python's Global Interpreter Lock (GIL) and its impact on multithreading.", expected_answer: "The GIL is a mutex in CPython that allows only one thread to execute Python bytecode at a time. This means CPU-bound multithreaded programs don't achieve true parallelism. For CPU-bound tasks, use multiprocessing instead. I/O-bound tasks can still benefit from threading as the GIL is released during I/O operations.", marks: 1 },
    { question_text: "What are list comprehensions and generator expressions? How do they differ?", expected_answer: "List comprehensions ([x**2 for x in range(10)]) create entire lists in memory at once. Generator expressions ((x**2 for x in range(10))) produce values lazily, one at a time, using less memory. Generators use yield and are ideal for large datasets. List comprehensions are faster for small datasets that need repeated access.", marks: 1 },
    { question_text: "Explain Python's memory management and garbage collection mechanism.", expected_answer: "Python uses reference counting as its primary memory management mechanism - each object tracks how many references point to it. When the count reaches zero, memory is freed. A cyclic garbage collector handles circular references. Python also uses memory pools (pymalloc) for small objects and a private heap for all Python objects.", marks: 1 },
    { question_text: "What is the difference between shallow copy and deep copy in Python?", expected_answer: "Shallow copy (copy.copy()) creates a new object but references the same nested objects. Deep copy (copy.deepcopy()) creates a new object and recursively copies all nested objects. For mutable nested structures, shallow copy means changes to nested objects affect both copies, while deep copy creates fully independent copies.", marks: 1 },
    { question_text: "Explain Python's inheritance model including multiple inheritance and MRO.", expected_answer: "Python supports single and multiple inheritance. With multiple inheritance, Method Resolution Order (MRO) uses C3 linearization to determine which method to call. The super() function follows MRO. Python uses the diamond problem resolution through MRO. Classes can override methods and call parent implementations using super().", marks: 1 },
    { question_text: "What are context managers in Python and how does the 'with' statement work?", expected_answer: "Context managers handle setup and cleanup actions automatically using the 'with' statement. They implement __enter__() and __exit__() methods. The 'with' statement ensures resources are properly released even if exceptions occur. Common examples include file handling (with open()), database connections, and locks. contextlib module provides utilities for creating context managers.", marks: 1 },
    { question_text: "Explain the concept of virtual environments in Python and why they are important.", expected_answer: "Virtual environments create isolated Python environments with their own packages and dependencies, independent of the system-wide installation. They prevent dependency conflicts between projects. Tools include venv (built-in), virtualenv, and conda. Each project can have different package versions without interfering with others.", marks: 1 },
    { question_text: "What are *args and **kwargs in Python? Explain with examples.", expected_answer: "*args collects extra positional arguments as a tuple, allowing functions to accept variable numbers of arguments. **kwargs collects extra keyword arguments as a dictionary. They can be used together: def func(*args, **kwargs). When calling functions, * unpacks iterables and ** unpacks dictionaries into arguments.", marks: 1 },
  ],
  C: [
    { question_text: "Explain the concept of pointers in C. What are pointer arithmetic and pointer to pointer?", expected_answer: "Pointers store memory addresses of variables. Pointer arithmetic allows incrementing/decrementing based on the data type size (e.g., int pointer increments by 4 bytes). Pointer to pointer (int **pp) stores the address of another pointer. Pointers enable dynamic memory allocation, pass-by-reference, and efficient array manipulation.", marks: 1 },
    { question_text: "What is dynamic memory allocation in C? Explain malloc(), calloc(), realloc(), and free().", expected_answer: "Dynamic memory allocation allows runtime memory management from the heap. malloc(size) allocates uninitialized memory. calloc(n, size) allocates zero-initialized memory for arrays. realloc(ptr, new_size) resizes previously allocated memory. free(ptr) releases allocated memory. Failure to free causes memory leaks.", marks: 1 },
    { question_text: "Explain the difference between structures and unions in C with examples.", expected_answer: "Structures allocate separate memory for each member, total size is sum of all members (plus padding). Unions share memory among members, size equals the largest member. In struct, all members can hold values simultaneously. In union, only one member holds a value at a time. Structs model entities; unions save memory when only one variant is needed.", marks: 1 },
    { question_text: "What is the difference between stack and heap memory in C? How are they managed?", expected_answer: "Stack memory is automatically managed (LIFO), stores local variables and function calls, has limited size, and is fast. Heap memory is manually managed via malloc/free, stores dynamically allocated data, is larger but slower, and risks fragmentation and memory leaks. Stack variables are deallocated when function returns.", marks: 1 },
    { question_text: "Explain file handling in C. What are the different modes and functions used?", expected_answer: "File handling uses FILE pointer and functions: fopen() opens files in modes like 'r' (read), 'w' (write), 'a' (append), 'rb' (binary read). fprintf/fscanf for formatted I/O, fread/fwrite for binary I/O, fgets/fputs for string I/O. fclose() closes files. fseek/ftell for position control. Always check if fopen returns NULL.", marks: 1 },
    { question_text: "What are preprocessor directives in C? Explain #define, #include, #ifdef with examples.", expected_answer: "Preprocessor directives are processed before compilation. #include inserts header files (#include <stdio.h> for system, #include \"myfile.h\" for local). #define creates macros and constants (#define PI 3.14). #ifdef/#ifndef/#endif enable conditional compilation for platform-specific code and include guards to prevent double inclusion.", marks: 1 },
    { question_text: "Explain the concept of function pointers in C and their practical applications.", expected_answer: "Function pointers store addresses of functions, declared as: int (*fptr)(int, int). They enable callback mechanisms, dynamic function dispatch, and implementing design patterns. Practical uses include qsort() comparison functions, event handlers, and creating jump tables. They allow runtime selection of which function to execute.", marks: 1 },
    { question_text: "What is the difference between pass by value and pass by reference in C?", expected_answer: "Pass by value copies the argument's value into the function parameter; changes don't affect the original. Pass by reference (using pointers) passes the address, allowing the function to modify the original variable. C only supports pass by value natively, but pass by reference is simulated using pointers (e.g., void swap(int *a, int *b)).", marks: 1 },
    { question_text: "Explain the concept of linked lists in C. How do you implement insertion and deletion?", expected_answer: "A linked list is a dynamic data structure where each node contains data and a pointer to the next node. Insertion: create new node, adjust pointers (at head: new->next = head; head = new). Deletion: find node, adjust previous node's pointer to skip deleted node, then free memory. Types include singly, doubly, and circular linked lists.", marks: 1 },
    { question_text: "What are storage classes in C? Explain auto, register, static, and extern.", expected_answer: "Storage classes define scope, visibility, and lifetime. auto (default): local scope, stack storage, exists within block. register: suggests CPU register storage for fast access. static: persists across function calls (local) or limits visibility to file (global). extern: declares variable defined in another file, enabling cross-file sharing.", marks: 1 },
  ],
  DBMS: [
    { question_text: "Explain normalization in databases. Describe 1NF, 2NF, 3NF, and BCNF with examples.", expected_answer: "Normalization reduces redundancy and dependency. 1NF: atomic values, no repeating groups. 2NF: 1NF + no partial dependencies (all non-key attributes depend on full primary key). 3NF: 2NF + no transitive dependencies. BCNF: every determinant is a candidate key. Each level eliminates specific types of anomalies (insert, update, delete).", marks: 1 },
    { question_text: "What are ACID properties in database transactions? Explain each with examples.", expected_answer: "ACID ensures reliable transactions. Atomicity: all operations complete or none do (bank transfer either completes fully or rolls back). Consistency: database moves from one valid state to another. Isolation: concurrent transactions don't interfere (using locks/MVCC). Durability: committed changes survive system failures (write-ahead logging).", marks: 1 },
    { question_text: "Explain the different types of JOINs in SQL with examples.", expected_answer: "INNER JOIN returns matching rows from both tables. LEFT JOIN returns all left table rows plus matching right rows (NULL for non-matches). RIGHT JOIN returns all right table rows plus matching left rows. FULL OUTER JOIN returns all rows from both tables. CROSS JOIN produces Cartesian product. SELF JOIN joins a table with itself.", marks: 1 },
    { question_text: "What is indexing in databases? Explain B-Tree and Hash indexes.", expected_answer: "Indexing creates data structures to speed up data retrieval. B-Tree indexes store sorted data in a balanced tree structure, supporting range queries and ordered access. Hash indexes use hash functions for exact-match lookups, offering O(1) average time but no range queries. Indexes speed reads but slow writes and consume storage.", marks: 1 },
    { question_text: "Explain the concept of database transactions and concurrency control mechanisms.", expected_answer: "Transactions group operations into atomic units. Concurrency control prevents conflicts when multiple transactions access data simultaneously. Mechanisms include: locking (shared/exclusive locks), two-phase locking (2PL), timestamp ordering, and MVCC (Multi-Version Concurrency Control). Problems prevented: dirty reads, non-repeatable reads, phantom reads.", marks: 1 },
    { question_text: "What is the difference between clustered and non-clustered indexes?", expected_answer: "Clustered index physically reorders table data according to the index key - only one per table, usually on primary key. Non-clustered index creates a separate structure with pointers to data rows - multiple allowed per table. Clustered is faster for range queries; non-clustered is better for specific lookups. Non-clustered has an additional lookup step.", marks: 1 },
    { question_text: "Explain database deadlocks. How are they detected and prevented?", expected_answer: "Deadlock occurs when two or more transactions hold locks and wait for each other's locks, creating a circular dependency. Detection uses wait-for graphs to find cycles. Prevention strategies: lock ordering (acquire locks in consistent order), timeout-based (abort after waiting too long), wound-wait and wait-die schemes. Resolution involves rolling back one transaction.", marks: 1 },
    { question_text: "What are views and stored procedures in SQL? What are their advantages?", expected_answer: "Views are virtual tables defined by SELECT queries, providing abstraction, security (restrict column access), and simplification. Stored procedures are precompiled SQL code blocks stored in the database, accepting parameters and containing logic. Advantages include reduced network traffic, code reuse, security, and consistent business logic enforcement.", marks: 1 },
    { question_text: "Explain the ER (Entity-Relationship) model and its components.", expected_answer: "The ER model represents database structure visually. Entities are real-world objects (rectangles). Attributes describe entities (ovals) - can be simple, composite, multivalued, or derived. Relationships connect entities (diamonds) with cardinality (1:1, 1:N, M:N). Keys (primary, foreign, candidate) uniquely identify entities. Weak entities depend on strong entities for identification.", marks: 1 },
    { question_text: "What is denormalization and when would you use it?", expected_answer: "Denormalization intentionally adds redundancy to normalized tables to improve read performance. It reduces JOIN operations by combining tables or adding redundant columns. Used when read performance is critical (reporting, analytics), query patterns are well-known, and write overhead is acceptable. Trade-offs include increased storage, update anomalies, and data inconsistency risk.", marks: 1 },
  ],
  HTML: [
    { question_text: "Explain the concept of semantic HTML. Why is it important and give examples of semantic elements.", expected_answer: "Semantic HTML uses elements that convey meaning about their content (header, nav, main, article, section, footer, aside, figure). Benefits: better accessibility for screen readers, improved SEO as search engines understand content structure, cleaner code, and easier maintenance. Non-semantic elements like div and span don't describe their content.", marks: 1 },
    { question_text: "What is the Document Object Model (DOM)? How does it relate to HTML?", expected_answer: "The DOM is a tree-structured representation of an HTML document created by the browser. Each HTML element becomes a node in the tree. JavaScript can access and manipulate DOM nodes to dynamically change content, structure, and styling. The DOM provides APIs like getElementById, querySelector, createElement for programmatic page manipulation.", marks: 1 },
    { question_text: "Explain HTML5 form validation attributes and their usage.", expected_answer: "HTML5 provides built-in validation: required (mandatory fields), pattern (regex validation), min/max (numeric ranges), minlength/maxlength (text length), type-specific validation (email, url, number, date), step (numeric increments). The novalidate attribute disables validation. Custom validity can be set via JavaScript's setCustomValidity() method.", marks: 1 },
    { question_text: "What are HTML5 APIs? Explain Web Storage, Geolocation, and Canvas.", expected_answer: "Web Storage: localStorage (persistent) and sessionStorage (per-session) for client-side key-value storage, replacing cookies for large data. Geolocation API: navigator.geolocation provides user's location with permission. Canvas API: <canvas> element with JavaScript drawing context for 2D graphics, animations, and image manipulation using methods like fillRect, drawImage, arc.", marks: 1 },
    { question_text: "Explain the concept of accessibility (a11y) in HTML. What are ARIA attributes?", expected_answer: "Accessibility ensures web content is usable by people with disabilities. Practices include proper heading hierarchy, alt text for images, form labels, keyboard navigation, and sufficient color contrast. ARIA (Accessible Rich Internet Applications) attributes like role, aria-label, aria-hidden, aria-live enhance accessibility for dynamic content and custom widgets.", marks: 1 },
    { question_text: "What is the difference between block-level and inline elements? Give examples.", expected_answer: "Block-level elements (div, p, h1-h6, section, article) start on a new line, take full width, and can contain other block/inline elements. Inline elements (span, a, strong, em, img) don't start new lines, only take needed width, and can't contain block elements. display property can change this behavior. HTML5 uses content categories instead.", marks: 1 },
    { question_text: "Explain the HTML document structure and the purpose of DOCTYPE, head, and meta tags.", expected_answer: "DOCTYPE (<!DOCTYPE html>) tells the browser which HTML version to use, preventing quirks mode. The <head> contains metadata: <title> for page title, <meta charset> for encoding, <meta viewport> for responsive design, <link> for stylesheets, <script> for JavaScript. <meta> tags include description, keywords, Open Graph tags for SEO and social sharing.", marks: 1 },
    { question_text: "What are iframes in HTML? What are their uses and security concerns?", expected_answer: "iframes (<iframe>) embed external HTML documents within a page. Uses include embedding maps, videos, ads, and third-party widgets. Security concerns: clickjacking attacks, cross-site scripting via malicious embedded content. Mitigations: sandbox attribute restricts iframe capabilities, X-Frame-Options header prevents embedding, Content-Security-Policy frame-ancestors directive controls embedding.", marks: 1 },
    { question_text: "Explain responsive web design principles in HTML.", expected_answer: "Responsive design adapts layouts to different screen sizes. Key principles: viewport meta tag (width=device-width), fluid grids using percentages, flexible images (max-width: 100%), CSS media queries for breakpoints, mobile-first approach. HTML elements like <picture> and srcset provide responsive images. CSS frameworks like Bootstrap provide responsive grid systems.", marks: 1 },
    { question_text: "What are Web Components? Explain Custom Elements, Shadow DOM, and Templates.", expected_answer: "Web Components are reusable custom HTML elements. Custom Elements define new HTML tags with JavaScript classes extending HTMLElement. Shadow DOM provides encapsulated DOM and styling, preventing style leakage. HTML Templates (<template>) hold markup not rendered until instantiated via JavaScript. Slots (<slot>) enable content projection into shadow DOM.", marks: 1 },
  ],
  CSS: [
    { question_text: "Explain the CSS Box Model in detail. How do margin, border, padding, and content work together?", expected_answer: "The box model wraps every HTML element: Content (actual text/image), Padding (space between content and border), Border (surrounds padding), Margin (space outside border). box-sizing: content-box (default) means width/height apply to content only. box-sizing: border-box includes padding and border in width/height, simplifying layouts.", marks: 1 },
    { question_text: "What is Flexbox? Explain its main properties and how it handles layout.", expected_answer: "Flexbox is a one-dimensional layout model for arranging items in rows or columns. Container properties: display:flex, flex-direction, justify-content (main axis alignment), align-items (cross axis), flex-wrap, gap. Item properties: flex-grow, flex-shrink, flex-basis, align-self, order. It handles dynamic sizing, equal heights, and centering elegantly.", marks: 1 },
    { question_text: "Explain CSS Grid Layout. How does it differ from Flexbox?", expected_answer: "CSS Grid is a two-dimensional layout system handling both rows and columns simultaneously. Properties: grid-template-columns/rows, grid-gap, grid-area, grid-template-areas for named regions. Differs from Flexbox: Grid is 2D (rows+columns), Flexbox is 1D (row or column). Grid is layout-first (define grid, place items), Flexbox is content-first.", marks: 1 },
    { question_text: "What is CSS specificity? How is it calculated and how does it resolve conflicts?", expected_answer: "Specificity determines which CSS rule applies when multiple rules target the same element. Calculated as (inline, IDs, classes/attributes/pseudo-classes, elements/pseudo-elements). Inline styles: 1000, IDs: 100, classes: 10, elements: 1. Higher specificity wins. Equal specificity: later rule wins. !important overrides all but should be avoided.", marks: 1 },
    { question_text: "Explain CSS positioning: static, relative, absolute, fixed, and sticky.", expected_answer: "Static: default flow. Relative: positioned relative to its normal position, space still reserved. Absolute: positioned relative to nearest positioned ancestor, removed from flow. Fixed: positioned relative to viewport, doesn't scroll. Sticky: acts as relative until scroll threshold, then becomes fixed. z-index controls stacking order for positioned elements.", marks: 1 },
    { question_text: "What are CSS transitions and animations? How do they differ?", expected_answer: "Transitions smoothly change property values over duration when triggered (hover, class change). Properties: transition-property, transition-duration, transition-timing-function, transition-delay. Animations use @keyframes for complex multi-step sequences that can loop. Properties: animation-name, animation-duration, animation-iteration-count. Transitions need triggers; animations can auto-play.", marks: 1 },
    { question_text: "Explain CSS media queries and responsive design breakpoints.", expected_answer: "Media queries apply styles conditionally based on device characteristics: @media (max-width: 768px) {}. Common breakpoints: mobile (<576px), tablet (576-768px), desktop (>992px). Features include width, height, orientation, resolution, prefers-color-scheme. Mobile-first approach uses min-width. Media queries enable responsive typography, layout changes, and hiding/showing elements.", marks: 1 },
    { question_text: "What are CSS custom properties (variables)? How do they work with inheritance?", expected_answer: "CSS custom properties (--variable-name) store reusable values, accessed via var(--variable-name, fallback). Defined in any selector, commonly :root for global scope. They cascade and inherit like regular properties. Can be changed dynamically with JavaScript. They enable theming, reduce repetition, and can be scoped to components. They differ from preprocessor variables by being runtime.", marks: 1 },
    { question_text: "Explain the concept of CSS preprocessors. What are the benefits of using SASS/SCSS?", expected_answer: "CSS preprocessors extend CSS with programming features. SASS/SCSS provides: variables ($color: red), nesting (parent & child selectors), mixins (@mixin for reusable blocks), functions, partials (@import for modular files), inheritance (@extend), and operators. Benefits: DRY code, maintainability, modularity. SCSS is superset syntax; SASS uses indentation.", marks: 1 },
    { question_text: "What is the CSS cascade? Explain how origin, specificity, and order determine applied styles.", expected_answer: "The cascade resolves conflicts when multiple rules target an element. Order of precedence: 1) Origin and importance (user !important > author !important > author > user > browser default), 2) Specificity (inline > ID > class > element), 3) Source order (later rules win). Understanding cascade prevents unexpected styling and reduces need for !important.", marks: 1 },
  ],
  "Digital Electronics": [
    { question_text: "Explain the difference between combinational and sequential circuits with examples.", expected_answer: "Combinational circuits' output depends only on current inputs (no memory). Examples: adders, multiplexers, decoders, encoders. Sequential circuits' output depends on current inputs AND previous state (has memory). Examples: flip-flops, counters, registers, shift registers. Sequential circuits use feedback and clock signals for state storage.", marks: 1 },
    { question_text: "What are Karnaugh Maps (K-Maps)? Explain how to simplify Boolean expressions using K-Maps.", expected_answer: "K-Maps are graphical tools for simplifying Boolean expressions. Variables are arranged in Gray code order. Adjacent cells (differing by one bit) are grouped in powers of 2. Groups represent simplified product terms. Larger groups = simpler terms. Don't-care conditions can be included in groups. K-Maps work well for up to 4-5 variables.", marks: 1 },
    { question_text: "Explain the working of SR, JK, D, and T flip-flops.", expected_answer: "SR flip-flop: Set (S=1,R=0) sets Q=1, Reset (S=0,R=1) sets Q=0, S=R=1 is invalid. JK flip-flop: Like SR but J=K=1 toggles output, eliminating invalid state. D flip-flop: Output follows Data input on clock edge (D=1→Q=1). T flip-flop: Toggle - T=1 toggles output on clock edge, T=0 holds. All are edge-triggered or level-triggered.", marks: 1 },
    { question_text: "What is the difference between synchronous and asynchronous counters? Explain with examples.", expected_answer: "Synchronous counters: all flip-flops receive the same clock signal simultaneously, changing state together. Faster, no propagation delay accumulation. Example: synchronous 4-bit binary counter. Asynchronous (ripple) counters: clock input of each flip-flop comes from output of previous one. Simpler but slower due to cumulative propagation delay.", marks: 1 },
    { question_text: "Explain the concept of number systems and conversions between binary, octal, decimal, and hexadecimal.", expected_answer: "Binary (base-2): digits 0,1. Octal (base-8): digits 0-7. Decimal (base-10): digits 0-9. Hexadecimal (base-16): digits 0-9, A-F. Conversions: binary to decimal using positional weights, decimal to binary using repeated division by 2, binary to octal/hex by grouping 3/4 bits respectively. Each system has advantages for different applications.", marks: 1 },
    { question_text: "What are multiplexers and demultiplexers? Explain their applications.", expected_answer: "Multiplexer (MUX): selects one of many inputs and routes it to a single output using select lines. 2^n inputs need n select lines. Applications: data routing, function generation, parallel-to-serial conversion. Demultiplexer (DEMUX): routes single input to one of many outputs. Applications: serial-to-parallel conversion, address decoding, data distribution.", marks: 1 },
    { question_text: "Explain Boolean algebra and its fundamental theorems (De Morgan's, duality, etc.).", expected_answer: "Boolean algebra uses binary variables and logical operations (AND, OR, NOT). Key theorems: De Morgan's: (A·B)' = A'+B' and (A+B)' = A'·B'. Duality: swap AND↔OR and 0↔1. Other laws: commutative, associative, distributive, absorption (A+A·B=A), consensus. These enable systematic simplification of digital logic expressions.", marks: 1 },
    { question_text: "What is an ADC and DAC? Explain the conversion process.", expected_answer: "ADC (Analog-to-Digital Converter) converts continuous analog signals to discrete digital values through sampling, quantization, and encoding. Types: flash (fast), successive approximation (balanced), sigma-delta (high resolution). DAC (Digital-to-Analog Converter) converts digital values to analog signals using weighted resistors or R-2R ladder networks. Resolution is measured in bits.", marks: 1 },
    { question_text: "Explain the concept of memory in digital systems: RAM, ROM, and their types.", expected_answer: "RAM (Random Access Memory): volatile, read-write. SRAM uses flip-flops (fast, expensive, cache). DRAM uses capacitors (slower, cheaper, main memory, needs refresh). ROM (Read-Only Memory): non-volatile, read-only. Types: PROM (one-time programmable), EPROM (UV erasable), EEPROM (electrically erasable), Flash (block erasable, used in SSDs/USBs).", marks: 1 },
    { question_text: "What are programmable logic devices (PLD)? Explain PLA, PAL, and FPGA.", expected_answer: "PLDs are configurable digital circuits. PLA (Programmable Logic Array): both AND and OR planes programmable, most flexible but slower. PAL (Programmable Array Logic): programmable AND plane, fixed OR plane, faster. FPGA (Field Programmable Gate Array): contains configurable logic blocks, interconnects, and I/O blocks. FPGAs are reconfigurable and used for prototyping and complex designs.", marks: 1 },
  ],
  "Analog Electronics": [
    { question_text: "Explain the working principle of a PN junction diode and its V-I characteristics.", expected_answer: "A PN junction forms when P-type (holes) and N-type (electrons) semiconductors join, creating a depletion region. Forward bias reduces depletion width, allowing current flow above threshold voltage (~0.7V for Si). Reverse bias widens depletion region, only leakage current flows until breakdown voltage. V-I curve shows exponential forward current and sharp reverse breakdown.", marks: 1 },
    { question_text: "What is an operational amplifier (Op-Amp)? Explain its ideal characteristics and basic configurations.", expected_answer: "An Op-Amp is a high-gain differential amplifier with two inputs (inverting, non-inverting) and one output. Ideal characteristics: infinite open-loop gain, infinite input impedance, zero output impedance, infinite bandwidth. Basic configurations: inverting amplifier (gain = -Rf/Rin), non-inverting (gain = 1+Rf/Rin), voltage follower, summing amplifier, difference amplifier.", marks: 1 },
    { question_text: "Explain the different types of filters: low-pass, high-pass, band-pass, and band-stop.", expected_answer: "Low-pass filter passes frequencies below cutoff, attenuates higher frequencies (RC circuit with output across capacitor). High-pass passes frequencies above cutoff (output across resistor). Band-pass passes frequencies within a range (combines LP and HP). Band-stop (notch) rejects a frequency range. Characterized by cutoff frequency, order, and roll-off rate (dB/decade).", marks: 1 },
    { question_text: "What is feedback in amplifier circuits? Explain positive and negative feedback.", expected_answer: "Feedback returns part of output to input. Negative feedback (output opposes input): reduces gain but improves stability, bandwidth, linearity, and reduces distortion. Used in most amplifier circuits. Positive feedback (output reinforces input): increases gain, can cause instability/oscillation. Used in oscillators, comparators, and Schmitt triggers. Feedback factor β determines the fraction returned.", marks: 1 },
    { question_text: "Explain the working of BJT transistor in different configurations (CE, CB, CC).", expected_answer: "BJT (Bipolar Junction Transistor) has three terminals: Base, Collector, Emitter. Common Emitter (CE): most used, high voltage and current gain, 180° phase inversion. Common Base (CB): high voltage gain, no current gain, good high-frequency response. Common Collector (CC/emitter follower): unity voltage gain, high current gain, high input impedance, used as buffer.", marks: 1 },
    { question_text: "What is the difference between Class A, B, AB, and C power amplifiers?", expected_answer: "Class A: conducts full cycle (360°), low distortion, max efficiency ~25% (50% with transformer). Class B: conducts half cycle (180°), higher efficiency ~78.5%, crossover distortion. Class AB: slightly more than half cycle, reduces crossover distortion, practical efficiency ~60%. Class C: conducts less than half cycle (<180°), highest efficiency ~80%, used in RF with tuned circuits.", marks: 1 },
    { question_text: "Explain the concept of oscillators. What are the Barkhausen criteria?", expected_answer: "Oscillators generate periodic waveforms without external input. Barkhausen criteria for sustained oscillation: 1) Loop gain |Aβ| = 1 (gain equals losses), 2) Total phase shift around loop = 0° or 360°. Types: RC oscillators (Wien bridge, phase shift) for low frequencies, LC oscillators (Colpitts, Hartley) for high frequencies, crystal oscillators for precise frequencies.", marks: 1 },
    { question_text: "What are voltage regulators? Explain the working of a Zener diode voltage regulator.", expected_answer: "Voltage regulators maintain constant output voltage despite input variations or load changes. Zener diode regulator: Zener operates in reverse breakdown region where voltage remains nearly constant. Series resistor limits current. When input increases, Zener conducts more current, keeping output stable. Limitations: low efficiency, limited current capacity. IC regulators (78xx, LM317) offer better performance.", marks: 1 },
    { question_text: "Explain MOSFET operation and the difference between enhancement and depletion modes.", expected_answer: "MOSFET (Metal-Oxide-Semiconductor FET) uses gate voltage to control drain current via electric field. Enhancement mode: normally off, requires gate voltage above threshold to create channel and conduct. Depletion mode: normally on, has built-in channel, gate voltage reduces/enhances conduction. MOSFETs have high input impedance, are voltage-controlled, and dominate digital circuits (CMOS).", marks: 1 },
    { question_text: "What is the concept of impedance matching? Why is it important in electronic circuits?", expected_answer: "Impedance matching ensures source impedance equals load impedance (or its conjugate for AC) for maximum power transfer. Mismatched impedances cause signal reflections and power loss. Important in RF circuits, audio systems, and transmission lines. Techniques: transformers, matching networks (L, T, pi), transmission line stubs. In voltage-driven circuits, high input impedance is preferred instead.", marks: 1 },
  ],
  "Embedded Systems": [
    { question_text: "Explain the architecture of a microcontroller and its key components.", expected_answer: "A microcontroller integrates CPU, memory (Flash for program, SRAM for data, EEPROM for persistent storage), and peripherals on a single chip. Key components: ALU for computation, program counter, stack pointer, I/O ports, timers/counters, ADC/DAC, communication interfaces (UART, SPI, I2C), interrupt controller, clock system, and power management unit.", marks: 1 },
    { question_text: "What are interrupts in embedded systems? Explain interrupt handling and priority.", expected_answer: "Interrupts are signals that pause normal execution to handle urgent events. Process: interrupt occurs → current state saved to stack → ISR (Interrupt Service Routine) executes → state restored → normal execution resumes. Priority levels determine which interrupt is serviced first. Types: hardware (external pins, timer overflow) and software (trap instructions). Nested interrupts allow higher-priority interrupts during ISR.", marks: 1 },
    { question_text: "Explain the difference between UART, SPI, and I2C communication protocols.", expected_answer: "UART: asynchronous, full-duplex, 2 wires (TX/RX), point-to-point, configurable baud rate. SPI: synchronous, full-duplex, 4 wires (MOSI/MISO/SCK/SS), master-slave, fast, separate SS per slave. I2C: synchronous, half-duplex, 2 wires (SDA/SCL), multi-master multi-slave with addressing, slower than SPI but fewer wires. Choice depends on speed, distance, and device count requirements.", marks: 1 },
    { question_text: "What is RTOS (Real-Time Operating System)? How does it differ from a general-purpose OS?", expected_answer: "RTOS guarantees deterministic response times for critical tasks. Features: task scheduling (preemptive/cooperative), inter-task communication (queues, semaphores, mutexes), memory management, and timing services. Differs from general OS: predictable timing, minimal latency, priority-based scheduling, smaller footprint. Types: hard real-time (missed deadline = failure) and soft real-time (degraded performance acceptable).", marks: 1 },
    { question_text: "Explain the concept of PWM (Pulse Width Modulation) and its applications.", expected_answer: "PWM generates a digital signal with variable duty cycle (ratio of ON time to total period). By changing duty cycle, average voltage is controlled. Applications: motor speed control, LED dimming, servo motor positioning, power supply regulation, audio generation. Resolution depends on timer bits (8-bit = 256 levels). Frequency selection depends on application requirements.", marks: 1 },
    { question_text: "What is DMA (Direct Memory Access)? How does it improve system performance?", expected_answer: "DMA allows peripherals to transfer data directly to/from memory without CPU involvement. The DMA controller handles the transfer while CPU performs other tasks. Process: CPU configures DMA (source, destination, size) → DMA transfers data → DMA interrupts CPU on completion. Improves performance by reducing CPU overhead for large data transfers (ADC sampling, UART buffers, memory-to-memory copies).", marks: 1 },
    { question_text: "Explain the boot process of an embedded system.", expected_answer: "Boot process: 1) Power-on reset initializes hardware to known state. 2) CPU fetches first instruction from reset vector (usually in Flash/ROM). 3) Bootloader executes: initializes clock, memory, and peripherals. 4) Bootloader loads application code (may from external storage). 5) Application startup: initializes stack, global variables (.data from Flash to RAM, .bss zeroed). 6) Main application runs.", marks: 1 },
    { question_text: "What is the difference between polling and interrupt-driven I/O?", expected_answer: "Polling: CPU continuously checks device status in a loop, simple but wastes CPU cycles waiting. Interrupt-driven: device signals CPU when ready, CPU handles other tasks meanwhile. Polling is predictable and simple for single-device systems. Interrupts are efficient for multiple devices and event-driven scenarios. Hybrid approaches use polling within ISRs or use DMA for high-throughput.", marks: 1 },
    { question_text: "Explain memory-mapped I/O vs port-mapped I/O in embedded systems.", expected_answer: "Memory-mapped I/O: peripheral registers share address space with memory, accessed using same load/store instructions. Simpler programming, C-friendly (pointer access). Port-mapped I/O: separate address space for peripherals, uses special instructions (IN/OUT). Memory-mapped is more common in modern architectures (ARM). Volatile keyword in C prevents compiler optimization of peripheral access.", marks: 1 },
    { question_text: "What are watchdog timers and why are they important in embedded systems?", expected_answer: "Watchdog timer (WDT) is a hardware timer that resets the system if not periodically refreshed ('kicked') by software. If the program hangs or enters an infinite loop, the watchdog expires and resets the processor, recovering from software failures. Important for unattended systems requiring reliability. Configuration includes timeout period and action (reset/interrupt). Must be kicked in main loop, not in ISR.", marks: 1 },
  ],
};

const q = (question_text: string, correct: string, wrong1: string, wrong2: string, wrong3: string): SampleQuestion => ({
  question_text,
  options: [
    { text: correct, is_correct: true },
    { text: wrong1, is_correct: false },
    { text: wrong2, is_correct: false },
    { text: wrong3, is_correct: false },
  ],
  marks: 1,
});

export const sampleQuestions: Record<string, SampleQuestion[]> = {
  Java: [
    q("Which keyword is used to define a class in Java?", "class", "struct", "define", "object"),
    q("What is the default value of an int variable in Java?", "0", "null", "1", "undefined"),
    q("Which method is the entry point of a Java program?", "main()", "start()", "run()", "init()"),
    q("Which of the following is not a primitive data type in Java?", "String", "int", "boolean", "char"),
    q("What does JVM stand for?", "Java Virtual Machine", "Java Variable Method", "Java Verified Machine", "Java Visual Method"),
    q("Which operator is used for string concatenation?", "+", "&", ".", ","),
    q("What is the size of int in Java?", "4 bytes", "2 bytes", "8 bytes", "1 byte"),
    q("Which keyword prevents a class from being inherited?", "final", "static", "private", "abstract"),
    q("What is the parent class of all Java classes?", "Object", "Class", "Main", "Base"),
    q("Which keyword is used to create an object?", "new", "create", "make", "init"),
    q("Which access modifier makes a member accessible only within the same class?", "private", "public", "protected", "default"),
    q("What is method overloading?", "Same method name with different parameters", "Overriding parent methods", "Creating abstract methods", "Using static methods"),
    q("Which collection class allows duplicate elements?", "ArrayList", "HashSet", "TreeSet", "HashMap"),
    q("What does the 'static' keyword mean in Java?", "Belongs to the class, not instance", "Cannot be changed", "Accessible everywhere", "Runs at startup"),
    q("Which interface must be implemented for sorting?", "Comparable", "Serializable", "Runnable", "Iterable"),
    q("What is the purpose of 'this' keyword?", "Refers to current object", "Refers to parent class", "Creates new object", "Imports a class"),
    q("Which exception is thrown when array index is out of bounds?", "ArrayIndexOutOfBoundsException", "NullPointerException", "ClassCastException", "ArithmeticException"),
    q("What is encapsulation?", "Wrapping data and methods together", "Inheriting from parent", "Implementing interfaces", "Method overriding"),
    q("Which keyword is used to inherit a class?", "extends", "implements", "inherits", "using"),
    q("What is polymorphism?", "Object taking many forms", "Hiding implementation", "Single inheritance", "Static binding"),
    q("Which data structure follows LIFO?", "Stack", "Queue", "LinkedList", "ArrayList"),
    q("What is the default value of a boolean in Java?", "false", "true", "null", "0"),
    q("Which loop is guaranteed to execute at least once?", "do-while", "for", "while", "foreach"),
    q("What does the 'super' keyword do?", "Refers to parent class", "Refers to current class", "Creates superclass", "Imports parent"),
    q("Which class is used to read input from the user?", "Scanner", "Reader", "Input", "Console"),
    q("What is an abstract class?", "A class that cannot be instantiated", "A class with only static methods", "A final class", "An interface"),
    q("Which keyword is used for exception handling?", "try", "handle", "error", "except"),
    q("What is the purpose of the 'finally' block?", "Always executes after try-catch", "Handles exceptions", "Defines constants", "Ends the program"),
    q("Which collection uses key-value pairs?", "HashMap", "ArrayList", "LinkedList", "HashSet"),
    q("What is a constructor?", "Special method called during object creation", "A static method", "A destructor", "An interface method"),
    q("What does 'break' do in a loop?", "Exits the loop", "Skips to next iteration", "Pauses execution", "Restarts the loop"),
    q("Which type of inheritance is not supported in Java (for classes)?", "Multiple", "Single", "Multilevel", "Hierarchical"),
    q("What is garbage collection?", "Automatic memory management", "Deleting source files", "Removing comments", "Clearing the console"),
    q("What is the output of 10 % 3?", "1", "3", "0", "10"),
    q("Which keyword makes a variable constant?", "final", "const", "static", "immutable"),
    q("What is an interface in Java?", "A contract with abstract methods", "A concrete class", "A data type", "A package"),
    q("Which method converts a string to an integer?", "Integer.parseInt()", "String.toInt()", "Int.parse()", "Convert.toInteger()"),
    q("What does the 'instanceof' operator do?", "Checks if an object is of a specific type", "Creates an instance", "Compares values", "Copies an object"),
    q("Which package is automatically imported?", "java.lang", "java.util", "java.io", "java.net"),
    q("What is a thread in Java?", "A lightweight process", "A heavy process", "A memory block", "A file stream"),
  ],
  Python: [
    q("Which function is used to print output in Python?", "print()", "echo()", "write()", "output()"),
    q("How do you start a comment in Python?", "#", "//", "/*", "--"),
    q("Which keyword defines a function in Python?", "def", "function", "func", "define"),
    q("What is the output of type(5)?", "<class 'int'>", "integer", "number", "int"),
    q("Which data structure uses key-value pairs?", "Dictionary", "List", "Tuple", "Set"),
    q("What does len() function do?", "Returns length", "Returns last element", "Lengthens a string", "Returns type"),
    q("Python is which type of language?", "Interpreted", "Compiled", "Assembly", "Machine"),
    q("Which of these is immutable?", "Tuple", "List", "Dictionary", "Set"),
    q("What is the result of 3 ** 2?", "9", "6", "5", "8"),
    q("Which keyword is used for loops in Python?", "for", "loop", "each", "iterate"),
    q("What does 'pip' stand for?", "Pip Installs Packages", "Python Install Program", "Package Import Protocol", "Python Interface Platform"),
    q("Which method adds an element to the end of a list?", "append()", "add()", "insert()", "push()"),
    q("What is a lambda function?", "An anonymous function", "A named function", "A class method", "A module"),
    q("How do you create a virtual environment?", "python -m venv env", "python create env", "pip install venv", "virtualenv --start"),
    q("What does 'self' refer to in a class?", "The current instance", "The parent class", "A static variable", "The module"),
    q("Which exception handles division by zero?", "ZeroDivisionError", "ValueError", "TypeError", "ArithmeticError"),
    q("What is list comprehension?", "A concise way to create lists", "A sorting algorithm", "A type of loop", "A module import"),
    q("Which keyword is used for inheritance?", "class Child(Parent):", "class Child extends Parent:", "class Child inherits Parent:", "class Child << Parent:"),
    q("What does the 'with' statement do?", "Context management for resources", "Creates a loop", "Defines a function", "Imports a module"),
    q("How do you handle exceptions in Python?", "try/except", "try/catch", "try/handle", "begin/rescue"),
    q("What is a decorator in Python?", "A function that modifies another function", "A class attribute", "A loop construct", "A variable type"),
    q("Which method removes whitespace from both ends of a string?", "strip()", "trim()", "clean()", "remove()"),
    q("What is the difference between '==' and 'is'?", "'==' compares values, 'is' compares identity", "They are identical", "'is' compares values, '==' compares identity", "'is' is for strings only"),
    q("Which built-in function returns the largest item?", "max()", "largest()", "big()", "top()"),
    q("What does the 'yield' keyword do?", "Creates a generator", "Returns a value and exits", "Raises an exception", "Imports a module"),
    q("How do you open a file for reading?", "open('file.txt', 'r')", "read('file.txt')", "file.open('r')", "open('file.txt', 'read')"),
    q("What is a module in Python?", "A file containing Python code", "A type of variable", "A loop construct", "A data type"),
    q("Which data type is ordered and changeable?", "List", "Tuple", "Set", "Frozenset"),
    q("What does the map() function do?", "Applies a function to each item in an iterable", "Creates a dictionary", "Maps keys to values", "Draws a map"),
    q("What is the output of bool('')?", "False", "True", "None", "Error"),
    q("Which method sorts a list in place?", "sort()", "sorted()", "order()", "arrange()"),
    q("What is __init__ in Python?", "Constructor method", "Destructor method", "Static method", "Class method"),
    q("How do you import a specific function from a module?", "from module import function", "import function from module", "include module.function", "require module.function"),
    q("What is slicing in Python?", "Extracting a portion of a sequence", "Cutting strings permanently", "Dividing numbers", "Splitting files"),
    q("Which keyword exits a loop prematurely?", "break", "exit", "stop", "end"),
    q("What is a set in Python?", "An unordered collection of unique elements", "An ordered list", "A key-value store", "A type of tuple"),
    q("What does the enumerate() function return?", "Index and value pairs", "Only values", "Only indices", "A dictionary"),
    q("Which method joins list elements into a string?", "join()", "concat()", "merge()", "combine()"),
    q("What is the Global Interpreter Lock (GIL)?", "A mutex preventing multiple threads from executing Python bytecode simultaneously", "A security feature", "A file lock", "A database lock"),
    q("What is the output of range(5)?", "0, 1, 2, 3, 4", "1, 2, 3, 4, 5", "0, 1, 2, 3, 4, 5", "1, 2, 3, 4"),
  ],
  C: [
    q("Which header file is required for printf()?", "stdio.h", "stdlib.h", "string.h", "conio.h"),
    q("What is the size of char in C?", "1 byte", "2 bytes", "4 bytes", "8 bytes"),
    q("Which symbol is used for pointer declaration?", "*", "&", "#", "@"),
    q("What does malloc() return?", "A pointer", "An integer", "A string", "Nothing"),
    q("Which loop checks condition first?", "while", "do-while", "for-each", "goto"),
    q("What does sizeof() return?", "Size in bytes", "Number of elements", "Length of string", "Memory address"),
    q("Which keyword is used for constants?", "const", "final", "static", "fix"),
    q("What is a struct in C?", "User-defined data type", "Built-in function", "Loop construct", "Header file"),
    q("What does '\\n' represent?", "Newline", "Null", "Number", "Nothing"),
    q("Which operator is used for address-of?", "&", "*", "#", "@"),
    q("What is a pointer in C?", "A variable storing a memory address", "A data type", "A function", "A loop"),
    q("Which function is used to allocate memory dynamically?", "malloc()", "alloc()", "new()", "create()"),
    q("What is the difference between '++i' and 'i++'?", "++i increments before use, i++ after", "No difference", "i++ increments before use", "++i is invalid"),
    q("Which function frees dynamically allocated memory?", "free()", "delete()", "remove()", "dealloc()"),
    q("What does the 'void' keyword mean?", "No return type", "Empty variable", "Null pointer", "Default type"),
    q("What is a segmentation fault?", "Accessing invalid memory", "Syntax error", "Logical error", "Compilation error"),
    q("Which format specifier is used for float?", "%f", "%d", "%c", "%s"),
    q("What is recursion?", "A function calling itself", "A loop construct", "Variable declaration", "Pointer arithmetic"),
    q("What is the null character in C?", "\\0", "\\n", "NULL", "\\t"),
    q("Which keyword is used to define a type alias?", "typedef", "define", "alias", "type"),
    q("What is the scope of a local variable?", "Within the function it is declared", "Entire program", "Within the file", "Global scope"),
    q("What does 'static' do to a local variable?", "Preserves value between function calls", "Makes it global", "Makes it constant", "Deletes after use"),
    q("Which header provides string functions?", "string.h", "str.h", "strings.h", "text.h"),
    q("What is an array in C?", "Collection of same-type elements", "A pointer type", "A function", "A struct"),
    q("What does the 'break' statement do?", "Exits the loop or switch", "Pauses execution", "Skips an iteration", "Ends the program"),
    q("Which function copies one string to another?", "strcpy()", "strcp()", "copy()", "stringcopy()"),
    q("What is a union in C?", "Members share the same memory", "Same as struct", "A data type", "A loop"),
    q("What does '#include' do?", "Includes a header file", "Defines a variable", "Creates a function", "Starts a loop"),
    q("Which operator accesses struct members?", ".", "->", "&", "*"),
    q("What is the difference between calloc() and malloc()?", "calloc initializes to zero", "No difference", "malloc initializes to zero", "calloc is faster"),
    q("What are command line arguments?", "Arguments passed to main()", "Compiler flags", "Error messages", "Debug options"),
    q("Which function compares two strings?", "strcmp()", "strcomp()", "compare()", "streq()"),
    q("What is a macro in C?", "A preprocessor directive for text substitution", "A function type", "A variable type", "A loop construct"),
    q("What does 'continue' do in a loop?", "Skips to next iteration", "Exits the loop", "Pauses execution", "Restarts the loop"),
    q("What is an enum in C?", "A set of named integer constants", "A float type", "A string type", "A struct type"),
    q("Which operator dereferences a pointer?", "*", "&", "->", "."),
    q("What does 'extern' keyword do?", "Declares a variable defined elsewhere", "Creates a local variable", "Makes variable constant", "Deletes a variable"),
    q("What is the output of printf(\"%d\", 5/2)?", "2", "2.5", "3", "2.0"),
    q("Which function reads a string from input?", "scanf()", "read()", "input()", "get()"),
    q("What is a dangling pointer?", "A pointer to freed memory", "A null pointer", "An array pointer", "A function pointer"),
  ],
  DBMS: [
    q("What does SQL stand for?", "Structured Query Language", "Simple Query Language", "Standard Query Logic", "System Query Language"),
    q("Which command creates a new table?", "CREATE TABLE", "NEW TABLE", "MAKE TABLE", "ADD TABLE"),
    q("What is a primary key?", "Unique identifier for a row", "First column", "Table name", "Database name"),
    q("Which normal form eliminates partial dependency?", "2NF", "1NF", "3NF", "BCNF"),
    q("What does JOIN do?", "Combines rows from tables", "Deletes rows", "Creates indexes", "Sorts data"),
    q("Which keyword removes duplicates?", "DISTINCT", "UNIQUE", "REMOVE", "CLEAN"),
    q("What is a foreign key?", "Reference to primary key of another table", "External database key", "Encrypted key", "Alternate key"),
    q("Which command deletes all rows quickly?", "TRUNCATE", "REMOVE ALL", "CLEAR", "ERASE"),
    q("What is an index used for?", "Speed up queries", "Add constraints", "Create backups", "Encrypt data"),
    q("Which is a DDL command?", "ALTER", "SELECT", "INSERT", "UPDATE"),
    q("What is normalization?", "Reducing data redundancy", "Adding more data", "Creating backups", "Encrypting data"),
    q("Which SQL clause filters grouped results?", "HAVING", "WHERE", "FILTER", "GROUP BY"),
    q("What is a view in SQL?", "A virtual table based on a query", "A physical table", "An index", "A stored procedure"),
    q("Which aggregate function counts rows?", "COUNT()", "SUM()", "TOTAL()", "NUM()"),
    q("What is ACID in databases?", "Atomicity, Consistency, Isolation, Durability", "Add, Create, Insert, Delete", "Automatic Commit In Database", "Access Control and Identity"),
    q("Which type of JOIN returns all rows from the left table?", "LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "CROSS JOIN"),
    q("What is a stored procedure?", "Precompiled SQL code stored in the database", "A table type", "A view", "An index"),
    q("Which command modifies existing data?", "UPDATE", "MODIFY", "CHANGE", "ALTER"),
    q("What is a candidate key?", "A column that can uniquely identify rows", "The primary key only", "A foreign key", "An index"),
    q("What does GROUP BY do?", "Groups rows with same values", "Sorts data", "Filters rows", "Joins tables"),
    q("What is a trigger in SQL?", "Automatic action on table events", "A manual command", "A type of index", "A stored function"),
    q("Which constraint ensures non-null values?", "NOT NULL", "REQUIRED", "MANDATORY", "NON_EMPTY"),
    q("What is denormalization?", "Adding redundancy for performance", "Removing tables", "Creating indexes", "Encrypting data"),
    q("Which command removes a table completely?", "DROP TABLE", "DELETE TABLE", "REMOVE TABLE", "CLEAR TABLE"),
    q("What is a subquery?", "A query nested inside another query", "A type of JOIN", "A stored procedure", "An index"),
    q("Which isolation level prevents dirty reads?", "READ COMMITTED", "READ UNCOMMITTED", "SERIALIZABLE", "REPEATABLE READ"),
    q("What is a composite key?", "A key made of multiple columns", "A single-column key", "An auto-increment key", "A foreign key"),
    q("Which function returns the average value?", "AVG()", "MEAN()", "AVERAGE()", "MID()"),
    q("What is a deadlock?", "Two transactions waiting for each other", "A slow query", "A syntax error", "A broken index"),
    q("Which command adds a new column to a table?", "ALTER TABLE ADD", "MODIFY TABLE ADD", "UPDATE TABLE ADD", "INSERT COLUMN"),
    q("What is referential integrity?", "Ensuring foreign key references valid primary keys", "Data encryption", "Index optimization", "Query caching"),
    q("Which type of relationship is many-to-many?", "Requires a junction table", "Uses a foreign key directly", "Is not possible in RDBMS", "Uses a view"),
    q("What is a transaction?", "A unit of work that is atomic", "A single SQL statement", "A table operation", "A database backup"),
    q("Which SQL operator checks for a range?", "BETWEEN", "RANGE", "WITHIN", "FROM-TO"),
    q("What is a cursor?", "A pointer to query result rows", "A table name", "A column type", "A constraint"),
    q("Which command grants permissions?", "GRANT", "ALLOW", "PERMIT", "ENABLE"),
    q("What is sharding?", "Distributing data across multiple databases", "Creating backups", "Encrypting data", "Indexing tables"),
    q("Which clause sorts query results?", "ORDER BY", "SORT BY", "ARRANGE BY", "RANK BY"),
    q("What is a materialized view?", "A view with stored results", "A regular view", "An index", "A temporary table"),
    q("What does COALESCE() do?", "Returns first non-null value", "Counts nulls", "Removes nulls", "Replaces all values"),
  ],
  HTML: [
    q("What does HTML stand for?", "HyperText Markup Language", "High Tech Modern Language", "Hyper Transfer Markup Language", "Home Tool Markup Language"),
    q("Which tag creates a hyperlink?", "<a>", "<link>", "<href>", "<url>"),
    q("Which tag is used for largest heading?", "<h1>", "<heading>", "<head>", "<h6>"),
    q("Which attribute specifies image source?", "src", "href", "link", "source"),
    q("Which tag creates a list item?", "<li>", "<list>", "<item>", "<ul>"),
    q("What is the correct DOCTYPE for HTML5?", "<!DOCTYPE html>", "<!DOCTYPE HTML5>", "<DOCTYPE html>", "<!HTML5>"),
    q("Which tag creates a paragraph?", "<p>", "<para>", "<text>", "<paragraph>"),
    q("Which element defines the body?", "<body>", "<content>", "<main>", "<page>"),
    q("Which tag is used for line break?", "<br>", "<lb>", "<break>", "<newline>"),
    q("Which tag creates a table?", "<table>", "<tab>", "<grid>", "<tbl>"),
    q("Which tag is used for an unordered list?", "<ul>", "<ol>", "<list>", "<dl>"),
    q("What does the 'alt' attribute do on an image?", "Provides alternative text", "Sets alignment", "Defines the title", "Adds a link"),
    q("Which tag defines a section in a document?", "<section>", "<div>", "<part>", "<block>"),
    q("Which input type creates a checkbox?", "checkbox", "check", "tick", "box"),
    q("What is the purpose of the <meta> tag?", "Provides metadata about the document", "Creates a menu", "Defines a method", "Adds multimedia"),
    q("Which tag is used for bold text?", "<strong>", "<bold>", "<b>", "<em>"),
    q("What does the 'action' attribute in <form> specify?", "Where to send form data", "The form style", "The form name", "Input validation"),
    q("Which tag embeds a video?", "<video>", "<media>", "<movie>", "<embed>"),
    q("What is a semantic HTML element?", "An element that describes its meaning", "Any div element", "A styled element", "A JavaScript element"),
    q("Which tag defines a navigation section?", "<nav>", "<navigation>", "<menu>", "<navbar>"),
    q("What does the 'target=\"_blank\"' attribute do?", "Opens link in a new tab", "Opens link in the same tab", "Downloads the link", "Closes the tab"),
    q("Which tag creates a dropdown list?", "<select>", "<dropdown>", "<list>", "<option>"),
    q("What is the <canvas> element used for?", "Drawing graphics via JavaScript", "Displaying text", "Creating forms", "Embedding videos"),
    q("Which attribute uniquely identifies an element?", "id", "class", "name", "key"),
    q("What does the <footer> tag represent?", "Footer of a section or page", "Bottom margin", "A footnote", "Copyright notice"),
    q("Which tag defines a table row?", "<tr>", "<row>", "<td>", "<th>"),
    q("What is the difference between <div> and <span>?", "div is block-level, span is inline", "They are the same", "span is block-level", "div is inline"),
    q("Which attribute specifies the language of the document?", "lang", "language", "locale", "lng"),
    q("What does the <header> tag represent?", "Introductory content or navigation", "The <head> section", "A heading", "Metadata"),
    q("Which tag creates a text input field?", "<input type=\"text\">", "<textfield>", "<text>", "<input type=\"string\">"),
    q("What is the purpose of the <aside> element?", "Content tangentially related to the main content", "A sidebar menu", "An advertisement", "A comment"),
    q("Which attribute disables an input element?", "disabled", "readonly", "inactive", "off"),
    q("What does the <details> tag do?", "Creates a collapsible disclosure widget", "Shows metadata", "Defines a description list", "Creates a dialog"),
    q("Which tag defines a table header cell?", "<th>", "<thead>", "<header>", "<hd>"),
    q("What is the purpose of the 'placeholder' attribute?", "Shows hint text in an input", "Sets default value", "Labels the input", "Validates input"),
    q("Which tag is used for emphasized text?", "<em>", "<emphasis>", "<italic>", "<i>"),
    q("What does the 'required' attribute do?", "Makes a form field mandatory", "Adds a red border", "Sets focus", "Validates email"),
    q("Which tag groups related form elements?", "<fieldset>", "<formgroup>", "<group>", "<inputgroup>"),
    q("What is the <article> element used for?", "Self-contained composition", "A blog page", "A paragraph", "A section"),
    q("Which attribute specifies a tooltip text?", "title", "tooltip", "hint", "alt"),
  ],
  CSS: [
    q("What does CSS stand for?", "Cascading Style Sheets", "Creative Style Sheets", "Computer Style Sheets", "Colorful Style Sheets"),
    q("Which property changes text color?", "color", "text-color", "font-color", "foreground"),
    q("How do you select an element by ID?", "#id", ".id", "id:", "*id"),
    q("Which property adds space inside an element?", "padding", "margin", "spacing", "border"),
    q("What is the default position value?", "static", "relative", "absolute", "fixed"),
    q("Which property makes text bold?", "font-weight", "text-style", "font-bold", "text-weight"),
    q("How do you select elements by class?", ".classname", "#classname", "classname:", "*classname"),
    q("Which display value hides an element?", "none", "hidden", "invisible", "off"),
    q("Which property creates flex layout?", "display: flex", "layout: flex", "flex: true", "type: flex"),
    q("Which unit is relative to viewport width?", "vw", "pw", "%w", "rw"),
    q("What is the CSS box model?", "Content, padding, border, margin", "Header, body, footer", "Div, span, p", "Flex, grid, block"),
    q("Which property sets the background image?", "background-image", "bg-image", "image", "background-src"),
    q("What does 'z-index' control?", "Stacking order of elements", "Zoom level", "Z-axis rotation", "Height"),
    q("Which property controls the space between lines?", "line-height", "line-spacing", "text-spacing", "letter-spacing"),
    q("What is a CSS pseudo-class?", "A keyword added to a selector for a special state", "A class in HTML", "A JavaScript function", "A media type"),
    q("Which property adds rounded corners?", "border-radius", "corner-radius", "border-round", "round-corner"),
    q("What does 'inherit' value do?", "Takes value from parent element", "Uses browser default", "Removes the property", "Sets to zero"),
    q("Which property controls element overflow?", "overflow", "scroll", "clip", "hide"),
    q("What is the difference between 'em' and 'rem'?", "em is relative to parent, rem to root", "They are the same", "rem is relative to parent", "em is absolute"),
    q("Which property creates CSS animations?", "animation", "transition", "transform", "motion"),
    q("What is a media query used for?", "Responsive design based on conditions", "Playing media files", "Querying databases", "Loading images"),
    q("Which property aligns items on the cross axis in flexbox?", "align-items", "justify-content", "flex-align", "vertical-align"),
    q("What does 'opacity: 0' do?", "Makes element fully transparent but still in layout", "Hides element from DOM", "Removes element", "Makes element semi-transparent"),
    q("Which selector targets the first child?", ":first-child", ":first", ":initial", ":start"),
    q("What is CSS Grid?", "A two-dimensional layout system", "A table system", "A font system", "A color system"),
    q("Which property sets element width to include padding and border?", "box-sizing: border-box", "width-mode: full", "sizing: include-all", "box-model: full"),
    q("What does 'float' do?", "Positions element to left or right", "Makes element invisible", "Animates element", "Centers element"),
    q("Which property controls the gap between grid items?", "gap", "grid-spacing", "cell-gap", "item-gap"),
    q("What is specificity in CSS?", "How the browser decides which rules apply", "The speed of rendering", "The order of stylesheets", "The size of CSS file"),
    q("Which pseudo-element adds content before an element?", "::before", "::start", "::pre", "::first"),
    q("What does 'transition' property do?", "Smoothly animates property changes", "Moves elements", "Changes display type", "Sets timing"),
    q("Which property makes text uppercase?", "text-transform: uppercase", "font-case: upper", "text-case: upper", "letter-case: uppercase"),
    q("What is the 'calc()' function used for?", "Performing calculations in CSS", "Calling JavaScript", "Counting elements", "Computing colors"),
    q("Which property controls flex item order?", "order", "flex-order", "sort", "position"),
    q("What does 'position: sticky' do?", "Toggles between relative and fixed based on scroll", "Sticks to top always", "Makes element immovable", "Fixes to bottom"),
    q("Which property sets the shadow of text?", "text-shadow", "font-shadow", "shadow-text", "text-glow"),
    q("What is the 'clamp()' function?", "Sets a value between a minimum and maximum", "Clamps elements together", "Limits animations", "Groups selectors"),
    q("Which property controls the direction of flex items?", "flex-direction", "flex-flow", "direction", "flex-orient"),
    q("What does 'will-change' property do?", "Hints browser about upcoming changes for optimization", "Forces a change", "Changes immediately", "Prevents changes"),
    q("Which unit is relative to the font size of the root element?", "rem", "em", "px", "vw"),
  ],
  "Digital Electronics": [
    q("What is the output of AND gate when both inputs are 1?", "1", "0", "Undefined", "High impedance"),
    q("Which gate is called the universal gate?", "NAND", "AND", "OR", "XOR"),
    q("What is the binary equivalent of decimal 10?", "1010", "1100", "1001", "1110"),
    q("How many bits are in a nibble?", "4", "8", "2", "16"),
    q("What does a flip-flop store?", "1 bit", "1 byte", "4 bits", "1 word"),
    q("Which number system has base 16?", "Hexadecimal", "Octal", "Binary", "Decimal"),
    q("What is De Morgan's theorem about?", "Complement of AND/OR operations", "Binary addition", "Flip-flop design", "Memory addressing"),
    q("Which circuit adds two binary digits?", "Half adder", "Multiplexer", "Decoder", "Counter"),
    q("What is the truth table output of NOT gate for input 1?", "0", "1", "Undefined", "Both"),
    q("How many inputs does a 4:1 MUX have?", "4", "1", "2", "8"),
    q("What is the output of XOR gate when both inputs are the same?", "0", "1", "Undefined", "High impedance"),
    q("Which flip-flop has two inputs S and R?", "SR flip-flop", "D flip-flop", "JK flip-flop", "T flip-flop"),
    q("What is a full adder?", "Adds two bits with a carry-in", "Adds two nibbles", "Subtracts bits", "Multiplies bits"),
    q("How many select lines does an 8:1 MUX need?", "3", "2", "4", "8"),
    q("What is a decoder?", "Converts binary code to unique output lines", "Encodes data", "Stores data", "Multiplies signals"),
    q("Which code is self-complementing?", "BCD (8421)", "Gray code", "Excess-3", "ASCII"),
    q("What is the purpose of a counter?", "Counts clock pulses", "Stores addresses", "Decodes data", "Amplifies signals"),
    q("What is a Karnaugh map used for?", "Simplifying Boolean expressions", "Drawing circuits", "Counting bits", "Designing memory"),
    q("Which gate outputs 1 only when inputs differ?", "XOR", "AND", "OR", "NAND"),
    q("What is a shift register?", "Stores and shifts data bits", "Adds numbers", "Counts pulses", "Decodes addresses"),
    q("How many bits can a 4-bit counter count?", "16 states (0-15)", "4 states", "8 states", "32 states"),
    q("What is the binary equivalent of hexadecimal 'A'?", "1010", "1000", "1100", "1111"),
    q("Which logic family has the lowest power consumption?", "CMOS", "TTL", "ECL", "DTL"),
    q("What is a priority encoder?", "Encoder that prioritizes the highest input", "A simple encoder", "A decoder", "A multiplexer"),
    q("What is 2's complement used for?", "Representing negative numbers", "Adding positive numbers", "Multiplication", "Division"),
    q("Which flip-flop toggles on every clock pulse?", "T flip-flop", "D flip-flop", "SR flip-flop", "JK flip-flop"),
    q("What is a demultiplexer?", "Routes one input to multiple outputs", "Combines multiple inputs", "Stores data", "Adds numbers"),
    q("What is the Gray code advantage?", "Only one bit changes between successive values", "Easier to add", "More compact", "Faster to process"),
    q("What is a ROM?", "Read-Only Memory", "Random Output Memory", "Reduced Operation Module", "Read-Once Memory"),
    q("How many gates are needed for a half adder?", "XOR and AND", "OR and NOT", "NAND and NOR", "Only XOR"),
    q("What is propagation delay?", "Time for signal to pass through a gate", "Clock frequency", "Power consumption", "Noise margin"),
    q("Which counter counts in reverse?", "Down counter", "Up counter", "Ring counter", "Johnson counter"),
    q("What is a PLA?", "Programmable Logic Array", "Primary Logic Architecture", "Programmable Line Adapter", "Parallel Logic Array"),
    q("What is fan-out?", "Number of inputs a gate output can drive", "Number of gates", "Power rating", "Speed of gate"),
    q("What is the output of NOR gate when both inputs are 0?", "1", "0", "Undefined", "High impedance"),
    q("Which memory is volatile?", "RAM", "ROM", "PROM", "EPROM"),
    q("What is a ring counter?", "Shift register with feedback from output to input", "A counter that counts in binary", "An up-down counter", "A modulo counter"),
    q("What is the difference between combinational and sequential circuits?", "Sequential has memory, combinational does not", "They are the same", "Combinational has memory", "Sequential is faster"),
    q("What is a Johnson counter?", "A twisted ring counter", "A binary counter", "A decade counter", "An up counter"),
    q("What is the purpose of a clock signal?", "Synchronizes circuit operations", "Powers the circuit", "Stores data", "Amplifies signals"),
  ],
  "Analog Electronics": [
    q("What is Ohm's Law?", "V = IR", "V = I/R", "V = I+R", "V = I-R"),
    q("What type of device is a diode?", "Two-terminal semiconductor", "Three-terminal resistor", "Four-terminal capacitor", "Single-terminal inductor"),
    q("What does an op-amp amplify?", "Difference between inputs", "Sum of inputs", "Product of inputs", "Only positive input"),
    q("What is the unit of capacitance?", "Farad", "Henry", "Ohm", "Watt"),
    q("What is the forward voltage of a silicon diode?", "0.7V", "0.3V", "1.2V", "5V"),
    q("What type of transistor has three terminals: B, C, E?", "BJT", "MOSFET", "JFET", "SCR"),
    q("What does a capacitor store?", "Electric charge", "Magnetic field", "Current", "Resistance"),
    q("Which filter passes low frequencies?", "Low-pass filter", "High-pass filter", "Band-pass filter", "Notch filter"),
    q("What is the unit of inductance?", "Henry", "Farad", "Ohm", "Watt"),
    q("In a common emitter config, where is the output taken?", "Collector", "Base", "Emitter", "Gate"),
    q("What is the cutoff frequency of a filter?", "Frequency at which output is -3dB", "Maximum frequency", "Zero frequency", "Resonant frequency"),
    q("What is the gain of an inverting amplifier with Rf=10k and Rin=1k?", "-10", "10", "-1", "100"),
    q("What does a Zener diode do in reverse bias?", "Maintains constant voltage", "Blocks all current", "Acts as a switch", "Amplifies signal"),
    q("What is the purpose of a voltage divider?", "Produces a fraction of input voltage", "Amplifies voltage", "Stores charge", "Filters noise"),
    q("Which transistor configuration has highest voltage gain?", "Common emitter", "Common base", "Common collector", "Common drain"),
    q("What is the bandwidth of an amplifier?", "Range of frequencies it amplifies", "Maximum gain", "Input impedance", "Output power"),
    q("What is a rectifier used for?", "Converting AC to DC", "Converting DC to AC", "Amplifying signals", "Filtering noise"),
    q("What is the ideal input impedance of an op-amp?", "Infinite", "Zero", "1 kΩ", "50 Ω"),
    q("What is the purpose of negative feedback?", "Stabilizes gain and reduces distortion", "Increases gain", "Creates oscillation", "Amplifies noise"),
    q("What is a Schmitt trigger?", "A comparator with hysteresis", "A type of oscillator", "An amplifier", "A filter"),
    q("What is the Q factor of a circuit?", "Measure of selectivity/sharpness of resonance", "Quality of components", "Current flow", "Power factor"),
    q("What does a transformer do?", "Changes voltage levels using electromagnetic induction", "Stores energy", "Rectifies AC", "Generates DC"),
    q("What is the difference between NPN and PNP transistors?", "Current flow direction is reversed", "They are identical", "NPN is faster", "PNP has higher gain"),
    q("What is an oscillator?", "Circuit that generates periodic signals", "An amplifier", "A rectifier", "A filter"),
    q("What is the purpose of a coupling capacitor?", "Blocks DC and passes AC", "Blocks AC and passes DC", "Stores energy", "Amplifies signal"),
    q("What is thermal runaway in transistors?", "Uncontrolled increase in current due to heat", "Cooling effect", "Stable operation", "Low power mode"),
    q("What is the unity gain bandwidth of an op-amp?", "Frequency at which gain equals 1", "Maximum frequency", "DC gain", "Minimum bandwidth"),
    q("What is a voltage regulator?", "Maintains constant output voltage", "Amplifies voltage", "Converts AC to DC", "Stores charge"),
    q("What is the knee voltage of a diode?", "Voltage at which diode begins conducting significantly", "Maximum voltage", "Breakdown voltage", "Zero voltage"),
    q("What is CMRR in op-amps?", "Common Mode Rejection Ratio", "Current Mode Resistance Ratio", "Capacitor Mode Response Rate", "Common Measure of Resistance"),
    q("What is a bridge rectifier?", "Four diodes converting full-wave AC to DC", "Two diodes for half-wave", "A transformer type", "An oscillator"),
    q("What is the purpose of a bypass capacitor?", "Filters high-frequency noise to ground", "Amplifies signals", "Blocks DC", "Stores energy permanently"),
    q("What is class A amplifier?", "Conducts for full 360° of input cycle", "Conducts for 180°", "Conducts for less than 180°", "Digital amplifier"),
    q("What is the slew rate of an op-amp?", "Maximum rate of output voltage change", "Input impedance", "Gain bandwidth", "Offset voltage"),
    q("What is a Darlington pair?", "Two transistors for high current gain", "Two diodes in series", "Two resistors in parallel", "Two capacitors in series"),
    q("What is the purpose of biasing a transistor?", "Setting the DC operating point", "Amplifying signal", "Filtering noise", "Generating oscillation"),
    q("What is the forward voltage of a germanium diode?", "0.3V", "0.7V", "1.2V", "5V"),
    q("What is clipping in amplifiers?", "Distortion when output exceeds supply voltage", "Noise reduction", "Signal filtering", "Gain increase"),
    q("What is the difference between series and parallel resonance?", "Series has minimum impedance, parallel has maximum", "They are the same", "Series has maximum impedance", "Parallel has minimum impedance"),
    q("What is a Colpitts oscillator?", "LC oscillator using capacitive voltage divider", "RC oscillator", "Crystal oscillator", "Relaxation oscillator"),
  ],
  "Embedded Systems": [
    q("What is a microcontroller?", "CPU with integrated memory and I/O", "A type of hard drive", "External memory chip", "Display controller"),
    q("What does GPIO stand for?", "General Purpose Input/Output", "Global Programmable I/O", "Generic Port Interface Operation", "Ground Power Input/Output"),
    q("Which protocol uses SDA and SCL lines?", "I2C", "SPI", "UART", "CAN"),
    q("What is an interrupt?", "Signal to stop current execution", "Power failure", "Memory leak", "Clock signal"),
    q("What does RTOS stand for?", "Real-Time Operating System", "Rapid Task Operation System", "Remote Terminal Operating System", "Reduced Time OS"),
    q("Which memory is non-volatile?", "Flash", "RAM", "Cache", "Register"),
    q("What is PWM used for?", "Controlling analog output", "Reading sensors", "Memory management", "Network communication"),
    q("What does ADC convert?", "Analog to Digital", "Digital to Analog", "AC to DC", "Data to Code"),
    q("Which architecture separates code and data memory?", "Harvard", "Von Neumann", "RISC", "CISC"),
    q("What is a watchdog timer?", "Resets system on hang", "Measures temperature", "Counts interrupts", "Manages power"),
    q("What does UART stand for?", "Universal Asynchronous Receiver Transmitter", "Unified Access Resource Terminal", "Universal Address Register Transfer", "Unified Asynchronous Relay Transmitter"),
    q("What is DMA?", "Direct Memory Access", "Dynamic Memory Allocation", "Data Management Architecture", "Digital Memory Adapter"),
    q("Which SPI line carries data from master to slave?", "MOSI", "MISO", "SCLK", "SS"),
    q("What is a bootloader?", "Program that loads the main firmware", "A debugging tool", "A memory manager", "An operating system"),
    q("What is the purpose of a pull-up resistor?", "Ensures a known high state when input is floating", "Increases current", "Reduces voltage", "Filters noise"),
    q("What is bare-metal programming?", "Programming without an OS", "Programming with RTOS", "Web programming", "Database programming"),
    q("What does DAC convert?", "Digital to Analog", "Analog to Digital", "Data to Code", "AC to DC"),
    q("What is a bus in embedded systems?", "Communication pathway between components", "A power source", "A type of memory", "A processor core"),
    q("What is the purpose of a crystal oscillator?", "Provides precise clock frequency", "Stores data", "Amplifies signals", "Converts power"),
    q("What is ISR?", "Interrupt Service Routine", "Internal System Register", "Input Signal Reader", "Integrated Serial Receiver"),
    q("What is memory-mapped I/O?", "I/O devices share address space with memory", "Separate I/O address space", "Virtual memory for I/O", "Cached I/O"),
    q("What is a timer/counter in a microcontroller?", "Peripheral that counts clock cycles or external events", "A type of memory", "An I/O port", "A communication protocol"),
    q("What is the CAN protocol used for?", "Automotive and industrial communication", "Internet browsing", "Wireless communication", "Memory management"),
    q("What is firmware?", "Software permanently stored in hardware", "Hardware components", "Temporary files", "Operating system kernel"),
    q("What is a semaphore in RTOS?", "Synchronization mechanism for shared resources", "A type of interrupt", "A memory allocation method", "A communication protocol"),
    q("What is the stack in a microcontroller?", "LIFO data structure for function calls and local data", "A type of register", "An I/O port", "A communication bus"),
    q("What is power gating?", "Shutting off power to unused circuit blocks", "Increasing power supply", "Voltage regulation", "Current limiting"),
    q("What is an embedded Linux system?", "Linux OS tailored for embedded devices", "A desktop Linux", "A server OS", "A mobile OS"),
    q("What is JTAG used for?", "Debugging and testing embedded systems", "Network communication", "Power management", "Audio processing"),
    q("What is the difference between RISC and CISC?", "RISC uses simpler instructions, CISC uses complex ones", "They are the same", "RISC is slower", "CISC uses fewer instructions"),
    q("What is a mutex?", "Mutual exclusion lock for resource access", "A type of timer", "A memory type", "A bus protocol"),
    q("What is brownout detection?", "Detecting supply voltage drops below threshold", "Detecting overheating", "Detecting memory errors", "Detecting clock failure"),
    q("What is bit-banging?", "Software-emulated communication protocol", "Hardware acceleration", "Memory optimization", "Power management"),
    q("What is a task in RTOS?", "An independent thread of execution", "A hardware interrupt", "A memory block", "A communication channel"),
    q("What is the purpose of a linker script?", "Defines memory layout for the program", "Compiles source code", "Debugs programs", "Manages power"),
    q("What does SoC stand for?", "System on Chip", "Speed of Clock", "Serial over Cable", "Standard of Communication"),
    q("What is edge-triggered vs level-triggered interrupt?", "Edge detects transitions, level detects steady state", "They are the same", "Level detects transitions", "Edge detects steady state"),
    q("What is a HAL?", "Hardware Abstraction Layer", "High Access Library", "Hardware Application Logic", "Host Adapter Layer"),
    q("What is the purpose of a decoupling capacitor?", "Reduces power supply noise near IC pins", "Stores data", "Amplifies signals", "Creates clock signals"),
    q("What is an FPGA?", "Field Programmable Gate Array", "Fixed Program Gate Architecture", "Fast Processing General Adapter", "Flexible Port General Access"),
  ],
};
