import { type SampleQuestion } from "./sample-questions";

const q = (question_text: string, correct: string, wrong1: string, wrong2: string, wrong3: string): SampleQuestion => ({
  question_text,
  options: [
    { text: correct, is_correct: true },
    { text: wrong1, is_correct: false },
    { text: wrong2, is_correct: false },
    { text: wrong3, is_correct: false },
  ].sort(() => Math.random() - 0.5),
  marks: 1,
});

// HTML - Level 2 (Intermediate)
export const htmlL2: SampleQuestion[] = [
  q("Which attribute is used to group associated form elements?", "<fieldset>", "<optgroup>", "<colgroup>", "<div>"),
  q("What does the 'controls' attribute do in the <video> tag?", "Displays play/pause, volume, etc.", "Starts the video automatically", "Repeat the video", "Mute the video"),
  q("Which tag is used to specify a side-note or sidebar?", "<aside>", "<section>", "<article>", "<div>"),
  q("How do you specify a multi-line text input?", "<textarea>", "<input type='text'>", "<text>", "<p>"),
  q("What is the purpose of the <label> tag's 'for' attribute?", "Binds it to an element ID", "Specifies the label name", "Sets the font size", "Defines the link"),
  q("Which tag is used for drawing graphics via scripting?", "<canvas>", "<svg>", "<graphics>", "<img>"),
  q("Which HTML5 attribute ensures a field is filled before submission?", "required", "mandatory", "validate", "check"),
  q("What does the <meter> element represent?", "A scalar measurement within a known range", "The current time", "A progress bar", "A temperature reading"),
  q("Which attribute allows an element to be draggable?", "draggable", "drag", "allow-drag", "move"),
  q("What is the use of the <figure> element?", "To encapsulate media and its caption", "To draw geometric shapes", "To format numbers", "To create a mathematical block"),
  q("Which tag defines a summary or heading for the <details> element?", "<summary>", "<header>", "<title>", "<caption>"),
  q("What is the purpose of the <datalist> tag?", "Provides auto-complete options for inputs", "Stores large data sets", "Displays a table", "Creates a dropdown"),
  q("Which attribute defines the legal number intervals for an input?", "step", "range", "interval", "scale"),
  q("What does the <time> element's 'datetime' attribute provide?", "Machine-readable date/time format", "The visible text", "The time zone", "A countdown"),
  q("Which element is used to represent the result of a calculation?", "<output>", "<result>", "<calc>", "<data>"),
  q("Which attribute specifies that an input should automatically get focus?", "autofocus", "focus", "start-focus", "select"),
  q("What is the purpose of the <wbr> tag?", "Word break opportunity", "Web browser link", "White space reset", "Window break"),
  q("Which tag provides a way to specify multiple media sources?", "<source>", "<media>", "<link>", "<src>"),
  q("What does the <address> element usually represent?", "Contact information for the author/owner", "A physical street address only", "A URL", "A server IP"),
  q("Which attribute in the <video> tag prevents downloading?", "None (standard HTML cannot prevent it)", "nodownload", "secure", "private"),
  q("Which tag is used to highlight text?", "<mark>", "<highlight>", "<color>", "<b>"),
  q("What is the purpose of the <main> tag?", "Specifies the dominant content of the document", "Wraps the navigation", "Includes the footer", "Holds all metadata"),
  q("Which attribute in an <img> tag improves loading speed?", "loading='lazy'", "fast='true'", "defer", "async"),
  q("What does the <cite> tag define?", "The title of a creative work", "A reference link", "The author's name", "A blockquote"),
  q("Which input type is specifically for email validation?", "email", "text", "url", "validate"),
  q("What is the default value of the 'target' attribute in <a>?", "_self", "_blank", "_parent", "_top"),
  q("Which tag defines a keyboard input?", "<kbd>", "<key>", "<code>", "<input>"),
  q("What is the purpose of the <rp> tag?", "Provides fallback for browsers not supporting ruby annotations", "Repeats a paragraph", "Registers a plugin", "Reset pattern"),
  q("Which attribute allows multiple file selections in an input?", "multiple", "multi", "allow-many", "files"),
  q("What does 'rel=noopener' do in a link?", "Prevents the new page from accessing window.opener", "Makes the link faster", "Opens in a popup", "Allows tracking")
];

// HTML - Level 3 (Advanced)
export const htmlL3: SampleQuestion[] = [
  q("What is the difference between 'async' and 'defer' script attributes?", "defer executes after parsing is complete", "async is for CSS", "defer is faster", "They are identical"),
  q("Which attribute provides custom data that can be accessed via JavaScript?", "data-*", "custom-*", "js-*", "extra-*"),
  q("What is the 'Shadow DOM'?", "A way to encapsulate parts of a web page", "A backup of the DOM", "A hidden frame", "A dark mode feature"),
  q("Which API is used to store data locally in the browser with no expiration?", "localStorage", "sessionStorage", "cookies", "flash"),
  q("What is the purpose of the 'nonce' attribute?", "Security - allows specific trusted scripts (CSP)", "Sets the number of executions", "Defines a unique ID", "Randomizes the layout"),
  q("Which element is used for 'Microdata' scope definition?", "itemscope", "datascoped", "schema", "micro"),
  q("What does the 'integrity' attribute do in a <script> tag?", "Allows Subresource Integrity (SRI) checking", "Validates the code logic", "Minifies the script", "Compresses the file"),
  q("Which tag allows high-quality graphics and is resolution-independent?", "<svg>", "<canvas>", "<img>", "<bitmap>"),
  q("What is the purpose of the <noscript> tag?", "Displays content for users with JavaScript disabled", "Stops JS execution", "Debugs the code", "Creates a server script"),
  q("Which attribute in <link> specifies a site's relationship to an icon?", "rel='icon'", "type='image'", "href='favicon'", "media='screen'"),
  q("What is 'Web Component' technology based on?", "Custom elements, Shadow DOM, and HTML templates", "React and Vue", "JSON and AJAX", "XML and SOAP"),
  q("Which attribute defines the allowed characters in an input using regex?", "pattern", "regex", "validate", "check"),
  q("What does the 'contenteditable' attribute allow?", "Enables users to edit element content", "Allows code editing only", "Makes text readable only", "Secures the content"),
  q("Which tag is typically used for mathematical formulas in HTML?", "<math>", "<formula>", "<calc>", "<equation>"),
  q("What is the purpose of the 'sandbox' attribute in an <iframe>?", "Enables security restrictions", "Creates a playground", "Slows down the loading", "Allows all scripts"),
  q("Which element defines the base URL for all relative URLs in a document?", "<base>", "<url>", "<root>", "<link>"),
  q("What is the 'prefetch' link relation used for?", "Tells the browser to fetch a resource for future use", "Downloads everything immediately", "Caches only images", "Clears the cache"),
  q("Which attribute specifies a keyboard shortcut to activate an element?", "accesskey", "shortcut", "key", "hotkey"),
  q("What is the use of the 'crossorigin' attribute?", "Handles CORS requests for modules/scripts", "Links to other websites", "Prevents tracking", "Enables HTTPS"),
  q("Which tag defines a set of option groups in a select list?", "<optgroup>", "<colgroup>", "<group>", "<options>"),
  q("What is the purpose of the 'spellcheck' attribute?", "Enables/disables grammar and spelling check", "Translates the text", "Checks for code errors", "Dictionary search"),
  q("Which attribute defines the character encoding of an external script?", "charset", "encoding", "type", "lang"),
  q("What does the 'translate' attribute do?", "Specifies whether content should be translated", "Changes the language", "Moves elements on screen", "Converts units"),
  q("Which element represents a range of time or date?", "<time>", "<date>", "<span class='time'>", "<clock>"),
  q("What is the purpose of the 'tabindex' attribute?", "Controls the order of element focus via keyboard", "Creates a table", "Sets numerical indices", "Links to tabs"),
  q("Which tag represents an abbreviation or acronym?", "<abbr>", "<acr>", "<span>", "<summary>"),
  q("What is the significance of the 'download' attribute in <a>?", "Prompts the user to save the linked file", "Downloads the website source", "Opens a PDF reader", "Saves a copy in history"),
  q("Which attribute defines a human-readable title for a track?", "label", "title", "text", "description"),
  q("What does the 'poster' attribute in <video> do?", "Displays an image before the video plays", "Sets the video profile", "Defines the creator", "Shows credits at the end"),
  q("Which element represents a generic vertical or horizontal container?", "<div>", "<span>", "<container>", "<block>")
];

// CSS - Level 2 (Intermediate)
export const cssL2: SampleQuestion[] = [
  q("How do you select the third child of an element?", ":nth-child(3)", ":child(3)", ":nth-of-type(3)", ":index(3)"),
  q("Which property is used for creating space between grid items?", "gap", "grid-spacing", "cell-margin", "white-space"),
  q("What does 'box-sizing: border-box' include in the width?", "Padding and border", "Only content", "Margin and padding", "Padding and margin"),
  q("Which flexbox property aligns items horizontally?", "justify-content", "align-items", "flex-direction", "horizontal-align"),
  q("What is the 'rem' unit based on?", "Root element font size", "Parent font size", "Viewport width", "Screen resolution"),
  q("Which selector targets an element that is being hovered?", ":hover", ":active", ":focus", ":select"),
  q("How do you apply a style to all elements?", "*", "all", "every", "html"),
  q("What does 'overflow: hidden' do?", "Hides content that exceeds element bounds", "Removes the element", "Makes element transparent", "Stops scrolling only"),
  q("Which property sets the transparency of an element?", "opacity", "transparent", "alpha", "filter"),
  q("What is a CSS 'media query' used for?", "Responsive web design", "Playing audio files", "Querying a database", "Calculating values"),
  q("Which property specifies the order of flex items?", "order", "flex-order", "index", "z-index"),
  q("How do you make a transition smooth?", "transition", "transform", "animate", "speed"),
  q("Which property controls the space between letters?", "letter-spacing", "word-spacing", "kerning", "line-height"),
  q("What does 'position: relative' do?", "Offset relative to its normal position", "Fixed to the screen", "Removed from document flow", "Sticks to parent top"),
  q("Which property adds a shadow to an element?", "box-shadow", "drop-shadow", "shadow", "element-shadow"),
  q("What is the 'vh' unit?", "1% of viewport height", "1% of vertical header", "10 pixels", "Vertical height"),
  q("Which display value makes an element act like a block but allows side elements?", "inline-block", "block", "inline", "flex"),
  q("How do you select only paragraphs directly inside a div?", "div > p", "div p", "div+p", "div.p"),
  q("What does 'z-index' define?", "The stack level of an element", "The zoom level", "The rotation", "The width"),
  q("Which property defines the font of an element?", "font-family", "font-style", "text-font", "typeface"),
  q("How do you center an element using Flexbox?", "justify-content: center; align-items: center;", "text-align: center;", "margin: auto;", "float: center;"),
  q("What is a 'pseudo-element'?", "Keywords used to style specific parts of an element", "A temporary class", "A JavaScript object", "A fake element name"),
  q("Which property sets the maximum width of an element?", "max-width", "width-limit", "limit-width", "upper-width"),
  q("What does 'visibility: hidden' do differently than 'display: none'?", "Leaves the space occupied", "Removes from layout", "Makes it solid grey", "Nothing (they are same)"),
  q("Which property creates a multi-column layout?", "column-count", "columns", "split", "grid"),
  q("How do you change the mouse cursor on hover?", "cursor: pointer;", "mouse: select;", "pointer: hover;", "icon: arrow;"),
  q("What does 'float: left' remove an element from?", "The normal document flow", "The DOM tree", "The CSS rules", "The parent container"),
  q("Which property scales an element?", "transform: scale()", "size: plus()", "resize: true", "zoom"),
  q("What is the 'em' unit relative to?", "Font size of the parent", "Root font size", "Screen width", "Element ID count"),
  q("Which property targets the background of an element?", "background", "bg", "content-bg", "color")
];

// CSS - Level 3 (Advanced)
export const cssL3: SampleQuestion[] = [
  q("What is the CSS specificity of an ID selector?", "100", "10", "1", "1000"),
  q("Which function is used to set a value between a min and max with an ideal size?", "clamp()", "minmax()", "limit()", "range()"),
  q("What do CSS 'Variables' start with?", "--", "$", "@", "var-"),
  q("What is 'CSS Grid Placement' using areas?", "grid-template-areas", "grid-layout", "grid-regions", "grid-map"),
  q("Which property allows you to change the rendering of borders/padding?", "box-sizing", "border-mode", "box-type", "layout-logic"),
  q("What is 'Specificity' score for '.class #id p'?", "111", "21", "110", "011"),
  q("Which pseudo-class targets an element if it has no children?", ":empty", ":null", ":none", ":void"),
  q("What is 'will-change' used for?", "GPU acceleration and optimization", "Animating every property", "Preventing changes", "Loading external files"),
  q("Which property handles hyphenation at line breaks?", "hyphens", "word-break", "text-align", "wrap"),
  q("What does 'scroll-behavior: smooth' do?", "Enables smooth scrolling within the container", "Makes animations slow", "Scrolls automatically", "Resets scroll position"),
  q("How do you detect users with 'Dark Mode' enabled in CSS?", "media (prefers-color-scheme: dark)", "html.dark", "mode: dark", "browser.dark"),
  q("What is 'Attribute Selector' syntax?", "[attribute='value']", ".attribute='value'", "@attribute", "#attribute"),
  q("Which property specifies how images/videos fit their container?", "object-fit", "content-fill", "media-layout", "img-mode"),
  q("What is the 'order' property used for in Flexbox?", "Changing the visual order of items", "Sorting elements alphabetically", "Setting priorities for load", "Filtering elements"),
  q("Which pseudo-class selects elements that are enabled?", ":enabled", ":active", ":start", ":on"),
  q("What does 'pointer-events: none' do?", "Element ignores mouse events and clicks pass through", "Disables the mouse", "Makes text unselectable", "Hides the cursor"),
  q("How do you target a specific range of viewport width?", "@media (min-width: X) and (max-width: Y)", "@responsive X to Y", "@viewport X Y", "screen: X-Y"),
  q("What is 'CSS Containment' (contain property)?", "Enables optimization by isolating subtrees", "Wraps elements in a border", "Stops scripts", "Limits width"),
  q("Which function performs a calculation with multiple units?", "calc()", "sum()", "math()", "unit()"),
  q("What is 'CSS Scoping'?", "Limiting styles to a specific part of the page", "Finding elements", "Measuring distance", "Zooming in"),
  q("Which property defines the flow of text around floating elements?", "clear", "float-clear", "reset", "break"),
  q("What is 'Flex-basis'?", "The initial size of a flex item", "The maximum size", "The background color", "The alignment type"),
  q("Which selector targets every 2nd element starting from the 1st?", ":nth-child(2n+1)", ":nth-child(2)", ":even", ":odd"),
  q("What is 'aspect-ratio' property?", "Sets a preferred aspect ratio for an element", "Resizes images", "Sets movie dimensions", "Changes screen size"),
  q("Which property allows text to be clipped with an ellipsis?", "text-overflow: ellipsis", "overflow: dot", "text-clip", "line-limit"),
  q("What is 'CSS Filter' used for?", "Visual effects like blur, brightness, contrast", "Filtering database results", "Cleaning code", "Removing spam"),
  q("Which pseudo-class targets the root of the document?", ":root", ":html", ":all", ":base"),
  q("What is 'Subgrid' in CSS Grid?", "Allows nested grids to use parent's columns/rows", "A small grid", "A second grid", "A grid inside a table"),
  q("Which property sets the background attachment (scroll or fixed)?", "background-attachment", "bg-scroll", "background-fixed", "scroll-parallax"),
  q("What does 'all: unset' do?", "Resets all properties to their initial/inherited values", "Deletes the element", "Hides the element", "Makes it transparent")
];

// DBMS - Level 2 (Intermediate)
export const dbmsL2: SampleQuestion[] = [
  q("What is the main goal of Normalization?", "Reduce data redundancy and dependency", "Increase the number of tables", "Simplify queries", "Encrypt data"),
  q("Which normal form handles transitive dependencies?", "3NF", "2NF", "BCNF", "4NF"),
  q("What is a 'Primary Key' requirement?", "Must be unique and not null", "Can have duplicates", "Can be null", "Must be a string"),
  q("What is the purpose of a 'Foreign Key'?", "Enforce referential integrity", "Ensure uniqueness in the same table", "Encrypt the database", "Speed up writing"),
  q("Which JOIN returns only matching records from both tables?", "INNER JOIN", "OUTER JOIN", "CROSS JOIN", "SELF JOIN"),
  q("What does a 'Transaction' need to be?", "Atomic, Consistent, Isolated, Durable", "Rapid, Scalable, Secure", "Shared and Open", "Distributed"),
  q("Which command is used to undo changes in a transaction?", "ROLLBACK", "RESET", "UNDO", "DELETE"),
  q("What is 'Indexing' used for?", "Improving data retrieval speed", "Securing the data", "Reducing database size", "Connecting to the server"),
  q("Which clause is used for grouping results?", "GROUP BY", "ORGANIZE BY", "COLLECT", "JOIN"),
  q("What is 'Referential Integrity'?", "Ensuring every foreign key refers to a valid primary key", "Protecting against hackers", "Checking for syntax errors", "Backup management"),
  q("Which SQL property prevents dirty reads?", "Isolation", "Atomicity", "Durability", "Consistency"),
  q("What is a 'Composite Key'?", "A key made of two or more columns", "A key that is also a foreign key", "A randomized ID", "A string-based key"),
  q("Which function is used to calculate the average value?", "AVG()", "MEAN()", "SUM()/COUNT()", "MID()"),
  q("What does the 'DISTINCT' keyword do?", "Removes duplicate rows from the results", "Sorts the results", "Hides table names", "Ensures all columns are unique"),
  q("What is 'BCNF'?", "Boyce-Codd Normal Form - stricter version of 3NF", "Basic Code Normal Form", "Binary Coded Normal Flow", "Backup Coverage and Node Filter"),
  q("Which command modifies the structure of a table?", "ALTER", "UPDATE", "CHANGE", "MODIFY"),
  q("What is a 'Stored Procedure'?", "Prepared SQL code that can be reused", "A physical backup file", "A type of trigger", "A system log"),
  q("Which operator is used to check for a range of values?", "BETWEEN", "RANGE", "IN", "SEARCH"),
  q("What is a 'Trigger'?", "A procedure that runs automatically on events", "A manual backup button", "A slow query", "A database engine"),
  q("What is the difference between TRUNCATE and DELETE?", "TRUNCATE reset identity/structure, DELETE is record by record", "No difference", "DELETE is faster", "TRUNCATE needs a WHERE clause"),
  q("Which integrity constraint ensures no two rows have the same value?", "UNIQUE", "NOT NULL", "CHECK", "DEFAULT"),
  q("What is a 'View' useful for?", "Abstracting complex queries and security", "Storing physical data", "Speeding up writes", "Creating backups"),
  q("Which command gives permissions to a user?", "GRANT", "ALLOW", "GIVE", "PERMIT"),
  q("What does 'Commit' do?", "Saves transaction changes permanently", "Starts a transaction", "Deletes a transaction", "Closes the database"),
  q("What is 'Cardinality' in DBMS?", "Number of unique values or rows", "The speed of the engine", "The type of data", "The database size"),
  q("Which SQL operator checks for a pattern?", "LIKE", "MATCH", "FIND", "SEARCH"),
  q("What is 'Self JOIN'?", "Joining a table with itself", "Joining two same-structured tables", "A join with no conditions", "A recursive join"),
  q("What is 'Denormalization'?", "Adding redundant data for performance", "Removing all keys", "Dropping tables", "Scaling to one table"),
  q("Which level of database abstraction is closest to the users?", "External level", "Conceptual level", "Physical level", "Internal level"),
  q("What is a 'Data Dictionary'?", "Metadata about the database structure", "A dictionary of common terms", "A backup system", "A list of users")
];

// DBMS - Level 3 (Advanced)
export const dbmsL3: SampleQuestion[] = [
  q("What is 'Sharding'?", "Horizontal partitioning of a database", "Vertical scaling of RAM", "Clustering of servers", "Encrypting segments"),
  q("Which locking level provides the highest concurrency?", "Row-level locking", "Table-level locking", "Database-level locking", "Page-level locking"),
  q("What is 'MVCC'?", "Multi-Version Concurrency Control", "Modern Video Codec Control", "Massive Value Cluster Connection", "Manual View Consistency Check"),
  q("What does 'WAL' stand for in database systems?", "Write-Ahead Logging", "Web Access Layer", "Wide Area Link", "Wait and Log"),
  q("Which join is most efficient if both tables are sorted by join key?", "Merge Join", "Hash Join", "Nested Loop Join", "Loop Join"),
  q("What is 'Checkpoint' in recovery?", "Point where memory is flushed to disk", "Point where user saves code", "Point where error occurs", "Point where backup starts"),
  q("What is a 'Sparse Index'?", "Index with entries for only some values", "A thin index", "A large index", "A binary search index"),
  q("What is the purpose of 'Materialized Views'?", "Store query results physically for performance", "Create virtual tables", "Hide complexity only", "Manage permissions"),
  q("What is 'Query Optimization'?", "Finding the best execution plan for a query", "Writing SQL faster", "Adding more indexes", "Deleting old data"),
  q("Which isolation level is the strictest?", "Serializable", "Repeatable Read", "Read Committed", "Read Uncommitted"),
  q("What is 'CAP theorem'?", "Consistency, Availability, Partition tolerance", "Cloud, API, Platform", "Capacity, Access, Performance", "Code, App, Process"),
  q("Which NoSQL type is MongoDB?", "Document-oriented", "Key-Value", "Wide-column", "Graph"),
  q("What is 'Hashed Index'?", "Used for equality comparisons via hash functions", "A generic index", "A sorted index", "A primary key index"),
  q("What is the purpose of 'RAID' in databases?", "Data redundancy and improved I/O", "Faster SQL parsing", "Memory management", "Network security"),
  q("What is 'Logical Decoding'?", "Extracting persistent changes from a WAL", "Decoding passwords", "Query parsing", "System log reading"),
  q("Which join is usually best for small tables or when one table is very large?", "Nested Loop Join", "Hash Join", "Merge Join", "Cross Join"),
  q("What is 'Bitmap Indexing'?", "Uses bit arrays for low cardinality columns", "Index for images", "Index for binary files", "A type of tree index"),
  q("What is 'Deadlock' resolution?", "Aborting one transaction to break the loop", "Restarting the computer", "Deleting the wait queue", "Ignoring the error"),
  q("Which property ensures that a transaction stays committed even after power failure?", "Durability", "Atomicity", "Isolation", "Consistency"),
  q("What is 'Foreign Data Wrapper' (FDW)?", "Connects to external databases as tables", "A type of security wrapper", "A network tool", "A database driver"),
  q("What is the difference between 'Vertical and Horizontal' scaling?", "Vertical adds RAM/CPU, Horizontal adds servers", "They are same", "Horizontal is faster", "Vertical is cheaper"),
  q("What is 'Query Parallelism'?", "Executing a single query across multiple cores", "Running multiple queries", "Fast indexing", "Database backup"),
  q("Which constraint is used to ensure a condition on a column?", "CHECK", "VALIDATE", "ASSERT", "WHERE"),
  q("What is 'Write Amplification' in SSD databases?", "Writing more physical data than logical data", "Increasing log size", "Adding more tables", "A type of error"),
  q("What is 'Point-In-Time Recovery' (PITR)?", "Restoring to a specific timestamp/WAL location", "Restoring from first backup", "Manual data entry", "Database scaling"),
  q("What is 'Full Text Search' index?", "Enables searching for words in huge text chunks efficiently", "Searching for single characters", "A fast select", "A type of primary key"),
  q("What is 'Conflict Resolution' in distributed databases?", "Strategy to merge divergent data (e.g., LWW)", "Ending the connection", "Deleting one database", "Throwing errors"),
  q("What is 'OLAP'?", "Online Analytical Processing (for BI and reports)", "Online Asset Program", "Offline Archive Protocol", "Operating Level App Process"),
  q("What is 'Cursor' in depth?", "A handle to navigate a result set row by row", "A mouse pointer", "A type of index", "A table name"),
  q("Which command displays the plan of a query execution?", "EXPLAIN", "SHOW", "PLAN", "GET")
];

// C - Level 2 (Intermediate)
export const cL2: SampleQuestion[] = [
  q("What is the purpose of a 'Pointer'?", "To store the memory address of another variable", "To store numbers", "To create a function", "To links files"),
  q("Which operator is used for access via a structure pointer?", "->", ".", "::", "*"),
  q("How do you pre-allocate memory dynamically?", "malloc()", "new()", "alloc()", "set()"),
  q("What is the difference between 'struct' and 'union'?", "Union members share the same memory", "Struct uses less memory", "Union is for functions", "They are identical"),
  q("What does the 'static' keyword do to a global variable?", "Limits its scope to the current file", "Makes it accessible everywhere", "Deletes it after use", "Makes it constant"),
  q("Which function is used to free dynamic memory?", "free()", "delete()", "clear()", "remove()"),
  q("What is a 'Macro' in C?", "Predefined code fragment for text substitution", "A small function", "A type of variable", "A loop type"),
  q("What is the output of 'sizeof(char)'?", "1 byte", "2 bytes", "4 bytes", "8 bytes"),
  q("Which control sequence is used for a tab?", "\\t", "\\n", "\\r", "\\b"),
  q("How do you declare a constant in C?", "const", "final", "fix", "static"),
  q("What is a 'Segmentation Fault'?", "Accessing restricted or invalid memory", "A syntax error", "A math error", "A logic error"),
  q("Which function compares two strings?", "strcmp()", "streq()", "compare()", "strcheck()"),
  q("What is the return type of a function that returns nothing?", "void", "null", "int", "empty"),
  q("How do you pass a variable by reference?", "Pass its address (&var)", "Pass its value", "Pass its name", "Pass its type"),
  q("What is a 'Pointer to a Pointer'?", "A variable that stores address of a pointer", "A doubled pointer", "A link to a file", "An array index"),
  q("Which header file is for string functions?", "string.h", "str.h", "text.h", "stdlib.h"),
  q("What does 'realloc()' do?", "Changes the size of previously allocated memory", "Re-allocates the whole program", "Resets memory to zero", "Deletes the memory"),
  q("What is an 'Enumeration' (enum)?", "A set of named integer constants", "A list of strings", "A type of loop", "A class in C"),
  q("Which loop checks the condition at the end?", "do-while", "while", "for", "foreach"),
  q("What is 'Recursion'?", "A function calling itself", "A repeating loop", "A type of variable", "Memory management"),
  q("How do you open a file for writing in C?", "fopen('file.txt', 'w')", "open('file.txt')", "write('file.txt')", "file.open('w')"),
  q("What is a 'Dangling Pointer'?", "A pointer referring to freed memory", "A null pointer", "A pointer that is too long", "An uninitialized pointer"),
  q("Which operator is used for bitwise AND?", "&", "&&", "|", "AND"),
  q("What is the value of EOF (End Of File)?", "-1 (usually)", "0", "1", "null"),
  q("What does '#include <stdio.h>' do?", "Includes standard input/output functions", "Starts the program", "Defines the screen", "Imports C++"),
  q("Which function converts a string to an integer?", "atoi()", "itoa()", "parseInt()", "strToInt()"),
  q("What is a 'Local Variable'?", "A variable declared inside a function", "A variable shared by files", "A constant", "A pointer"),
  q("Which keyword is used to skip the rest of a loop iteration?", "continue", "skip", "next", "break"),
  q("What is the size of 'int' on a 32-bit system (usually)?", "4 bytes", "2 bytes", "8 bytes", "1 byte"),
  q("Which operator dereferences a pointer?", "*", "&", "->", ".")
];

// C - Level 3 (Advanced)
export const cL3: SampleQuestion[] = [
  q("What is 'Memory Alignment'?", "Placing data at addresses that are multiples of its size", "Sorting memory", "Cleaning RAM", "Linking variables"),
  q("How do you declare a 'Function Pointer'?", "void (*ptr)(int)", "void *ptr(int)", "void ptr*(int)", "void &ptr(int)"),
  q("What is a 'Void Pointer'?", "A generic pointer that can point to any type", "A pointer to nothing", "An empty memory spot", "A pointer to a function"),
  q("What does 'volatile' keyword tell the compiler?", "Value may change unexpectedly (e.g., hardware)", "Variable is constant", "Speed up code", "Delete variable"),
  q("Which function allows reading a line of text safely (better than gets)?", "fgets()", "scanf()", "read()", "input()"),
  q("What is 'Pointer Arithmetic'?", "Adding/subtracting integers to a pointer address", "Calculating pointer speed", "Dividing pointers", "Multiplying addresses"),
  q("What is the use of 'extern' keyword?", "To declare a variable defined in another file", "To make a variable local", "To delete a variable", "To hide the variable"),
  q("What is a 'Self-Referential Structure'?", "A struct containing a pointer to its own type", "A recursive function", "A struct that refers to Main", "A type of memory"),
  q("Which memory segment stores local variables?", "Stack", "Heap", "Data Segment", "Code Segment"),
  q("Which memory segment stores 'malloc'ed memory?", "Heap", "Stack", "Data Segment", "BSS Segment"),
  q("What is 'Big Endian vs Little Endian'?", "The order of storing bytes in memory", "The size of the computer", "The type of keyboard", "Processor speed types"),
  q("What does the 'inline' hint suggest to the compiler?", "Replacement of function call with actual code", "Writing code on one line", "Faster execution of loops", "Deleting the function"),
  q("What is a 'Variable Length Array' (VLA)?", "An array whose size is determined at runtime", "A dynamic list", "A pointer to an array", "A type of malloc"),
  q("How do you access the N-th element of an array 'arr' using pointers?", "*(arr + n)", "arr + n", "&arr[n]", "*arr[n]"),
  q("What is 'Double-Free' error?", "Attempting to free the same memory twice", "Allocating memory twice", "Deleting two files", "Syntax error"),
  q("What is 'Bit Field' in C?", "Allocating specific number of bits for struct members", "A type of array", "A bitwise operation", "A network tool"),
  q("What is 'Variadic Function'?", "A function that takes a variable number of arguments (e.g., printf)", "A function that changes types", "A fast function", "A recursive function"),
  q("Which header is needed for 'va_start' and 'va_end'?", "stdarg.h", "stdlib.h", "stdio.h", "args.h"),
  q("What is 'Buffer Overflow'?", "Writing more data into a buffer than it can hold", "Streaming video", "Speeding up memory", "A type of loop"),
  q("What is the purpose of 'setjmp' and 'longjmp'?", "Non-local jumps (error handling)", "Starting the app", "Closing files", "Starting threads"),
  q("What is 'Linkage' (Internal vs External)?", "Visibility of identifiers across files", "Connecting to a URL", "Linking two variables", "Pointer to a link"),
  q("What is the 'Opaque Pointer' pattern?", "Hiding the internal details of a structure", "A null pointer", "A pointer to a file", "A hidden variable"),
  q("Which command compiles a C file using GCC?", "gcc file.c -o file", "compile file.c", "make file", "run file.c"),
  q("What is 'Padding' in structures?", "Extra bytes added to align members in memory", "Adding comments", "Clearing memory", "Creating empty arrays"),
  q("What is 'Strict Aliasing'?", "Rule that two pointers of different types can't point to same object", "A type of syntax check", "A security standard", "A pointer move"),
  q("Which function moves the file pointer to a specific location?", "fseek()", "move()", "goto()", "pointer()"),
  q("What is 'Memory Leak'?", "Forgetting to free dynamically allocated memory", "Physical damage to RAM", "Slow processor", "Stack overflow"),
  q("What is 'Call-by-Value' overhead?", "Copying large structures when passing to functions", "Naming variables long", "Using too many loops", "Calculation speed"),
  q("What is a 'Callback Function'?", "A function passed as an argument to another function", "A recursive call", "A function that returns a boolean", "A system hook"),
  q("Which operator performs a bitwise XOR?", "^", "~", "||", "!"),
];

// Digital Electronics - Level 2 (Intermediate)
export const digitalElectronicsL2: SampleQuestion[] = [
  q("What is the decimal equivalent of binary 11011?", "27", "26", "25", "28"),
  q("Which gate produces a 1 output only if its inputs are different?", "XOR", "XNOR", "AND", "OR"),
  q("How many select lines are required for a 16-to-1 multiplexer?", "4", "3", "5", "8"),
  q("What is a 'Full Adder' circuit?", "Adds three inputs (A, B, and Carry-in)", "Adds two inputs", "Subtracts two binary digits", "Multiplies binary digits"),
  q("What does a 'JK Flip-Flop' do when J=1 and K=1?", "Toggles its state", "Resets to 0", "Sets to 1", "Stays unchanged"),
  q("What is the Gray Code for decimal 4?", "0110", "0100", "0101", "0011"),
  q("How many bits are in a 16Kb memory chip?", "16,384 bits", "16,000 bits", "1,600 bits", "16,192 bits"),
  q("What is a 'Decade Counter'?", "A counter that counts from 0 to 9", "A counter with 10 flip-flops", "A counter for 10 users", "An up-down counter"),
  q("Which logic family has the highest speed but high power consumption?", "ECL (Emitter Coupled Logic)", "TTL", "CMOS", "NMOS"),
  q("What is 'Fan-out' of a logic gate?", "The number of inputs it can reliably drive", "The number of gates in a chip", "The power dissipation", "The speed of the signal"),
  q("What is the Boolean expression for an OR gate with inputs A and B?", "A + B", "A . B", "A xor B", "not(A)"),
  q("What is 'K-Map' simplification primarily used for?", "Reducing the number of gates required", "Drawing a circuit", "Testing a battery", "Calculating current"),
  q("Which flip-flop eliminates the invalid state of an SR flip-flop?", "JK Flip-Flop", "D Flip-Flop", "T Flip-Flop", "R Flip-Flop"),
  q("What is the output of XNOR when both inputs are 0?", "1", "0", "Undefined", "High impedance"),
  q("What is 'Multiplexing'?", "Selecting one of many inputs to a single output", "Sending one input to many outputs", "Multiplying two signals", "Adding binary digits"),
  q("Which code is used to represent alphanumeric characters in computers?", "ASCII", "BCD", "Gray Code", "Excess-3"),
  q("What is the resolution of an 8-bit DAC?", "256 levels", "8 levels", "64 levels", "1024 levels"),
  q("What does a 'Priority Encoder' do?", "Outputs the binary value of the highest priority active input", "Adds two binary digits", "Encodes every input equally", "Decodes binary to decimal"),
  q("Which theorem states that (A.B)' = A' + B'?", "De Morgan's Theorem", "Shannon's Theorem", "Thevenin's Theorem", "Norton's Theorem"),
  q("What is a 'LIFO' data structure used in digital systems?", "Stack", "Queue", "Matrix", "Register"),
  q("How many inputs does a half-subtractor have?", "2", "3", "4", "1"),
  q("What is 'Propagation Delay'?", "Time taken for input change to reach output", "Clock frequency", "Voltage levels", "Noise margin"),
  q("Which logic gate is equivalent to a 'Universal Gate'?", "NAND", "XOR", "OR", "XNOR"),
  q("What is a 'Synchronous' counter?", "All flip-flops are clocked simultaneously", "Each flip-flop is clocked by the previous one", "No clock is used", "A manual counter"),
  q("What is the hexadecimal equivalent of binary 1111?", "F", "15", "E", "A"),
  q("Which device is used to store data in a CPU?", "Registers (Flip-flops)", "Resistors", "Inductors", "Diodes"),
  q("What is 'CMOS' technology composed of?", "Both NMOS and PMOS transistors", "Only NMOS transistors", "Only PMOS transistors", "Bipolar transistors"),
  q("What is a 'Demultiplexer'?", "Sends one input to one of many outputs", "Combines many inputs into one", "A type of memory", "A binary adder"),
  q("What is 'Race Around Condition' in JK flip-flop?", "State changes multiple times during a single pulse", "A very fast calculation", "A loop in the logic", "A type of noise"),
  q("How many bits can a BCD digit represent?", "4 bits (0-9 range used)", "2 bits", "8 bits", "16 bits")
];

// Digital Electronics - Level 3 (Advanced)
export const digitalElectronicsL3: SampleQuestion[] = [
  q("What is 'FPGA' in digital design?", "Field Programmable Gate Array - reconfigurable hardware", "Fixed Precision Ground Architecture", "Fast Processing Ground Area", "Factorized Path Gate Adder"),
  q("What is 'Metastability' in flip-flops?", "A state where output is neither 0 nor 1 for a duration", "A very stable state", "A broken circuit", "A type of memory segment"),
  q("Which method is used to solve the 'Glitch' problem in combinational logic?", "Adding redundant terms in K-map", "Increasing the clock speed", "Removing every second gate", "Using larger transistors"),
  q("What is 'VHDL' used for?", "Hardware Description and Simulation", "Designing websites", "Writing database queries", "Managing files"),
  q("What is 'CPLD'?", "Complex Programmable Logic Device", "Cloud Programmable List Driver", "Central Processor Logic Detail", "Closed Program Logic Driver"),
  q("What is 'PLA'?", "Programmable Logic Array", "Parallel Link Adapter", "Primary Logic Adder", "Programmable Link Application"),
  q("Which state machine has outputs that depend only on current state?", "Moore Machine", "Mealy Machine", "Moore-Mealy hybrid", "Static Machine"),
  q("What is 'Setup Time Violation'?", "Data changes too close to the clock edge, leading to metastability", "Clock is too slow", "Designer is late", "A type of code error"),
  q("What is the primary benefit of 'Gray Code' in rotary encoders?", "Only one bit changes per step, preventing errors", "It's more compact", "It's faster to add", "It represents decimals directly"),
  q("What is 'Static Timing Analysis' (STA)?", "Verification technique for timing without using test vectors", "Testing the speed of a CPU", "Logging errors", "A backup system"),
  q("What is 'Quine-McCluskey' method used for?", "Algorithmic simplification of Boolean functions", "Drawing circuits", "A type of memory address", "Testing voltage"),
  q("Which circuit incorporates 'Hysteresis' to avoid noise triggers?", "Schmitt Trigger", "Half Adder", "MUX", "SR Latch"),
  q("What is 'PAL' (Programmable Array Logic)?", "Programmable AND array and fixed OR array", "Parallel Access Link", "Primary Access Log", "Programmable Analog Link"),
  q("What is 'Double-Buffering'?", "Using two buffers to hold data for processing/display", "Adding two capacitors", "Having two batteries", "A type of logic loop"),
  q("Which HDL is more popular in the industry for system-level design?", "SystemVerilog", "HTML", "VHDL", "XML"),
  q("What is 'Hamming Code'?", "A type of error-detecting and error-correcting code", "A code for images", "A type of encryption", "A specialized binary counter"),
  q("What is 'Johnson Counter' output frequency compared to clock?", "f / (2n)", "f / n", "f * n", "f / 2"),
  q("What is the purpose of 'Scan Insertion'?", "Adding test logic to every flip-flop to increase controllability", "Scanning for physical damage", "Looking for code bugs", "Managing users"),
  q("What is 'Clock Skew'?", "The difference in arrival time of the clock signal at different points", "A broken clock", "Checking the frequency", "Managing power"),
  q("What is 'LVS' (Layout Versus Schematic)?", "Matching the physical design to the original logic", "Logging voltage", "A type of security test", "A naming convention"),
  q("Which device is best for high-speed low-latency digital logic?", "ECL", "TTL", "CMOS", "RTL"),
  q("What is 'Power Gating'?", "Shutting off power to inactive blocks on a chip", "Opening a gate", "A type of error", "Scaling the wall"),
  q("Which gate corresponds to 'Modular-2 Addition'?", "XOR", "NOR", "NOT", "NAND"),
  q("What is 'Finite State Machine' (FSM)?", "A mathematical model of computation used to design logic circuits", "A robot with many states", "A type of memory address", "A security protocol"),
  q("What is 'Don't Care' condition in K-map?", "Input combinations that never occur or don't affect output", "Ignore the result", "A type of error", "A missing wire"),
  q("What is 'Critical Path'?", "The longest timing path in a digital circuit", "A dangerous wire", "A path for data only", "A designer's path"),
  q("What is 'D-type Flip-Flop' used for in registers?", "Storing binary information", "Inverting signals", "Adding two binary digits", "Generating a clock"),
  q("What is 'Pulse Triggering'?", "Changing state only during the clock pulse duration", "Sticking to the floor", "A type of error", "Stopping the timer"),
  q("What is the hexadecimal value for dec 173?", "AD", "B1", "A3", "C2"),
  q("What is 'Wait State'?", "Delaying the processor for slow memory interaction", "The end of a program", "Waiting for the user", "A power mode")
];

// Analog Electronics - Level 2 (Intermediate)
export const analogElectronicsL2: SampleQuestion[] = [
  q("What is the purpose of a 'Coupling Capacitor'?", "To pass AC while blocking DC", "To store energy", "To filter low frequencies", "To increase gain"),
  q("In an NPN transistor, the majority carriers are:", "Electrons", "Holes", "Protons", "Neutrons"),
  q("What is 'Transconductance' (gm) of a MOSFET?", "The ratio of change in drain current to change in gate-to-source voltage", "Current flow", "Voltage gain", "Resistance"),
  q("What is a 'Differential Amplifier's' CMRR?", "Common Mode Rejection Ratio", "Current Multiplier Rate", "Capacitor Mode Response", "Collective Measure"),
  q("What is the ideal gain of a non-inverting op-amp with Rf=9k and Ri=1k?", "10", "9", "1", "100"),
  q("Which filter type has a flat passband?", "Butterworth", "Chebyshev", "Bessel", "Elliptic"),
  q("What does a 'Zener Diode' do in its breakdown region?", "Maintains a constant voltage", "Blocks all current", "Acts as an open circuit", "Amplifies the signal"),
  q("What is the 'Early Effect' in BJT transistors?", "Variation in the effective base width due to collector-base voltage", "Starting the circuit early", "A type of power failure", "A cooling problem"),
  q("What is 'Negative Feedback' used for in amplifiers?", "Stabilize gain and increase bandwidth", "Increase noise", "Decrease input impedance", "Cause oscillation"),
  q("What is the purpose of a 'Varactor Diode'?", "To act as a voltage-controlled capacitor", "To rectify current", "To emit light", "To protect from surge"),
  q("What is 'Slew Rate' of an op-amp?", "Maximum rate of output voltage change", "The speed of light", "The power consumption", "The offset current"),
  q("Which amplifier configuration has high input and low output impedance?", "Emitter Follower (Common Collector)", "Common Emitter", "Common Base", "Common Drain"),
  q("What is a 'Schmitt Trigger' used for?", "Squaring a signal and removing noise", "Amplifying audio", "Rectifying AC", "Filtering high frequency"),
  q("What is the function of a 'Clamper' circuit?", "Adds a DC level to an AC signal", "Cuts off the peaks", "Multiples the voltage", "Filters noise"),
  q("What is the 'Efficiency' of a Class B power amplifier (max theoretical)?", "78.5%", "25%", "50%", "100%"),
  q("What defines the 'Q-point' of a transistor?", "The DC operating point (Ic and Vce)", "The quality of the material", "The quickness of response", "The query point"),
  q("What is 'Thermal Runaway'?", "Self-destruction of a transistor due to heat-induced current increase", "A cool running circuit", "A type of battery charge", "A software crash"),
  q("What is the 'Bandwidth' of a circuit?", "Range of frequencies over which the gain is within 3dB of max", "The width of the wire", "The computer memory", "Connecting to the internet"),
  q("Which device uses a 'Gate' terminal for control similar to a tap?", "FET (Field Effect Transistor)", "BJT", "Diode", "Inductor"),
  q("What is a 'Voltage Regulator' IC (e.g. 7805)?", "Maintains a steady 5V output", "Amplifies voltage by 5", "Converts DC to 7805 Hz AC", "A type of memory"),
  q("What is the purpose of a 'Heat Sink'?", "Dissipate excess heat from components", "To sink the circuit in water", "To store cold energy", "To filter electrical noise"),
  q("What is 'Barkhausen Criterion' for oscillators?", "Loop gain = 1 and phase shift = 360/0 deg", "Voltage must be high", "Current must be low", "Resistance must be zero"),
  q("Which oscillator uses a crystal for high frequency stability?", "Crystal Oscillator", "Hartley Oscillator", "Colpitts Oscillator", "Phase Shift Oscillator"),
  q("What is a 'Varistor'?", "A resistor whose resistance depends on the applied voltage", "A variable resistor", "A type of capacitor", "A diode"),
  q("What does a 'Full Wave Bridge Rectifier' use?", "Four diodes", "Two diodes", "One diode", "A transformer only"),
  q("What is 'Input Offset Voltage'?", "Voltage needed to bring output to zero when inputs are grounded", "The power supply voltage", "The input signal peak", "A type of error in the log"),
  q("What is 'Crossover Distortion'?", "Occurs in Class B amplifiers when transitioning between transistors", "A signal crossing a wire", "A mistake in the design", "A noisy fan"),
  q("What is the 'Miller Effect'?", "Multiplication of input capacitance due to gain", "A type of cooling", "A beer brand for engineers", "A software update"),
  q("What is an 'Instrumentation Amplifier'?", "A highly accurate differential amplifier with high input impedance", "A music amp", "A type of scale", "A laboratory tool"),
  q("Which component opposes a sudden change in current?", "Inductor", "Capacitor", "Resistor", "Diode")
];

// Analog Electronics - Level 3 (Advanced)
export const analogElectronicsL3: SampleQuestion[] = [
  q("What is 'Lock-in Amplifier' used for?", "Extracting small signals from very noisy backgrounds", "Locking the circuit door", "Charging many batteries", "A high-speed MUX"),
  q("What is 'Harmonic Distortion'?", "Appearance of unwanted integer multiples of the fundamental frequency", "Beautiful music", "A type of wave", "A physical break"),
  q("Which op-amp parameter limits high-frequency performance?", "Gain-Bandwidth Product (GBW)", "Input Impedance", "Power Supply Voltage", "Offset Current"),
  q("What is 'Safe Operating Area' (SOA) of a power transistor?", "Region within which current/voltage limits must stay to prevent damage", "The lab area", "A type of documentation", "A cooling zone"),
  q("What is the primary advantage of 'Active Filters' over 'Passive Filters'?", "Integrated gain and no bulky inductors needed", "They need no power", "They are cheaper", "They are always digital"),
  q("What is 'Chopper-Stabilized' amplifier?", "Uses a switching mechanism to eliminate DC offset and drift", "A noisy amplifier", "An amplifier for helicopters", "A type of filter"),
  q("What is 'Logarithmic Amplifier' output proportional to?", "Natural logarithm of the input current", "Square of input", "Product of inputs", "Square root"),
  q("What is 'Phase-Locked Loop' (PLL) used for?", "Frequency synthesis and signal synchronization", "Locking the phase of a moon", "Storing data", "Measuring humidity"),
  q("What is 'ADC Flash Conversion'?", "Uses multiple comparators in parallel for extremely fast conversion", "Using a LED flash", "Saving data fast", "A type of software"),
  q("What is 'Current Mirror' circuit?", "Used to copy a reference current through another path", "A mirror made of current", "A type of optic sensor", "A duplicate database"),
  q("What is 'PSR' (Power Supply Rejection)?", "Ability of the circuit to ignore noise from the power lines", "Rejecting a new power cable", "Running out of juice", "Managing energy"),
  q("Which device is best for high-voltage and high-current power switching?", "IGBT (Insulated Gate Bipolar Transistor)", "NPN", "MOSFET", "JFET"),
  q("What is 'Intermodulation Distortion'?", "Creation of new frequencies from the sum and difference of input signals", "A frequency mix", "A typo in code", "A type of battery leak"),
  q("What is 'Bode Plot' used for?", "Frequency response analysis (Gain/Phase vs Frequency)", "Plotting a movie", "Drawing a circuit", "Measuring voltage levels"),
  q("What is 'Compensation' in Op-Amps?", "Adding internal capacitance to ensure stability and prevent oscillation", "Paying the designer", "Adding more gain", "Deleting the offset"),
  q("What is 'Translinear Principle'?", "Relationship where current ratios are products/sums in bipolar circuits", "A linear move", "A straight line", "A data flow"),
  q("Which bridge is used to measure unknown resistance accurately?", "Wheatstone Bridge", "Maxwell Bridge", "Schering Bridge", "Wien Bridge"),
  q("What is 'Parasitic Oscillation'?", "Unwanted oscillation due to feedback through stray capacitance/inductance", "A ghost in the app", "A noisy computer", "A type of virus"),
  q("What is 'ADC Successive Approximation'?", "Uses a binary search to find the digital value", "Fastest type of ADC", "A simple counter", "A manual process"),
  q("What is the 'Noise Figure' of a component?", "Measure of degradation of signal-to-noise ratio", "A number in a chart", "The sound of a fan", "A type of error"),
  q("What is 'Thermal Noise'?", "Electrical noise generated by random thermal motion of electrons", "A noisy heater", "A broken sensor", "A software crash"),
  q("What is 'Flicker Noise'?", "Low-frequency noise found in most electronic devices", "Flashing lights", "A high-frequency beep", "A type of error log"),
  q("What is 'Sample and Hold' circuit used for?", "Maintaining stationary voltage for ADC conversion", "Holding a file", "Sampling a user", "A type of memory"),
  q("What is 'OTA' (Operational Transconductance Amplifier)?", "Amplifier where differential input voltage produces an output current", "An over-the-air update", "A type of radio", "A security standard"),
  q("What is 'Bootstrap' circuit in analog?", "Positive feedback used to increase input impedance", "Starting the computer", "A type of file", "A footwear brand"),
  q("What is 'Voltage Follower' purpose?", "Buffer for impedance matching (Gain = 1)", "Following the leader", "Adding voltage", "Converting AC to DC"),
  q("What is 'Integrator' circuit?", "Performs mathematical integration on input signal", "Adds two numbers", "Joins databases", "Cleans code"),
  q("What is 'Differentiator' circuit?", "Produces output proportional to rate of change of input", "Subtracts two numbers", "Differentiates users", "Filters noise"),
  q("What is 'Peak Detector'?", "Stores the highest value of a signal", "Detects mountains", "A type of sensor", "A measure of energy"),
  q("What is 'Precision Rectifier'?", "Op-amp circuit that rectifies small signals", "A high-speed motor", "A type of scale", "A tool for alignment")
];

// Embedded Systems - Level 2 (Intermediate)
export const embeddedSystemsL2: SampleQuestion[] = [
  q("What is the primary difference between I2C and SPI?", "I2C uses 2 wires; SPI uses 4 wires", "I2C is faster", "SPI is multi-master by default", "They are identical"),
  q("What does a 'Watchdog Timer' (WDT) help with?", "Recovering the system from software hangs", "Measures time for the user", "Acts as an alarm clock", "Stores data"),
  q("In an RTOS, what is 'Preemption'?", "OS interrupts a lower-priority task to run a higher-priority one", "Deleting a task", "Adding more RAM", "Starting the bootloader"),
  q("What is 'UART' transmission?", "Asynchronous serial communication", "Fast parallel link", "Synchronous wireless protocol", "A type of memory bus"),
  q("What is the purpose of the 'Stack' in local function calls?", "Store return addresses and local variables", "Store large images", "Organize files", "Hold global settings"),
  q("What is 'Bare-Metal' programming?", "Programming directly on hardware without an OS", "Programming using Linux", "Designing the metal casing", "Using a library"),
  q("Which protocol uses the terms 'Master' and 'Slave'?", "SPI and I2C", "HTTP", "TCP", "UDP"),
  q("What is 'DMA'?", "Allows peripherals to move data without CPU involvement", "Double memory space", "A software tool", "An external hard drive"),
  q("What is a 'Bootloader'?", "First piece of code that runs and loads the main firmware", "A tool for boots", "A way to load apps", "A secondary app"),
  q("What is the purpose of 'Atomic' operations?", "Ensuring an operation is not interrupted", "Using small variables", "Splitting code", "Cleaning memory"),
  q("What is 'Endianness'?", "The order of bytes in memory (Big/Little)", "The speed of the CPU", "The number of bits", "A type of cable"),
  q("Which memory is typically used for code execution in MCUs?", "Flash", "EEPROM", "SRAM", "DRAM"),
  q("What does 'ADC' resolution of 12-bits mean?", "4096 discrete voltage levels", "12 levels", "1024 levels", "40,000 levels"),
  q("What is 'Jitter' in RTOS?", "Varation in the timing of task execution", "A nervous reaction", "A fast movement", "A power failure"),
  q("What is the purpose of 'Volatile' keyword?", "Prevents compiler from optimizing out hardware register reads", "Speed up code", "Delete variable", "Make constant"),
  q("What is 'I/O Polling'?", "CPU repeatedly checks a status bit", "Waiting for a signal", "Asking the user", "Running a scan"),
  q("What is an 'External Interrupt'?", "Hardware signal from a pin that triggers an ISR", "A code error", "A cloud message", "A user click"),
  q("Which module is used for precise time measurements?", "Timers/Counters", "ADC", "UART", "GPIO"),
  q("What is 'Memory-Mapped I/O'?", "Peripherals are accessed via specific memory addresses", "Separate I/O instructions", "Using a map for memory", "Virtual memory for apps"),
  q("What is a 'Semaphore' useful for?", "Synchronizing tasks and protecting shared resources", "A type of signal flag", "Allocating RAM", "Naming files"),
  q("What is 'Race Condition'?", "When two tasks access shared data leading to unpredictability", "A competition between robots", "A fast code", "A hardware crash"),
  q("What is 'RTOS Task Context'?", "The CPU state saved when a task is switched out", "The name of the project", "The user's account", "The database log"),
  q("What is 'Brown-Out Reset'?", "Resets the CPU if the voltage supply drops too low", "A type of user log", "A cooling system", "A backup power"),
  q("Which communication is typically used for industrial applications?", "CAN / RS485", "I2C", "SPI", "Bluetooth"),
  q("What is a 'Logic Analyzer' used for?", "Capturing and viewing digital signals", "Thinking logically", "Writing code", "Measuring temperature"),
  q("What is 'OTA' update?", "Updating software wirelessly", "Updating in an airplane", "Updating by hand", "A type of fan"),
  q("What is the purpose of 'ISR'?", "A function that handles an interrupt promptly", "A list of projects", "A networking tool", "A database record"),
  q("Which is a common MCU core architecture?", "ARM Cortex-M", "Intel i7", "AMD Ryzen", "Nvidia RTX"),
  q("What is 'Baud Rate'?", "The speed of serial communication", "The cost of hardware", "The number of users", "A type of cable"),
  q("What is 'Silicon ID'?", "A unique serial number burned into every chip", "The name of a company", "A type of memory", "A security standard")
];

// Embedded Systems - Level 3 (Advanced)
export const embeddedSystemsL3: SampleQuestion[] = [
  q("What is 'Priority Inversion' in RTOS?", "When a low-priority task holds a resource needed by a high-priority one", "Reversing task order", "Making all tasks equal", "A type of software crash"),
  q("What is 'Priority Inheritance'?", "A solution to priority inversion", "Getting a job from a parent", "A specialized team", "A software library"),
  q("What is 'Deadlock'?", "Two tasks waiting for each other, blocking both", "A broken door", "The end of a program", "A type of alert"),
  q("Which mechanism is best for zero-latency task communication?", "Direct Task Notifications", "Queues", "Sending HTTP requests", "Writing to Flash"),
  q("What is 'Safety-Critical' software?", "Code written following strict rules for reliability", "Code that is dangerous", "A specialized antivirus", "A secure database"),
  q("What is 'MMU' (Memory Management Unit)?", "Hardware that handles virtual memory and protection", "A memory stick", "Managing large files", "A type of processor core"),
  q("What is the difference between 'ICD' and 'Emulator'?", "Emulator mimics hardware externally; ICD works within the real chip", "No difference", "ICD is for robots", "Emulator is faster"),
  q("What is 'Core Dump'?", "The captured state of the system memory after a crash", "A place for old chips", "A large database", "A type of log file"),
  q("What is 'Power Profiling'?", "Measuring current consumption over time", "Listing usernames", "Setting up a server", "Measuring CPU speed"),
  q("What is 'Secure Boot'?", "Ensuring only signed, trusted firmware can be executed", "Using a password to boot", "Booting in a safe room", "A faster way to start"),
  q("What is 'Hard Real-Time' vs 'Soft Real-Time'?", "Hard fails if a deadline is missed; Soft allows latency", "Hard is for hardware; Soft is for software", "No difference", "Hard is faster"),
  q("What is 'Instruction Cache' vs 'Data Cache'?", "Separating instructions from data", "Sharing memory", "Adding more RAM", "A type of flash memory"),
  q("What is 'In-Application Programming' (IAP)?", "Allowing a running app to update its own Flash", "Programming while at work", "A type of user interface", "A security standard"),
  q("Which bus is commonly used for graphics in embedded?", "MIPI / LVDS", "UART", "I2C", "CAN"),
  q("What is 'Trace Data'?", "Real-time execution data sent by the CPU", "A type of drawing", "A list of bank records", "A memory address"),
  q("What is 'Fault Tolerance'?", "Ability of a system to continue operating during a fault", "Ignoring errors", "Fixing errors manually", "A type of backup"),
  q("What is 'Static Analysis' of code?", "Checking source code for errors without running it", "Measuring speed", "Testing hardware", "Reading documentation"),
  q("Which linker section typically stores initialized global variables?", ".data", ".bss", ".text", ".stack"),
  q("Which linker section typically stores uninitialized global variables?", ".bss", ".data", ".text", ".heap"),
  q("What is 'Linker Script'?", "Defines where code/data sections are placed", "A script for linking web pages", "A type of CSS", "A manual for the linker"),
  q("What is 'HAL'?", "Hardware Abstraction Layer - API that hides hardware complexity", "A type of cabinet", "A group of designers", "A simulation tool"),
  q("What is 'TrustZone' architecture?", "Hardware-based security that isolates secret code", "A safe place in the office", "A type of antivirus", "A memory bank"),
  q("What is 'FPGA Coprocessor'?", "Offloading task from CPU to dedicated logic", "A fast computer", "A type of camera", "A networking tool"),
  q("What is 'Dynamic Voltage Scaling' (DVS)?", "Lowering voltage when CPU is idle", "Using many batteries", "A type of wire", "A security feature"),
  q("What is 'Cyclic Redundancy Check' (CRC)?", "Algorithm used to detect corruption in data blocks", "A type of loop", "A measure of speed", "A database record"),
  q("What is 'Nvm' in embedded software?", "Non-Volatile Memory (Flash/EEPROM)", "Node Version Manager", "New Volume Mode", "Network Value Manual"),
  q("What is 'Bit-Banging'?", "Software implementation of a serial protocol using GPIO", "Hitting the computer", "A type of fast motion", "A database query"),
  q("What is 'Double-Pointer' used for?", "Modifying the original pointer address", "A pointer to a twin", "An expensive variable", "A type of array"),
  q("Which tool is used for In-Circuit Programming?", "Programmer/Debugger", "A screwdriver", "A user's computer", "A cloud server"),
  q("What is the significance of the Reset Vector?", "The memory address where the CPU starts after power-on", "A vector drawing", "An error message", "The end of the code")
];

