import { type SampleQuestion } from "./sample-questions";

const q = (question_text: string, correct: string, wrong1: string, wrong2: string, wrong3: string): SampleQuestion => ({
  question_text,
  options: [
    { text: correct, is_correct: true },
    { text: wrong1, is_correct: false },
    { text: wrong2, is_correct: false },
    { text: wrong3, is_correct: false },
  ].sort(() => Math.random() - 0.5),
  marks: 1,
});

export const roboticsL1: SampleQuestion[] = [
  q("What is Robotics?", "The branch of technology that deals with the design, construction, operation, and application of robots", "The study of rocks", "The science of flying", "A type of video game"),
  q("What is a Sensors in robotics?", "Devices that allow a robot to perceive its environment", "The robot's brain", "The robot's wheels", "A type of battery"),
  q("What is an Actuator?", "A component of a machine that is responsible for moving and controlling a mechanism or system", "A sensor", "A computer screen", "A piece of software"),
  q("What is the 'Degrees of Freedom' (DoF)?", "The number of independent ways a mechanical system can move", "The weight of a robot", "The price of a robot", "The battery life"),
  q("Which of these is a common microcontroller used in robotics?", "Arduino", "Windows 10", "Adobe Photoshop", "Google Chrome"),
  q("What is LIDAR?", "Light Detection and Ranging", "Level Integrated Data Access", "Long Internal Digital Audio Reader", "Laser Induced Digital Array"),
  q("What is a 'Servo Motor'?", "A motor that can be commanded to a specific angular position", "A motor that only spins one way", "A type of engine", "A water pump"),
  q("What is 'Path Planning'?", "Finding a valid path from a start point to a goal point without hitting obstacles", "Building a robot", "Drawing a map", "A type of battery"),
  q("What is 'SLAM'?", "Simultaneous Localization and Mapping", "Simple Linear Array Management", "System Level Access Method", "Static Local Area Monitor"),
  q("What is an Encoder?", "A device that converts motion to an electrical signal", "A type of motor", "A sensor for heat", "A computer case"),
  q("Which sensor is used to measure distance using sound?", "Ultrasonic sensor", "Infrared sensor", "Gyroscope", "Accelerometer"),
  q("What is a Gyroscope used for?", "Measuring or maintaining orientation and angular velocity", "Measuring height", "Measuring speed", "Measuring light"),
  q("What is an Accelerometer used for?", "Measuring proper acceleration", "Measuring temperature", "Measuring sound", "Measuring humidity"),
  q("What is the 'End Effector'?", "The device at the end of a robotic arm, designed to interact with the environment", "The robot's head", "The power source", "The base of the robot"),
  q("What is 'Teleoperation'?", "Operation of a robot from a distance", "Automatic operation", "Fast operation", "Voice control"),
  q("What is a 'Humanoid' robot?", "A robot with its body shape built to resemble the human body", "A robot that looks like a dog", "A flying robot", "A industrial robot"),
  q("What is 'Isaac Asimov' famous for in robotics?", "The Three Laws of Robotics", "Inventing the first robot", "Creating the word 'robot'", "Building the first AI"),
  q("What is 'ROS'?", "Robot Operating System (middleware)", "Robot Output System", "Radial Operating Speed", "Robot Optimization Software"),
  q("What is a 'Brushless DC' (BLDC) motor?", "A motor that uses electronic commutation instead of brushes", "A motor that needs water", "A motor with many brushes", "A type of battery"),
  q("What is 'Inverse Kinematics'?", "Determining the joint angles needed to place the end effector in a desired position", "Calculating speed", "Forward motion", "Robot vision"),
  q("What is a 'Bipedal' robot?", "A robot that walks on two legs", "A robot with four wheels", "A flying robot", "A swimming robot"),
  q("What is 'Artificial Intelligence' (AI) in robotics?", "The ability of a robot to perform tasks that typically require human intelligence", "A fancy screen", "A fast motor", "A big battery"),
  q("What is a 'Cobot'?", "A collaborative robot intended for direct human-robot interaction", "A combat robot", "A robot that builds cars", "A home robot"),
  q("Which material is commonly used for lightweight robot frames?", "Aluminum", "Lead", "Cement", "Wood"),
  q("What is 'Computer Vision'?", "The field that deals with how computers can gain high-level understanding from digital images", "A type of screen", "A glasses for robots", "Robot memory"),
  q("What is a 'Proximity Sensor'?", "A sensor that detects the presence of nearby objects without any physical contact", "A heat sensor", "A sound sensor", "A weight sensor"),
  q("What is 'Haptic Feedback'?", "Providing physical sensations (touch/vibration) to a user", "A sound signal", "A light signal", "A database update"),
  q("What is the 'Euler angles'?", "A way of describing the orientation of a rigid body in three-dimensional space", "A type of geometry", "Robot joints", "Battery capacity"),
  q("What is 'Dead Reckoning'?", "The process of calculating current position by using a previously determined position", "A broken robot", "A type of code", "Searching for obstacles"),
  q("What is 'Swarm Robotics'?", "The study of how large numbers of simple robots can coordinate to perform tasks", "Robots that look like bees", "Fighting robots", "Robots in space")
];

export const vlsiL1: SampleQuestion[] = [
  q("What does VLSI stand for?", "Very Large Scale Integration", "Value Level System Integration", "Variable Longitudinal Signal Interface", "Vector Logic System Instruction"),
  q("Which material is the most common substrate for VLSI circuits?", "Silicon", "Copper", "Aluminum", "Germanium"),
  q("What is Moore's Law?", "The number of transistors on a microchip doubles about every two years", "Complexity increases every year", "Speed doubles every year", "Prices drop every year"),
  q("What is a MOSFET?", "Metal-Oxide-Semiconductor Field-Effect Transistor", "Modular Output Signal Filter", "Main Operating System for Electronics", "Mobile Signal Feedback Tool"),
  q("What is 'Photolithography'?", "A process used in microfabrication to pattern parts of a thin film", "Taking photos of chips", "A type of software", "Measuring light"),
  q("What is 'Doping' in semiconductors?", "Intentionally introducing impurities into an intrinsic semiconductor for the purpose of modulating its electrical properties", "Cleaning the wafer", "Adding gold wires", "Testing the chip"),
  q("Which tool is commonly used for VLSI design?", "Cadence", "Microsoft Word", "Adobe Premiere", "Google Sheets"),
  q("What is 'ASIC'?", "Application-Specific Integrated Circuit", "Advanced Signal Interface Controller", "Automatic System Integration Code", "Analog Serial Input Circuit"),
  q("What is 'FPGA'?", "Field Programmable Gate Array", "Fast Processing Ground Array", "Fixed Path Gate Assembly", "Flexible Prototype Grid Area"),
  q("What is 'Floorplanning' in VLSI design?", "The process of identifying structures that should be placed close together and allocating space", "Designing the factory floor", "Making a list of components", "A type of simulation"),
  q("What is 'Static Timing Analysis' (STA)?", "A method of computing the expected timing of a digital circuit without simulating the behavior", "Testing the chip speed under load", "Measuring the clock frequency", "A way to check power usage"),
  q("What is 'CMOS'?", "Complementary Metal-Oxide-Semiconductor", "Code Managed Operating System", "Circuit Modified Output System", "Common Modular Operating Standard"),
  q("What is a 'Standard Cell'?", "A functional block (like NAND/NOR) used in ASIC design", "A type of battery", "A mobile phone unit", "A default wafer size"),
  q("What is 'Synthesis' in VLSI?", "Converting a high-level description (HDL) into a gate-level netlist", "Making the chip physically", "Testing the chip", "Designing the layout by hand"),
  q("What is 'Routing'?", "The process of connecting terminals defined by a netlist using wires", "Finding the path for the signal", "Managing web traffic", "Scheduling tasks"),
  q("What is 'GDSII'?", "A database file format which is the industry standard for data exchange of IC layout artwork", "A type of processor", "A simulation tool", "A hardware language"),
  q("What is 'Design Rule Check' (DRC)?", "Verification that the layout meets the manufacturing rules of the foundry", "Checking for bugs in code", "Simulating the circuit", "A type of logic test"),
  q("What is 'LVS'?", "Layout Versus Schematic - checking if layout matches the original circuit design", "Low Voltage Signal", "Language Verification System", "Logic Vector Synthesis"),
  q("What is 'Power Dissipation'?", "The loss of energy in the form of heat in a circuit", "Adding power to a chip", "Generating electricity", "Battery life"),
  q("What is a 'Via' in a PCB/IC?", "An electrical connection between different layers", "A type of signal", "A bypass capacitor", "An input terminal"),
  q("What is 'VHDL'?", "VHSIC Hardware Description Language", "Visual Hardware Design Language", "Variable Hardware Data Link", "Velocity Hardware Design Logic"),
  q("What is 'Verilog'?", "A hardware description language (HDL) used to model electronic systems", "A programming language like Java", "A simulation tool", "A data format"),
  q("What is a 'Wafer'?", "A thin slice of semiconductor used for the fabrication of integrated circuits", "A component of an inductor", "A data packet", "A cleaning tool"),
  q("What is 'Foundry' in VLSI?", "A factory that manufactures integrated circuits", "A software library", "A group of designers", "A type of transistor"),
  q("What is 'Extraction' in VLSI CAD?", "Deriving parasitic resistance and capacitance from the layout", "Removing the chip from the wafer", "Retrieving data from a database", "Sampling signals"),
  q("What is an 'Iterative Design' process?", "A methodology based on cyclic process of prototyping, testing, analyzing, and refining", "Designing once and building", "Using AI to design", "Slow design"),
  q("What is 'Interconnect'?", "The wiring that connects transistors and other components on a chip", "A network connection", "A type of transistor", "Internal communication"),
  q("What is 'Crosstalk'?", "Unwanted signal coupling between two wires", "Communication between teams", "A type of signal noise", "A wireless protocol"),
  q("What is 'Tape-out'?", "The final result of the design process for integrated circuits", "The end of the day", "Setting up a test", "Recording a simulation"),
  q("What is 'N-well' in CMOS process?", "A region of the substrate doped with n-type impurities to host PMOS transistors", "A water well", "A negative terminal", "A type of capacitor")
];

export const computerArchL1: SampleQuestion[] = [
  q("What is Computer Architecture?", "The set of rules and methods that describe the functionality, organization, and implementation of computer systems", "The building for computers", "A type of software", "The history of computing"),
  q("What is the 'Von Neumann architecture'?", "A design template for a digital computer that uses a processing unit and a single separate storage structure", "A computer that only has RAM", "A distributed system", "A computer with no CPU"),
  q("What does CPU stand for?", "Central Processing Unit", "Central Power Unit", "Computer Processing Utility", "Common Program Unit"),
  q("What is 'ALU'?", "Arithmetic Logic Unit - performs arithmetic and logical operations", "Advanced Layout Unit", "Automatic Link User", "Adaptive Logic Universal"),
  q("What is 'Control Unit'?", "The part of the CPU that directs the operation of the processor", "The power button", "The keyboard controller", "A type of software"),
  q("What is 'RAM'?", "Random Access Memory - volatile memory for temporary storage", "Read All Memory", "Rapid Access Method", "Real-time Access Metadata"),
  q("What is 'Cache Memory'?", "A high-speed storage layer which stores a subset of data", "Hidden files", "A type of database", "The hard drive"),
  q("What is the 'Harvard architecture'?", "A computer architecture with separate storage and signal pathways for instructions and data", "A computer from Harvard university", "A computer with no memory", "A mainframe"),
  q("What is 'Instruction Set Architecture' (ISA)?", "An abstract model of a computer that defines how the software controls the hardware", "A set of books for computers", "A type of coding style", "The speed of the CPU"),
  q("What is 'Pipelining'?", "A technique where multiple instructions are overlapped during execution", "Connecting the CPU with pipes", "A way to speed up memory", "A database query flow"),
  q("What is 'Register'?", "A small, very fast storage location within the CPU", "A list of users", "A type of memory address", "A software record"),
  q("What is the 'Program Counter' (PC)?", "A register that holds the address of the next instruction to be executed", "A counter for how many programs are running", "A type of clock", "The power supply"),
  q("What is 'Clock Speed'?", "The rate at which a processor executes instructions", "The time on the computer", "The speed of the internet", "The size of the hard drive"),
  q("What is 'Multicore Processor'?", "A single computing component with two or more independent processing units (cores)", "A computer with many CPUs", "A software library", "A type of RAM"),
  q("What is 'Bus' in computer architecture?", "A communication system that transfers data between components", "A vehicle for transport", "A serial port", "A power cable"),
  q("What is 'I/O'?", "Input/Output - communication between the computer and the external world", "Initial/Output", "Internal/Offline", "Intelligent/Order"),
  q("What is 'ROM'?", "Read-Only Memory - non-volatile memory that stores permanent data", "Random Online Memory", "Rapid Output Mode", "Read On Main"),
  q("What is 'Virtual Memory'?", "A memory management technique that provides an idealized abstraction of memory to user programs", "A memory on the cloud", "Memory used for VR", "Hidden data on disk"),
  q("What is the 'Opcode'?", "The part of an instruction that specifies the operation to be performed", "An optional code", "Object code", "Optimal code"),
  q("What is 'Operand'?", "The data or the location of data on which the operation is performed", "The person using the computer", "A mathematical operator", "A result of a function"),
  q("What is 'Direct Memory Access' (DMA)?", "A feature that allows certain hardware subsystems to access main system memory independently of the CPU", "Fast memory access", "Double memory allocation", "Directing memory to apps"),
  q("What is the 'Clock Cycle'?", "The time between two consecutive pulses of a modern processor", "The time to boot up", "The life of a computer", "A full day of computing"),
  q("What is 'Big Endian'?", "The most significant byte is stored at the smallest address", "A large computer", "A fast CPU", "A type of memory segment"),
  q("What is 'Little Endian'?", "The least significant byte is stored at the smallest address", "A small computer", "A low-power CPU", "A type of instruction"),
  q("What is 'Branch Prediction'?", "A technique that tries to predict which path a branch (like an if statement) will take", "Predicting the weather", "Estimating variable values", "Finding the best route for data"),
  q("What is an 'Interrupt'?", "A signal to the processor emitted by hardware or software indicating an event that needs immediate attention", "A signal to stop the computer", "A mistake in code", "A loud noise"),
  q("What is 'Overclocking'?", "Increasing the clock speed of a processor beyond its default factory setting", "Using the computer too much", "Using a fast clock", "Running too many programs"),
  q("What is 'Throughput'?", "The amount of work a computer can do in a given amount of time", "The size of a file", "The speed of light", "The power consumption"),
  q("What is 'Instruction Latency'?", "The time it takes for an instruction to complete its execution", "The size of an instruction", "The waiting time for the user", "The cost of a CPU"),
  q("What is 'Moore's Law' primarily about?", "The number of transistors in a dense integrated circuit doubling about every two years", "Complexity increasing", "Speed doubling", "Power decreasing")
];

export const pcbDesignL1: SampleQuestion[] = [
  q("What does PCB stand for?", "Printed Circuit Board", "Personal Computer Base", "Power Circuit Board", "Processor Control Board"),
  q("What is a 'Schematic' in PCB design?", "A diagram that shows the electrical connections and functions of a circuit", "A layout of the board", "A list of components", "A type of software"),
  q("What is a 'Footprint' or 'Land Pattern'?", "The arrangement of pads and other features on the PCB for soldering a component", "The size of the board", "The weight of the board", "The distance between components"),
  q("What is 'Routing' in PCB layout?", "The process of layout the copper tracks to connect the components", "Finding the path for the signal", "Managing web traffic", "Scheduling tasks"),
  q("What is a 'Via'?", "A plated-through hole used to connect tracks on different layers of a PCB", "A type of signal", "A bypass capacitor", "An input terminal"),
  q("What is 'Soldermask' (Solder Resist)?", "A thin lacquer-like layer of polymer that is usually applied to the copper traces to prevent oxidation and shorts", "A mask for the designer", "A cleaning tool", "A type of glue"),
  q("What is 'Silkscreen' layer?", "The layer used for identifying components, test points, PCB part numbers, and company logos", "A layer for printing colors", "A screen for filtering noise", "A cleaning tool"),
  q("What is 'BOM'?", "Bill of Materials - a list of the raw materials, sub-assemblies, and components needed to manufacture the PCB", "Best Operating Mode", "Board Of Management", "Base Output Message"),
  q("What is 'DRC' in PCB design?", "Design Rule Check - checking for common errors like shorts or trace width issues", "Data Routing Center", "Direct Routing Control", "Digital Radio Circuit"),
  q("What is 'Copper Pour' or 'Copper Plane'?", "A large area of copper on one or more layers, often used for ground or power", "Adding more copper by hand", "Cleaning the copper", "A type of wire"),
  q("What is a 'Trace' or 'Track'?", "A copper wire that connects components on a PCB", "A physical path for the user", "A type of component", "A result of a test"),
  q("What is the 'Gerber File'?", "The industry standard file format for describing PCB layer images", "A type of project file", "A simulation result", "A data sheet"),
  q("What is 'Surface Mount Technology' (SMT)?", "A method for producing electronic circuits where components are mounted directly onto the surface of PCBs", "Mounting components on a table", "Using very small wires", "A manual soldering method"),
  q("What is 'Through-Hole' technology?", "Components with leads that are inserted into holes drilled in PCBs and soldered to pads on the opposite side", "A way to drill holes", "A type of connector", "An old assembly method"),
  q("What is 'Padding' or 'Land'?", "The area of copper to which a component lead is soldered", "Adding extra space", "A type of connector", "A protective layer"),
  q("What is 'FR-4'?", "A common base material for PCBs, made of flame-retardant epoxy-glass composite", "A type of processor", "A simulation tool", "A data format"),
  q("What is 'Panels' or 'Panelization'?", "Grouping several PCBs onto one large sheet for manufacturing efficiency", "Building a control panel", "Adding a frame to the board", "A type of software"),
  q("What is 'Thermal Relief'?", "A connection to a large copper area with small traces to make soldering easier", "A component that cools down", "A fan for the board", "A heat sink"),
  q("What is 'Pick and Place'?", "An automated process where machines place SMT components onto a PCB", "A game for designers", "Manual assembly", "A type of software"),
  q("What is 'Annular Ring'?", "The area of copper pad that remains around a hole after it is drilled", "A wedding ring", "A type of capacitor", "A circle around a component"),
  q("What is 'Differential Pair'?", "Two traces of same length used to carry high-speed signals with reduced EMI", "A pair of components", "A different type of wire", "A parallel connection"),
  q("What is 'Impedance Control'?", "Ensuring traces have a specific characteristic impedance for signal integrity", "Controlling the speed of signal", "A security measure", "Managing power usage"),
  q("What is 'Blind Via'?", "A via that connects an outer layer to one or more inner layers but does not go through the entire board", "A via that you can't see", "A broken via", "A via for power only"),
  q("What is 'Buried Via'?", "A via that connects two or more inner layers but does not reach either outer layer", "A via hidden under a component", "An expensive via", "A grounding via"),
  q("What is 'Clearance' in PCB design?", "The minimum distance between two copper features", "Clearing the work area", "Removing short circuits", "Deleting traces"),
  q("What is 'Trace Width'?", "The width of the copper connection, which determines how much current it can carry", "The length of the wire", "The thickness of the copper", "The speed of the signal"),
  q("What is 'Reflow Soldering'?", "A process where solder paste is melted to create permanent electrical joints", "Melting the board", "Using a iron by hand", "A cleaning process"),
  q("What is 'Wave Soldering'?", "A bulk soldering process for through-hole components", "Soldering in the ocean", "Fast soldering", "A manual process"),
  q("What is 'Netlist'?", "A list of all the electrical connections between component terminals", "A web addresses list", "A group of variables", "A simulation result"),
  q("What is 'Fiducial Mark'?", "A mark on the PCB used as a reference point for automated assembly machines", "A company logo", "A mistake on the board", "A test point")
];

export const roboticsL2: SampleQuestion[] = [
  q("In PID control, what does the 'Integral' term primarily help with?", "Eliminating steady-state error", "Reducing overshoot", "Increasing response speed", "Reducing noise"),
  q("Which sensor fusion algorithm is most commonly used for orientation estimation?", "Kalman Filter", "Binary Search", "Quicksort", "Fast Fourier Transform"),
  q("What is the primary advantage of a 'Brushless' motor over a 'Brushed' motor?", "Higher efficiency and lower maintenance", "Simpler control logic", "Lower cost", "Lower torque"),
  q("In the context of SLAM, what is 'Loop Closure'?", "Recognizing a previously visited location to reduce drift", "Completing a circular path", "Turning off the robot", "Connecting a battery"),
  q("What does a 'Jacobian Matrix' represent in robotics?", "The relationship between joint velocities and end-effector velocities", "The robot's weight distribution", "The sensor noise profile", "The battery discharge curve"),
  q("Which communication protocol is frequently used for low-level sensor interfacing?", "I2C", "HTTP", "FTP", "SMTP"),
  q("What is 'Dead Reckoning' error primarily caused by?", "Cumulative integration of small measurement errors over time", "A sudden hardware failure", "Lack of power", "Strong magnetic fields"),
  q("What is the difference between 'Forward Kinematics' and 'Inverse Kinematics'?", "FK finds position from angles; IK finds angles from position", "FK is for wheels; IK is for arms", "FK is faster; IK is more accurate", "There is no difference"),
  q("What is a 'Global Costmap' used for in navigation stacks?", "Long-range path planning across the entire known environment", "Short-range obstacle avoidance", "Measuring battery usage", "Updating the robot's firmware"),
  q("Why is 'Filtering' necessary for raw sensor data?", "To remove noise and outliers from the signal", "To change the sensor's color", "To make the data larger", "To encrypt the data"),
  q("What is 'Odometry'?", "The use of data from motion sensors to estimate change in position over time", "The study of robot smells", "A type of motor control", "Measuring the robot's height"),
  q("What is a 'Collision Volume' in simulation?", "A simplified geometric shape used to detect contact between objects", "The volume of a robot's speaker", "The amount of space a robot takes up", "A measure of impact force"),
  q("What is 'Task Space'?", "The coordinate system where the robot's end effector operates", "The room where the robot works", "The memory allocated for a script", "A type of user interface"),
  q("What is 'Joint Space'?", "The set of all possible joint angles of a robot", "The area between two robots", "A type of mechanical hinge", "A shared folder"),
  q("Which algorithm is often used for reactive obstacle avoidance?", "Vector Field Histogram (VFH)", "A* Search", "Dijkstra's Algorithm", "Bubble Sort"),
  q("What is 'Sensor Aliasing'?", "When different locations appear identical to a sensor", "Using a nickname for a sensor", "A type of sensor failure", "Combining two sensors"),
  q("What is the purpose of 'Normalization' in computer vision pipelines?", "Ensuring pixel values fall within a standard range (e.g., 0 to 1)", "Resizing an image", "Converting to grayscale", "Detecting edges"),
  q("What is a 'Transformation Matrix' (4x4) used for?", "Representing both rotation and translation in 3D space", "Adding two numbers", "Measuring temperature", "Displaying a 2D map"),
  q("What is the 'Condition Number' of a Jacobian used for?", "Measuring how close a robot is to a 'singular' configuration", "Predicting battery life", "Counting the number of joints", "Estimating the robot's age"),
  q("What is 'Behavior Trees' in robotic high-level control?", "A way of organizing complex, modular task logic", "A map of the forest", "A type of data structure for sensors", "A visual effect for screens"),
  q("What is 'Impedance Control' used for?", "Controlling how a robot reacts to external forces/contact", "Saving energy", "Preventing electrical shorts", "Speeding up the CPU"),
  q("What is the 'Sampling Rate' of a controller?", "The frequency at which the control loop executes", "The size of the sensor", "The number of bits used", "The price of the hardware"),
  q("What is 'Latency' in a teleoperation system?", "The delay between a command and the robot's actual motion", "The weight of the remote", "The quality of the video", "The battery level"),
  q("What is 'Motion Primitives'?", "Pre-computed or standardized motion segments used for fast planning", "Basic building blocks of life", "A type of primary color", "Simple math functions"),
  q("What is 'Feature Extraction' in vision?", "Identifying key points or patterns like edges and corners in an image", "Removing a broken lens", "Adding a filter to a photo", "Saving a screenshot"),
  q("What is 'Particle Filter' used for in localization?", "Representing multiple possible robot positions as weighted particles", "Cleaning the robot's air intake", "Filtering out dust from sensors", "A type of battery chemistry"),
  q("What is 'Dynamic Model' of a robot?", "A mathematical description that includes mass, inertia, and forces", "A robot that moves quickly", "A 3D model of a robot", "A simulation that looks real"),
  q("What is 'Torque Control'?", "Directly controlling the current to produce specific force at the joints", "Controlling the speed of wheels", "Measuring the weight of the robot", "Adjusting the volume"),
  q("What is 'Point Cloud'?", "A set of data points in space, usually produced by a 3D scanner/LIDAR", "A weather forecast for robots", "A type of storage drive", "A blurry image"),
  q("What is 'Gait' in legged robotics?", "A coordinated sequence of leg movements for walking or running", "The entrance to the lab", "A type of sensor", "The speed of the robot")
];

export const roboticsL3: SampleQuestion[] = [
  q("What is the 'Kidnapped Robot Problem'?", "Recovering localization after the robot is moved to an unknown location without its knowledge", "A robot being stolen from a lab", "A hardware failure in the GPS", "A software bug that stops the robot"),
  q("Which optimization technique is core to 'Model Predictive Control' (MPC)?", "Solving a constrained optimization problem over a future time horizon", "Gradient Descent on static data", "Genetic Algorithms for hardware design", "Simple lookup tables"),
  q("What is a 'Singularity' in robotic arm kinematics?", "A configuration where the robot loses one or more degrees of freedom", "A point where the robot is fastest", "The center of the robot", "A type of AI consciousness"),
  q("In Deep Reinforcement Learning for robotics, what is 'Sim-to-Real' transfer?", "Training a model in simulation and deploying it on physical hardware", "Converting real data to simulation", "Buying a new robot", "Upgrading the simulator"),
  q("What is 'Factor Graph' optimization in SLAM?", "A way of representing constraints between poses and landmarks to find the best global map", "A graph showing the robot's factory location", "A type of chart for battery life", "Multiplying two matrices"),
  q("What is 'Visual Odometry'?", "Estimating the robot's motion by analyzing consecutive camera images", "A speedometer for robots", "A map made by a human", "A type of glasses for robots"),
  q("What is 'Underactuated' robotics?", "A system that has fewer actuators than degrees of freedom", "A robot that is too slow", "A robot that is broken", "A robot with no battery"),
  q("What is 'Force/Torque (F/T) Sensor'?", "A sensor that measures the interaction forces at the robot's wrist", "An accelerometer", "A gyro", "A type of scale"),
  q("What is 'Semantic Mapping'?", "Adding human-level labels (like 'door', 'table') to a geometric map", "Drawing a beautiful map", "A map made of words", "A type of compression"),
  q("What is 'Active Sensing'?", "Controlling the robot's movement specifically to improve sensor data/reduce uncertainty", "A sensor that is turned on", "A fast sensor", "A sensor that emits light"),
  q("What is 'Redundancy' in a robotic manipulator?", "Having more degrees of freedom than required for a task", "A backup battery", "A type of error", "A duplicate code block"),
  q("What is 'Compliance' in robotics?", "The flexibility of a robot's joints or structure in response to external force", "Following the safety rules", "Signing a legal contract", "The weight of the robot"),
  q("What is 'Non-holonomic' constraint?", "A constraint on the relationship between the velocity and the position (e.g., a car cannot move sideways)", "A broken wheel", "A type of battery limit", "A software permission"),
  q("What is 'Workspace' vs 'Configuration Space'?", "Workspace is physical reach; C-space is the set of all possible joint states", "Workspace is the desk; C-space is the floor", "They are identical", "Workspace is for users; C-space is for admins"),
  q("What is 'Pose Graph SLAM'?", "Optimizing only the robot's path (poses) rather than individual landmarks", "Drawing a graph of robot poses", "A type of database for images", "A social media for robots"),
  q("What is 'Zero Moment Point' (ZMP)?", "A point where the horizontal components of the tipping moment are zero, used for bipedal stability", "The center of the robot", "The point where gravity is zero", "A type of sensor failure"),
  q("What is 'DMP' (Dynamic Movement Primitives)?", "A method for modeling and learning complex trajectories with stability guarantees", "A fast movement", "A digital map", "A type of motor controller"),
  q("What is 'Tele-existence'?", "A highly immersive form of teleoperation that makes the user feel 'present' at the robot's location", "A robot that is alive", "A type of internet connection", "A futuristic movie"),
  q("What is 'Soft Robotics'?", "Robotics made from flexible, compliant materials instead of rigid metal", "Robots that are nice to people", "Software-only robots", "A plush toy robot"),
  q("What is 'End-to-End Learning' in robotics?", "Mapping raw sensor data directly to motor commands using neural networks", "Learning from the start to the end of a project", "A type of school for robots", "A battery charging method"),
  q("What is 'Multi-modal' sensing?", "Combining data from different types of sensors (e.g., vision + touch)", "Using many sensors of the same type", "A sensor that changes modes", "A type of alarm"),
  q("What is 'Admittance Control'?", "A control strategy where a robot mimics a mass-spring-damper system in response to force", "Allowing a robot into a room", "Controlling the entrance of users", "A type of power management"),
  q("What is 'RRT*' (Rapidly-exploring Random Tree Star)?", "An asymptotically optimal version of the RRT path planning algorithm", "A very fast robot", "A map of the stars", "A type of search engine"),
  q("What is 'Bundle Adjustment' in computer vision?", "Simultaneously optimizing camera poses and 3D point positions", "Adjusting a bundle of wires", "A type of financial calculation", "Cleaning a camera lens"),
  q("What is 'Inverse Reinforcement Learning'?", "Learning the underlying reward function by observing an expert's behavior", "Teaching a human to be a robot", "Reversing a software update", "A type of battery cycle"),
  q("What is 'Swarm Intelligence'?", "Collective behavior of decentralized, self-organized systems", "A very smart robot", "A group of people working together", "A type of cloud computing"),
  q("What is 'Hexapod' robot?", "A six-legged robot", "A robot with six arms", "A flying robot", "A robot that looks like a snake"),
  q("What is 'Cross-Entropy Method' (CEM) in planning?", "An iterative sampling method for optimization and rare event simulation", "A type of chemical test", "Merging two datasets", "A measure of data noise"),
  q("What is 'Transfer Learning'?", "Using a pre-trained model on a new but related task", "Moving a robot to another room", "Charging a battery", "Sending data to a server"),
  q("What is 'Bio-inspired' robotics?", "Designing robots based on biological systems found in nature", "A robot that eats food", "A robot for doctors", "A type of green energy")
];

export const vlsiL2: SampleQuestion[] = [
  q("Which effect becomes significant as transistor sizes shrink into the nanometer range?", "Quantum Tunneling / Leakage", "Gravity", "Magnetic interference", "Battery drain"),
  q("What is the primary purpose of 'Clock Tree Synthesis' (CTS)?", "Ensuring uniform clock distribution and minimizing skew", "Growing a decorative tree", "Designing the CPU architecture", "Managing the power supply"),
  q("What is 'Slack' in timing analysis?", "The difference between the required time and the arrival time of a signal", "A communication tool", "A slow part of the circuit", "The distance between wires"),
  q("What is 'Electromigration'?", "The gradual displacement of atoms in a conductor caused by high current density", "Electricity moving through a wire", "A type of battery failure", "Moving a factory"),
  q("Which layer is used to define the actual logic gates in a standard cell library?", "Polysilicon and Diffusion", "Metal 1", "Metal 10", "Silkscreen"),
  q("What is 'Antenna Effect' in IC fabrication?", "Accumulation of charge on metal wires during plasma etching that can damage gate oxides", "Wireless reception on a chip", "A large metal structure", "A type of radio signal"),
  q("What is the difference between 'Dynamic Power' and 'Static Power'?", "Dynamic is during switching; Static is due to leakage", "Dynamic is higher; Static is lower", "Dynamic is from battery; Static is from wall", "No difference"),
  q("What is 'Latch-up' in CMOS circuits?", "A low-impedance path between power rails caused by parasitic bipolar transistors", "Locking the door", "A type of software crash", "Connecting two chips"),
  q("Which HDL construct is used for concurrent signal assignment?", "assign (in Verilog)", "if-else", "for loop", "case"),
  q("What is 'Scan Chain' used for in DFT (Design for Testability)?", "Testing internal flops by shifting data through them sequentially", "Scanning a document", "A type of security measure", "Manufacturing the chip"),
  q("What is 'Setup Time'?", "The minimum time a data signal must be stable before the clock edge", "The time to build the factory", "The time to boot the OS", "The time to design the circuit"),
  q("What is 'Hold Time'?", "The minimum time a data signal must be stable after the clock edge", "The time to wait for a signal", "A pause in the simulation", "The end of a project"),
  q("What is 'Signal Integrity' (SI)?", "A measure of the quality of an electrical signal", "A type of encryption", "The speed of the clock", "The honesty of a designer"),
  q("What is 'IR drop'?", "The voltage drop caused by the resistance of the power grid", "Losing a signal", "A type of cooling", "Dropping the chip on the floor"),
  q("What is 'Gate Delay' vs 'Wire Delay'?", "Gate is delay through transistor; Wire is delay through interconnect", "They are same", "Gate is faster", "Wire is for power only"),
  q("What is 'Logical Effort'?", "A method for estimating delay in a CMOS circuit", "Trying hard to think", "A type of logic test", "The complexity of a code"),
  q("What is 'Physical Design' (PD)?", "The step of converting a gate-level netlist into a geometric layout", "Building the computer case", "Designing the UI", "Measuring the chip size"),
  q("What is 'Standard Cell Library'?", "A collection of pre-designed logic gates and flip-flops", "A group of books about VLSI", "A place to study", "A file of code"),
  q("What is 'Placement' in VLSI?", "Deciding the coordinates of every cell in the design area", "Putting a chip on a board", "Filling a job position", "Scheduling a meeting"),
  q("What is 'Clock Gating'?", "A technique to reduce power by disabling the clock to inactive modules", "Closing a gate", "A type of error", "Speeding up the clock"),
  q("What is 'Multi-Corner Multi-Mode' (MCMM) analysis?", "Checking timing across different manufacturing processes and operating conditions", "A game mode", "Calculating four corners of a chip", "Using many computers"),
  q("What is 'Parasitic Extraction'?", "Calculating the unwanted resistance and capacitance of the interconnects", "Removing bugs from a chip", "Taking data from a user", "Retrieving a wafer"),
  q("What is 'DRC' (Design Rule Check)?", "Verifying the layout follows fabrication rules (e.g., min width)", "Checking code logic", "Testing the chip", "A type of simulation"),
  q("What is 'LVS' (Layout Versus Schematic)?", "Matching the physical layout with the logical circuit diagram", "Comparing two chips", "A type of voltage test", "A naming convention"),
  q("What is 'Fill' in layout?", "Adding dummy metal or poly to ensure uniform density for manufacturing", "Filling a cup", "Filling a database", "Adding more data"),
  q("What is 'Guard Ring'?", "A structure used to isolate sensitive circuits from noise or latch-up", "A ring of fire", "A security fence", "A type of wedding ring"),
  q("What is 'DFT' (Design for Testability)?", "Adding features to the design to make it easier to test after manufacturing", "Designing for the future", "A type of simulation", "A software library"),
  q("What is 'BIST' (Built-in Self-Test)?", "A mechanism that allows a chip to test itself", "A type of breakfast", "A fast computer", "A group of testers"),
  q("What is 'IO Pad'?", "The circuitry used to interface the internal logic with external pins", "A tablet for input", "A landing spot for robots", "A cleaning cloth"),
  q("What is 'Thermal Throttling'?", "Reducing speed to prevent the chip from overheating", "A type of heating", "Stopping the factory", "A cooling fan")
];

export const vlsiL3: SampleQuestion[] = [
  q("What is 'FinFET' architecture?", "A 3D transistor design where the channel is a thin 'fin' of silicon", "A transistor with fins for cooling", "A very fast chip", "A type of underwater sensor"),
  q("What is 'EUV' lithography?", "Extreme Ultraviolet lithography - using very short wavelengths for sub-7nm nodes", "A new EU regulation", "A high-speed camera", "A type of solar power"),
  q("What is 'High-K Metal Gate' (HKMG)?", "Using materials with high dielectric constants and metal gates to reduce leakage", "A very expensive gate", "A type of heavy metal", "A high voltage terminal"),
  q("In the context of 'Yield', what is 'Binning'?", "Sorting chips based on their achieved frequency and power characteristics", "Throwing away broken chips", "Recycling wafers", "A way to pack chips"),
  q("What is 'DVFS' (Dynamic Voltage and Frequency Scaling)?", "Adjusting voltage and speed on the fly to optimize power/performance", "A type of file system", "A fast data bus", "A security protocol"),
  q("What is '3D IC' / 'TSV'?", "Stacking chips vertically and connecting them with Through-Silicon Vias", "A 3D movie about chips", "A very thick wafer", "A type of cooling"),
  q("What is 'NBTI' (Negative Bias Temperature Instability)?", "A reliability issue where PMOS transistor threshold voltage shifts over time", "A bad mood in the lab", "A type of temperature sensor", "A cooling failure"),
  q("What is 'Formal Verification'?", "Using mathematical proofs to ensure the design matches the specification", "A formal meeting", "Checking the paperwork", "A type of simulation"),
  q("What is 'Single Event Upset' (SEU)?", "A state change in a circuit caused by ionizing radiation", "A sad day for a designer", "A single bug in code", "A one-time event"),
  q("What is 'Machine Learning in EDA'?", "Using AI to optimize placement, routing, or timing closure", "Teaching a computer to build chips", "Buying an AI chip", "Automating the office"),
  q("What is 'System on Chip' (SoC)?", "An integrated circuit that integrates all components of a computer", "A chip for a system", "A single chip", "A motherboard"),
  q("What is 'Intellectual Property' (IP) Core?", "A reusable unit of logic or cell layout that is the product of one party", "The brain of a chip", "A type of law", "A secret code"),
  q("What is 'Hardware Trojan'?", "A malicious modification of an integrated circuit", "A virus on the computer", "A wooden robot", "A type of security software"),
  q("What is 'Physical Unclonable Function' (PUF)?", "A physical entity that provides a unique finger-print for a chip", "A function that cannot be copied", "A type of encryption", "A specialized transistor"),
  q("What is 'Signal Integrity' crosstalk noise?", "Unwanted signal on one wire caused by transition of a nearby wire", "Too many people talking", "A noisy fan", "A wireless signal interference"),
  q("What is 'Negative Slack'?", "When a signal arrives later than the required time (timing violation)", "A very slow signal", "A type of error", "A mistake in the calendar"),
  q("What is 'Sign-off'?", "The final verification stage before the design is sent to the foundry", "Signing a contract", "Closing the office", "The end of a simulation"),
  q("What is 'OCV' (On-Chip Variation)?", "Variations in process, voltage, or temperature across a single die", "A visual inspection", "A type of camera", "A local error"),
  q("What is 'AOCV' (Advanced OCV)?", "A more accurate variation modeling that accounts for path depth/location", "A better camera", "An advanced version of a chip", "A type of software"),
  q("What is 'Liberty (.lib)' file?", "The file used to describe the timing, power, and area of cells", "A file about freedom", "A type of library", "A database record"),
  q("What is 'SPEF'?", "Standard Parasitic Exchange Format - used to transfer parasitic data", "A file for images", "A special effect", "A communication code"),
  q("What is 'UPF' (Unified Power Format)?", "A standard for describing power intent (power domains, level shifters)", "A power supply unit", "A type of battery", "A electricity bill"),
  q("What is 'Level Shifter'?", "A circuit that translates signals between different voltage domains", "Moving to a new level", "A type of elevator", "A gear in a car"),
  q("What is 'Isolation Cell'?", "A cell used to ensure signals stay at valid logic levels when a power domain is OFF", "A prison cell", "A small room", "A protective layer"),
  q("What is 'Reticle'?", "The master copy of the IC layout used in photolithography", "A type of lens", "A target on a screen", "A cleaning tool"),
  q("What is 'CMP' (Chemical Mechanical Polishing)?", "A process of flattening the wafer surface using chemicals and abrasives", "Polishing the computer case", "A type of chemistry test", "Cleaning the wafer"),
  q("What is 'Step-and-Repeat'?", "The process of exposing the same pattern multiple times across the wafer", "A dance move", "A loop in code", "A manual process"),
  q("What is 'Yield Enhancement'?", "Techniques used to increase the percentage of working chips on a wafer", "Making more money", "Speeding up the factory", "Improving the design"),
  q("What is 'Multi-Patterning'?", "Using multiple masks to print features that are too close for a single mask", "Drawing with many pens", "A type of fabric", "A complex simulation"),
  q("What is 'Heterogeneous Integration'?", "Combining different types of chips (e.g. analog, digital, memory) into one package", "Using different materials", "A mix of everything", "A complex system")
];

export const computerArchL2: SampleQuestion[] = [
  q("What is the primary difference between 'RISC' and 'CISC'?", "RISC has simple, uniform instructions; CISC has complex, variable-length instructions", "RISC is faster; CISC is slower", "RISC is for mobile; CISC is for desktop", "RISC is old; CISC is new"),
  q("What is 'Cache Coherency'?", "Ensuring that all processors in a multicore system see the most recent data", "Making the cache faster", "Cleaning the cache", "Organizing the cache memory"),
  q("What is 'Virtual Memory' Page Fault?", "An interrupt raised when a program accesses a page not currently in RAM", "A broken hard drive", "A type of software error", "A missing file"),
  q("Which strategy is used for 'Write-Through' cache?", "Updating both the cache and the main memory simultaneously", "Updating only the cache", "Updating memory after a delay", "Deleting the data"),
  q("What is 'Branch Prediction'?", "Guessing the outcome of a conditional branch to avoid pipeline stalls", "Predicting the weather", "Guessing the next user input", "Estimating variable values"),
  q("What does 'SIMD' stand for?", "Single Instruction, Multiple Data - used in parallel processing", "Simple Internal Memory Device", "Signal Integrated Modern Driver", "System Internal Metadata"),
  q("What is 'Speculative Execution'?", "Executing instructions before it is known if they are actually needed", "Guessing how many instructions are left", "A type of high-speed gaming", "Executing code after an error"),
  q("What is 'Memory Latency'?", "The time elapsed between a memory request and the data becoming available", "The size of the memory", "The speed of the processor", "The price of a RAM stick"),
  q("Which replacement policy is common for caches?", "LRU (Least Recently Used)", "Random", "FIFO (First In First Out)", "Alphabetic"),
  q("What is 'Out-of-Order Execution'?", "Executing instructions in an order different from the program to maximize efficiency", "A broken computer", "Executing instructions backwards", "Running two programs at once"),
  q("What is 'Data Hazard' in pipelining?", "When an instruction depends on the result of a previous instruction still in the pipeline", "Losing data from the hard drive", "A type of software bug", "A security risk"),
  q("What is 'Control Hazard'?", "When the pipeline doesn't know which instruction to fetch next due to a branch", "Losing control of the computer", "A faulty power button", "A type of crash"),
  q("What is 'Structural Hazard'?", "When two instructions need the same hardware resource at the same time", "The computer case breaking", "A type of virus", "A design flaw"),
  q("What is 'Microarchitecture'?", "The specific hardware implementation of an Instruction Set Architecture (ISA)", "A very small building", "A type of software architecture", "Designing tiny chips"),
  q("What is 'Instruction Throughput'?", "The number of instructions completed per unit of time", "The size of an instruction", "The speed of light", "The number of bits used"),
  q("What is 'Load-Store' architecture?", "An ISA where memory access is only allowed through specific load and store instructions", "A warehouse for computers", "A type of database", "A shopping website"),
  q("What is 'TLB' (Translation Lookaside Buffer)?", "A cache that stores recent virtual-to-physical address translations", "A table of bank records", "A type of CPU register", "A memory on the cloud"),
  q("What is 'Page Table'?", "A data structure used by a virtual memory system to store the mapping between virtual and physical addresses", "A table in a book", "A part of a spreadsheet", "A list of websites"),
  q("What is 'DMA' (Direct Memory Access)?", "A feature that allows hardware to access memory without the CPU", "Fast memory access", "Double memory allocation", "Directing memory to apps"),
  q("What is 'IRQ' (Interrupt Request)?", "A hardware signal sent to the CPU to get its attention", "A question about code", "A type of error log", "A power failure"),
  q("What is 'Hyper-threading' (Simultaneous Multithreading)?", "Executing two threads on a single physical core by sharing resources", "Executing code very fast", "Using many computers at once", "A type of internet speed"),
  q("What is 'Uniform Memory Access' (UMA)?", "A shared memory architecture where access time is equal for all memory locations", "All memory is the same size", "A memory that never changes", "A type of local storage"),
  q("What is 'Non-Uniform Memory Access' (NUMA)?", "A design where memory access time depends on the memory location relative to the processor", "Variable speed RAM", "A type of random memory", "A cloud storage"),
  q("What is 'Vector Processor'?", "A CPU designed to perform operations on large arrays of data in a single instruction", "A processor that draws shapes", "A high-speed graphics card", "A type of mathematics tool"),
  q("What is 'Super-scalar' architecture?", "A CPU that can execute more than one instruction per clock cycle", "A very large computer", "A processor with many cores", "A type of measurement"),
  q("What is 'Bus Master'?", "An entity on the bus that can initiate a data transfer", "The boss of the office", "A type of hardware driver", "A primary power cable"),
  q("What is 'Latency' vs 'Bandwidth'?", "Latency is delay; Bandwidth is total capacity", "They are same", "Latency is better", "Bandwidth is for internet only"),
  q("What is 'Register Renaming'?", "A technique used to avoid false data dependencies between instructions", "Changing the name of a file", "Registering a new user", "A type of memory segment"),
  q("What is 'Execution Wall'?", "The limit on speed improvement due to the need for sequential execution", "A physical wall in a lab", "A type of security software", "A crash on startup"),
  q("What is 'Dark Silicon'?", "Transistors that cannot be powered on simultaneously due to thermal limits", "A black computer case", "Hidden data", "A type of broken chip")
];

export const computerArchL3: SampleQuestion[] = [
  q("Which of these is a typical solution for the 'Memory Wall' problem?", "Stacked High-Bandwidth Memory (HBM)", "Using larger hard drives", "Increasing clock speed indefinitely", "Adding more fans"),
  q("What does 'Amdahl's Law' primarily predict?", "The maximum theoretical speedup of a program using multiple processors", "The number of transistors on a chip", "The power consumption of a CPU", "The size of the internet"),
  q("In the 'MESI' protocol, what does the 'E' stand for?", "Exclusive - data is in only this cache and matches memory", "Error", "Empty", "External"),
  q("What is 'Tournament Branch Prediction'?", "Combining multiple predictors and choosing the best one for the current situation", "A game between computers", "Predicting the winner of a race", "Evaluating the speed of a CPU"),
  q("Which mechanism is used in 'Spectre' and 'Meltdown' vulnerabilities?", "Exploiting speculative execution to leak data via side channels", "Directly stealing passwords from the screen", "Breaking the physical chip", "Sending too many emails"),
  q("What is 'VLIW' (Very Long Instruction Word)?", "An architecture where the compiler groups multiple independent operations into a single long instruction", "A very long sentence", "A big database record", "A high-speed network cable"),
  q("What is 'Directory-based' cache coherence?", "Using a centralized table to keep track of sharing across many nodes/cores", "A file explorer for memory", "Organizing files into folders", "A type of cloud storage"),
  q("What is 'Transactional Memory'?", "Allowing groups of memory operations to execute atomically, similar to database transactions", "Buying memory online", "Moving data between banks", "A type of logging"),
  q("What is 'Near-Memory Computing'?", "Moving computation closer to where the data is stored to reduce data movement", "Using a laptop in a library", "A local area network", "Placing the CPU near the wall"),
  q("What is 'Roofline Model'?", "A performance model used to identify if a program is memory-bound or compute-bound", "A model of a house", "A type of sky-high gaming", "A graph of power usage"),
  q("What is 'Instruction Fusion'?", "Combining multiple simple instructions into a single complex micro-op", "Melting the processor", "Merging two programs", "A type of data compression"),
  q("What is 'Memory Consistency Model'?", "A set of rules defining the order in which memory updates become visible to other processors", "Making sure the RAM is clean", "A type of software update", "Matching the motherboard"),
  q("What is 'Deadlock' in a multicore system?", "A situation where two or more processes are blocked forever, waiting for each other", "A broken lock", "The end of a program", "A type of security alert"),
  q("What is 'Fetch, Decode, Execute' cycle?", "The basic operation cycle of a computer", "A type of sports exercise", "Moving data around the world", "A software development model"),
  q("What is 'Uop' (Micro-operation)?", "A simple instruction that the CPU actually executes after translating complex ones", "A small sound", "A type of app", "A database query"),
  q("What is 'Reservation Station'?", "A buffer that holds instructions and their operands in out-of-order execution", "A place to book a ticket", "A type of computer desk", "A software waiting room"),
  q("What is 'Reorder Buffer' (ROB)?", "A structure that allows instructions to be committed in their original program order", "Sorting files", "A type of stack", "A memory cleaner"),
  q("What is 'Unified Cache'?", "A cache that stores both instructions and data", "A shared folder", "A group of computers", "A type of browser cache"),
  q("What is 'Split Cache'?", "Separate caches for instructions and data", "A broken memory", "Two different computers", "A shared database"),
  q("What is 'Write-Back' cache?", "Data is written to cache and only written to main memory when the block is replaced", "Writing a letter", "Sending an email back", "Saving a file to disk"),
  q("What is 'Memory interleaving'?", "Arranging memory into multiple banks to allow simultaneous access", "Mixing two books", "A way to weave wires", "A type of data encoding"),
  q("What is 'Translation Lookaside Buffer' (TLB) miss?", "When a virtual-to-physical mapping is not in the TLB", "Losing a game", "A type of software error", "A missing link"),
  q("What is 'Interrupt Vector Table'?", "A table that maps interrupt signals to their handling routines", "A list of directions", "A type of spreadsheet", "A math matrix"),
  q("What is 'Bus Arbitration'?", "The process of deciding which device gets control of the bus", "A legal case for computers", "Selecting a driver", "A type of signal test"),
  q("What is 'Southbridge' in a chipset?", "The chip that handles slower I/O (like USB, SATA)", "A bridge in a city", "A type of cooling fan", "A software library"),
  q("What is 'Northbridge' in a chipset?", "The chip that handles high-speed communication between CPU, RAM, and GPU", "A bridge to the north", "A type of memory stick", "A primary power unit"),
  q("What is 'ECC' memory?", "Error-Correcting Code memory - can detect and fix data corruption", "Extra Cold Cooling", "Efficient Code Creator", "Everywhere Connected Computer"),
  q("What is 'Cold Boot'?", "Starting a computer from a powered-off state", "Booting in the winter", "A type of software update", "A slow computer"),
  q("What is 'Warm Boot'?", "Restarting a computer without cutting the power", "A fast computer", "A type of heating", "Using the computer a lot"),
  q("What is 'Bottleneck' in computer systems?", "A component that limits the overall performance of the system", "A part of a bottle", "A type of container", "A security risk")
];

export const pcbDesignL2: SampleQuestion[] = [
  q("What is the primary reason for using 'Differential Pairs'?", "Canceling electromagnetic interference (EMI) and improving high-speed signal integrity", "Doubling the current", "Providing a backup path", "Saving space"),
  q("What is 'Crosstalk' in PCB design?", "Unwanted signal coupling between two adjacent tracks", "Communication between designers", "A type of noise in the lab", "Signal loss over distance"),
  q("Why is a 'Ground Plane' essential in multi-layer PCBs?", "Providing a low-impedance return path and reducing EMI", "Keeping the board flat", "Adding more weight", "Connecting all components to battery"),
  q("What is 'Thermal Relief'?", "A connection to a copper plane with small traces to prevent heat sinking during soldering", "A fan for the board", "A cooling system", "A type of insulation"),
  q("Which file is used specifically for automated component placement?", "Pick and Place file / Centroid file", "Gerber file", "Schematic", "BOM"),
  q("What is 'Aspect Ratio' of a via?", "The ratio of board thickness to the via hole diameter", "The width to height ratio of the board", "The number of vias per square inch", "The price vs quality"),
  q("What is 'Characteristic Impedance' (Z0)?", "The uniform resistance to a signal along a transmission line", "The total weight of the board", "The maximum voltage allowed", "A type of internal battery"),
  q("Why is 'Solder Paste' applied through a stencil?", "To ensure consistent and accurate amount of solder on the pads", "To clean the board", "To add colors", "To hide errors"),
  q("What is the purpose of 'Guard Traces'?", "Grounded traces placed between sensitive signals to reduce crosstalk", "Traces that protect from physical damage", "Secret wires", "High-power connections"),
  q("What is 'Signal Integrity' (SI)?", "A set of measures of the quality of an electrical signal", "The honesty of the signal", "A type of encryption", "The speed of the clock"),
  q("What is 'Power Integrity' (PI)?", "Ensuring that the power and ground planes provide stable voltage to components", "The honesty of the power supply", "The total power capacity", "A measure of energy efficiency"),
  q("What is 'Stackup'?", "The arrangement of copper and insulating layers in a multi-layer PCB", "A pile of boards", "A type of software error", "A manufacturing delay"),
  q("What is 'Annular Ring'?", "The area of copper pad remaining around a drilled via hole", "A wedding ring", "A type of capacitor", "A circle around a component"),
  q("What is 'Clearance'?", "The minimum distance between two copper features", "Clearing the work area", "Removing short circuits", "Deleting traces"),
  q("What is 'Creepage'?", "The shortest path between two conductive parts along the surface of an insulator", "A bug on the board", "A slow movement of a wire", "A type of signal noise"),
  q("What is 'Trace Width'?", "The width of a copper connection", "The length of a wire", "The thickness of the copper", "The speed of the signal"),
  q("What is 'Trace Thickness' (Copper weight)?", "The amount of copper per square foot (e.g. 1oz)", "The width of the wire", "The color of the copper", "The price of the material"),
  q("What is 'Blind Via'?", "A via that connects an outer layer to an inner layer only", "A via you can't see", "A broken via", "A via for power only"),
  q("What is 'Buried Via'?", "A via that connects two inner layers only", "A via hidden under a component", "An expensive via", "A grounding via"),
  q("What is 'Microvia'?", "A very small via, often laser-drilled, used in High-Density Interconnect (HDI) boards", "A via for a microscope", "A tiny hardware component", "A software bug"),
  q("What is 'Panelization'?", "Grouping multiple small PCBs onto a larger board for manufacturing", "Building a control panel", "Adding a frame", "A type of software"),
  q("What is 'BOM' (Bill of Materials)?", "A complete list of components required for the board", "A dangerous object", "Board of Management", "Base Output Message"),
  q("What is 'Design for Manufacturing' (DFM)?", "Adjusting the design to make production easier and cheaper", "Designing to looks good", "A type of simulation", "A manufacturing plan"),
  q("What is 'Design for Assembly' (DFA)?", "Adjusting the design to make component mounting easier", "Designing for a meeting", "A specialized team", "A software tool"),
  q("What is 'Design for Test' (DFT)?", "Adding test points to make it easier to verify the board after assembly", "Designing for the future", "A type of simulation", "A software library"),
  q("What is 'Reflow Oven'?", "A machine used to melt solder paste and create joints", "A kitchen appliance", "A cooling device", "A database server"),
  q("What is 'Wave Soldering'?", "A bulk soldering process for through-hole boards", "Soldering in the ocean", "Fast soldering", "A manual process"),
  q("What is 'Silk Screen'?", "The text and graphics printed on a PCB for identification", "A screen for filtering noise", "A cleaning tool", "A type of fabric"),
  q("What is 'Solder Mask'?", "The protective layer that covers copper traces (usually green)", "A mask for the designer", "A cleaning tool", "A type of glue"),
  q("What is 'Copper Pour'?", "A large solid area of copper, often used for grounding", "Adding more copper by hand", "Cleaning the copper", "A type of wire")
];

export const pcbDesignL3: SampleQuestion[] = [
  q("What is 'Length Matching' used for in high-speed buses like DDR?", "Ensuring signals arrive at the destination at exactly the same time to avoid skew", "Making the board look neat", "Providing equal resistance", "Saving material"),
  q("What is 'EMI' (Electromagnetic Interference) shielding?", "Using metal cages or planes to block unwanted radio frequency signals", "Blocking the wind", "Protecting from sunlight", "A type of password"),
  q("Which material is better for 'High Frequency' / RF PCBs compared to FR-4?", "Rogers / PTFE", "Aluminum", "Lead", "Wood"),
  q("What is 'Fiducial Mark' and why are they placed far apart?", "Reference points for optical alignment during assembly; distance improves rotational accuracy", "A company logo; spacing looks better", "Test points; distance prevents shorts", "Manufacturing markers; spacing is random"),
  q("In 'Power Integrity' (PI), what is a 'Decoupling Capacitor's' primary role?", "Providing a localized reservoir of energy for high-speed switching and filtering noise", "Disconnecting the battery", "Coupling two circuits", "Measuring voltage"),
  q("What is 'High-Density Interconnect' (HDI)?", "A PCB with higher wiring density per unit area than conventional boards", "A very fast internet connection", "A dense group of people", "A type of hard drive interface"),
  q("What is 'TDR' (Time Domain Reflectometry)?", "A technique used to measure characteristic impedance and find discontinuities in traces", "A speedometer for robots", "A clock on the wall", "A type of database query"),
  q("What is 'Signal Skew'?", "The difference in time of arrival of bits of a parallel bus", "A blurry signal", "A signal that moves left", "A type of error log"),
  q("What is 'Stubs' in high-speed routing?", "An unused branch of a trace that causes reflections and signal degradation", "A part of a ticket", "A short wire", "A type of connector"),
  q("What is 'Termination Resistor'?", "A resistor used at the end of a transmission line to prevent reflections", "A resistor that stops the board", "A type of fuse", "A way to end a project"),
  q("What is 'Daisy Chain' routing?", "A wiring scheme where components are connected one after the other in a sequence", "A chain made of flowers", "A type of decoration", "A parallel connection"),
  q("What is 'Fly-by' topology?", "A routing topology used in DDR3 memory to improve signal integrity across many chips", "Routing while flying", "A fast way to draw traces", "A type of bird-like robot"),
  q("What is 'V-Groove' / 'V-Scoring'?", "A cut into the board to allow easy snapping of panels", "A musical term", "A type of wire", "A software bug"),
  q("What is 'Tab Routing'?", "Connecting boards in a panel with small tabs of material", "A way to organize web tabs", "A type of network router", "A keyboard shortcut"),
  q("What is 'Immersion Gold' (ENIG)?", "A type of surface finish for PCBs consisting of electroless nickel covered with gold", "A gold medal", "Adding gold to the board by hand", "A cleaning process"),
  q("What is 'HASL' (Hot Air Solder Leveling)?", "A common surface finish involving dipping the board in molten solder and blowing off excess", "A fast computer", "A type of heating system", "A manual soldering iron"),
  q("What is 'Silver Finish'?", "A surface finish using silver, good for high-frequency boards", "A second-place medal", "Adding silver to the office", "A type of plating"),
  q("What is 'OSHP' (Organic Solderability Preservative)?", "A thin organic coating to protect copper from oxidation until soldering", "A type of ship", "A safety protocol", "A cleaning tool"),
  q("What is 'Via-in-Pad' technology?", "Placing a via directly in the SMT pad to save space (requires specialized filling)", "A via inside a laptop", "A broken pad", "An expensive manufacturing trick"),
  q("What is 'Parasitic Inductance'?", "Unwanted inductance inherent in traces and component leads", "A type of insect", "A ghost in the machine", "A measure of power"),
  q("What is 'Eye Diagram'?", "An oscilloscope display used to analyze high-speed signal quality and jitter", "A diagram of a human eye", "A way to look at the board", "A type of chart for sales"),
  q("What is 'Jitter'?", "The deviation from true periodicity of a periodic signal", "A nervous feeling", "A type of fast motion", "A software lag"),
  q("What is 'Bit Error Rate' (BER)?", "The number of bit errors per unit time", "A type of bear", "A measure of speed", "A database record"),
  q("What is 'Insertion Loss'?", "The loss of signal power resulting from the insertion of a component or trace", "Losing a part during assembly", "A type of error log", "A power failure"),
  q("What is 'Return Loss'?", "A measure of how much signal is reflected back toward the source", "Losing a customer", "A financial term", "A type of data signal"),
  q("What is 'Differential Impedance'?", "The impedance seen between two traces of a differential pair", "Two different impedances", "A complex math formula", "A type of signal noise"),
  q("What is 'Common Mode' noise?", "Noise that appears on both lines of a differential pair in the same phase", "Noise shared by everyone", "A type of ordinary sound", "A standard database error"),
  q("What is 'Backdrilling'?", "Removing the unused part of a plated-through hole to reduce stubs", "Drilling from the back of the room", "A manual hardware repair", "A type of simulation"),
  q("What is 'Buried Resistance'?", "A resistor formed directly on the internal layers of a PCB", "A secret resistance", "A type of component", "A buried cable"),
  q("What is 'Embedded Capacitance'?", "Using thin dielectric layers between power and ground to create large-scale capacitance", "A capacitor hidden inside a chip", "A type of storage", "A battery built into the board")
];


