import { type SampleQuestion } from "./sample-questions";

const q = (question_text: string, correct: string, wrong1: string, wrong2: string, wrong3: string): SampleQuestion => ({
  question_text,
  options: [
    { text: correct, is_correct: true },
    { text: wrong1, is_correct: false },
    { text: wrong2, is_correct: false },
    { text: wrong3, is_correct: false },
  ].sort(() => Math.random() - 0.5),
  marks: 1,
});

export const javaL1: SampleQuestion[] = [
  q("Which keyword is used to define a class in Java?", "class", "struct", "define", "object"),
  q("What is the default value of an int variable in Java?", "0", "null", "1", "undefined"),
  q("Which method is the entry point of a Java program?", "main()", "start()", "run()", "init()"),
  q("Which of the following is not a primitive data type in Java?", "String", "int", "boolean", "char"),
  q("What does JVM stand for?", "Java Virtual Machine", "Java Variable Method", "Java Verified Machine", "Java Visual Method"),
  q("Which operator is used for string concatenation?", "+", "&", ".", ","),
  q("What is the size of int in Java?", "4 bytes", "2 bytes", "8 bytes", "1 byte"),
  q("Which keyword prevents a class from being inherited?", "final", "static", "private", "abstract"),
  q("What is the parent class of all Java classes?", "Object", "Class", "Main", "Base"),
  q("Which keyword is used to create an object?", "new", "create", "make", "init"),
  q("Which access modifier makes a member accessible only within the same class?", "private", "public", "protected", "default"),
  q("What is method overloading?", "Same method name with different parameters", "Overriding parent methods", "Creating abstract methods", "Using static methods"),
  q("Which collection class allows duplicate elements?", "ArrayList", "HashSet", "TreeSet", "HashMap"),
  q("What does the 'static' keyword mean in Java?", "Belongs to the class, not instance", "Cannot be changed", "Accessible everywhere", "Runs at startup"),
  q("What does the 'super' keyword do?", "Refers to parent class", "Refers to current class", "Creates superclass", "Imports parent"),
  q("Which class is used to read input from the user?", "Scanner", "Reader", "Input", "Console"),
  q("What is an abstract class?", "A class that cannot be instantiated", "A class with only static methods", "A final class", "An interface"),
  q("Which keyword is used for exception handling?", "try", "handle", "error", "except"),
  q("What is the purpose of the 'finally' block?", "Always executes after try-catch", "Handles exceptions", "Defines constants", "Ends the program"),
  q("Which collection uses key-value pairs?", "HashMap", "ArrayList", "LinkedList", "HashSet"),
  q("What is a constructor?", "Special method called during object creation", "A static method", "A destructor", "An interface method"),
  q("What does 'break' do in a loop?", "Exits the loop", "Skips to next iteration", "Pauses execution", "Restarts the loop"),
  q("Which type of inheritance is not supported in Java (for classes)?", "Multiple", "Single", "Multilevel", "Hierarchical"),
  q("What is garbage collection?", "Automatic memory management", "Deleting source files", "Removing comments", "Clearing the console"),
  q("What is the output of 10 % 3?", "1", "3", "0", "10"),
  q("Which keyword makes a variable constant?", "final", "const", "static", "immutable"),
  q("What is an interface in Java?", "A contract with abstract methods", "A concrete class", "A data type", "A package"),
  q("Which method converts a string to an integer?", "Integer.parseInt()", "String.toInt()", "Int.parse()", "Convert.toInteger()"),
  q("What does the 'instanceof' operator do?", "Checks if an object is of a specific type", "Creates an instance", "Compares values", "Copies an object"),
  q("Which package is automatically imported?", "java.lang", "java.util", "java.io", "java.net")
];

export const pythonL1: SampleQuestion[] = [
  q("Which function is used to print output in Python?", "print()", "echo()", "write()", "output()"),
  q("How do you start a comment in Python?", "#", "//", "/*", "--"),
  q("Which keyword defines a function in Python?", "def", "function", "func", "define"),
  q("What is the output of type(5)?", "<class 'int'>", "integer", "number", "int"),
  q("Which data structure uses key-value pairs?", "Dictionary", "List", "Tuple", "Set"),
  q("What does len() function do?", "Returns length", "Returns last element", "Lengthens a string", "Returns type"),
  q("Python is which type of language?", "Interpreted", "Compiled", "Assembly", "Machine"),
  q("Which of these is immutable?", "Tuple", "List", "Dictionary", "Set"),
  q("What is the result of 3 ** 2?", "9", "6", "5", "8"),
  q("Which keyword is used for loops in Python?", "for", "loop", "each", "iterate"),
  q("What does 'pip' stand for?", "Pip Installs Packages", "Python Install Program", "Package Import Protocol", "Python Interface Platform"),
  q("Which method adds an element to the end of a list?", "append()", "add()", "insert()", "push()"),
  q("What is a lambda function?", "An anonymous function", "A named function", "A class method", "A module"),
  q("How do you create a virtual environment?", "python -m venv env", "python create env", "pip install venv", "virtualenv --start"),
  q("What does 'self' refer to in a class?", "The current instance", "The parent class", "A static variable", "The module"),
  q("Which exception handles division by zero?", "ZeroDivisionError", "ValueError", "TypeError", "ArithmeticError"),
  q("What is list comprehension?", "A concise way to create lists", "A sorting algorithm", "A type of loop", "A module import"),
  q("Which keyword is used for inheritance?", "class Child(Parent):", "class Child extends Parent:", "class Child inherits Parent:", "class Child << Parent:"),
  q("What does the 'with' statement do?", "Context management for resources", "Creates a loop", "Defines a function", "Imports a module"),
  q("How do you handle exceptions in Python?", "try/except", "try/catch", "try/handle", "begin/rescue"),
  q("What is a decorator in Python?", "A function that modifies another function", "A class attribute", "A loop construct", "A variable type"),
  q("Which method removes whitespace from both ends of a string?", "strip()", "trim()", "clean()", "remove()"),
  q("What is the difference between '==' and 'is'?", "'==' compares values, 'is' compares identity", "They are identical", "'is' compares values, '==' compares identity", "'is' is for strings only"),
  q("Which built-in function returns the largest item?", "max()", "largest()", "big()", "top()"),
  q("What does the 'yield' keyword do?", "Creates a generator", "Returns a value and exits", "Raises an exception", "Imports a module"),
  q("How do you open a file for reading?", "open('file.txt', 'r')", "read('file.txt')", "file.open('r')", "open('file.txt', 'read')"),
  q("What is a module in Python?", "A file containing Python code", "A type of variable", "A loop construct", "A data type"),
  q("Which data type is ordered and changeable?", "List", "Tuple", "Set", "Frozenset"),
  q("What does the map() function do?", "Applies a function to each item in an iterable", "Creates a dictionary", "Maps keys to values", "Draws a map"),
  q("What is the output of bool('')?", "False", "True", "None", "Error")
];

export const javaL2: SampleQuestion[] = [
  q("What is the difference between 'ArrayList' and 'LinkedList'?", "ArrayList uses a dynamic array; LinkedList uses a doubly linked list", "No difference", "ArrayList is faster for updates", "LinkedList is faster for random access"),
  q("What is the 'Reflection' API in Java?", "Allows a program to inspect/modify its own behavior at runtime", "A way to mirror objects", "A type of UI toolkit", "A database connector"),
  q("What is the use of 'volatile' keyword?", "Ensures that a variable is always read from/written to main memory (not CPU cache)", "Makes variable constant", "Deletes variable", "Thread-safe only for writes"),
  q("What is 'Serialization'?", "Converting an object state into a byte stream", "Sorting objects", "Grouping classes", "Saving to XML"),
  q("What is a 'ClassLoader'?", "The part of JRE that loads Java classes into the JVM", "A way to download jars", "A type of constructor", "A security manager"),
  q("What is 'Synchronization' in Java?", "Controlling access of multiple threads to shared resources", "Running code at same time", "Syncing database", "Updating UI"),
  q("What is the difference between 'HashMap' and 'Hashtable'?", "HashMap is non-synchronized and allows null; Hashtable is synchronized and no null", "They are identical", "Hashtable is faster", "HashMap is for integers only"),
  q("What is 'Garbage Collection' algorithms?", "Methods like G1, CMS used to reclaim memory", "Scripts for deleting files", "A way to clear console", "A type of loop"),
  q("What is 'JVM Heap' vs 'Stack'?", "Heap stores objects; Stack stores method local variables and call frames", "They are the same", "Stack is for objects", "Heap is for primitives"),
  q("What is 'Type Erasure' in Generics?", "The process where the compiler removes all information related to generic type parameters at runtime", "Deleting types", "Merging classes", "Changing variable names"),
  q("which keyword is used to call a parent constructor?", "super()", "parent()", "base()", "this()"),
  q("What is a 'Functional Interface'?", "An interface with exactly one abstract method", "An interface with only static methods", "A class with no methods", "A type of lambda"),
  q("What is 'Optional' class in Java 8?", "A container object which may or may not contain a non-null value", "A way to skip methods", "An optional parameter", "A type of array"),
  q("What is 'Stream API'?", "A sequence of elements supporting sequential and parallel aggregate operations", "A way to read files", "A database connection", "A networking tool"),
  q("What is 'Method Reference' (::)?", "A shorthand way to write a lambda expression to call an existing method", "Calling a static method", "Accessing a field", "A type of pointer"),
  q("What is 'Marker Interface'?", "An interface with no fields or methods (e.g., Serializable)", "A colored interface", "A way to bookmark code", "A high-priority interface"),
  q("What is 'Atomic' variable (e.g., AtomicInteger)?", "Variables that support lock-free thread-safe operations on single variables", "Small variables", "Variables that explode", "Constant variables"),
  q("What is 'Deadlock' in Java threads?", "A situation where two or more threads are blocked forever, waiting for each other", "A fast loop", "A crash", "A file lock"),
  q("What is 'CompletableFuture'?", "A way to perform asynchronous computations in Java", "A promise that never ends", "A type of thread pool", "A database task"),
  q("What is 'Lambda Expression'?", "A short block of code which takes in parameters and returns a value", "A type of variable", "A loop construct", "A class definition"),
  q("which method starts a thread?", "start()", "run()", "execute()", "init()"),
  q("What is the use of 'Transient' keyword?", "Specifies that a field should not be serialized", "Makes variable temporary", "Speeds up loading", "Makes field private"),
  q("What is 'Inner Class' in Java?", "A class defined within another class", "A class for internal use only", "A private class", "A static class"),
  q("What is 'Enum' in Java?", "A special data type that enables for a variable to be a set of predefined constants", "A number list", "A type of array", "A loop"),
  q("which package contains 'Collection' interface?", "java.util", "java.lang", "java.io", "java.net"),
  q("What is 'Generic' in Java?", "Allowing a type (class, interface, or method) to be a parameter to another type", "Standard code", "Common library", "A type of object"),
  q("What is 'Fail-Safe' iterator?", "An iterator that operates on a copy of the collection (e.g., CopyOnWriteArrayList)", "An iterator that doesn't crash", "A fast iterator", "A secure iterator"),
  q("What is 'Bounded Wildcard' in Generics?", "Using <? extends T> or <? super T> to restrict type parameters", "A limit for variables", "A way to catch errors", "A type of loop"),
  q("What is 'Double Brace Initialization'?", "A shorthand for creating and initializing an outer collection at the same time", "A type of error", "A security risk", "A fast way to load classes"),
  q("What is 'Project Loom' (experimental)?", "Introduction of virtual threads to Java", "A new UI framework", "A database engine", "A game engine")
];

export const javaL3: SampleQuestion[] = [
  q("What is 'G1 Garbage Collector'?", "A regionalized, parallel, and concurrent collector that meets soft real-time targets", "The first garbage collector", "A mobile game collector", "A type of RAM"),
  q("What is 'Java Memory Model' (JMM)?", "Specifies how threads interact through memory and what behaviors are allowed", "The size of RAM", "A type of memory chip", "A database schema"),
  q("What is 'Java Native Interface' (JNI)?", "Allows Java code to call or be called by native applications (C/C++)", "A new Java version", "A way to connect to databases", "A network interface"),
  q("What is 'JIT Compiler'?", "Just-In-Time compiler - compiles bytecode to native machine code at runtime", "A compiler that runs on its own", "A fast compiler for cloud", "A way to interpret code"),
  q("What is 'Phantom Reference'?", "A reference type that is eligible for GC but only after finishing finalized", "A ghost object", "A reference that doesn't exist", "A weak pointer"),
  q("What is 'Flyweight Pattern' in Java String?", "String interning to reuse equal strings to save memory", "A fast string", "A type of list", "A way to compress text"),
  q("What is 'PermGen' vs 'Metaspace' (Java 8+)?", "Metaspace replaced PermGen for storing class metadata, using native memory", "They are identical", "PermGen is larger", "Metaspace is for objects"),
  q("What is 'Happens-Before' relationship?", "A guarantee in JMM that memory writes by one statement are visible to another", "A type of timing attack", "A way to sort code", "A logical error"),
  q("What is 'Fork/Join' framework?", "An implementation of the ExecutorService for data-parallel tasks", "A way to join databases", "A type of branching", "A multi-threaded server"),
  q("What is 'Bytecode'?", "The intermediate representation of Java code between source and machine code", "A code with 8 bits", "A type of variable", "A security token"),
  q("What is 'AOT Compilation'?", "Ahead-of-Time compilation - compiling code to machine code before execution", "Always On Time", "Automatic Object Tracing", "A new Java feature"),
  q("What is 'Escape Analysis'?", "A technique used by JIT to determine if an object can be allocated on the stack instead of heap", "Analyzing code for bugs", "A security scan", "Memory leak detection"),
  q("What is 'VarHandle' (Java 9+)?", "A standard way to perform atomic operations and memory fencing", "A type of variable", "A GUI handle", "A database connection"),
  q("What is 'Modular System' (Project Jigsaw)?", "Breaking the JDK into modules for better performance and security", "A group of libraries", "A type of class", "A way to load jars"),
  q("What is 'Shenandoah GC'?", "A low-pause-time garbage collector that performs most GC work concurrently", "A high-performance file system", "A cloud manager", "A database collector"),
  q("What is 'ZGC'?", "A scalable low-latency garbage collector designed for large heaps", "The last letter in code", "A type of thread", "A security standard"),
  q("What is 'Stack Walking API'?", "Allows easy and efficient access to stack trace information", "A way to debug", "A type of iterator", "A UI component"),
  q("What is 'Direct Buffer' in NIO?", "A buffer whose memory is allocated outside of the garbage-collected heap", "A fast database cache", "A type of string", "A network packet"),
  q("What is 'Invokedynamic' instruction?", "Allows for more efficient implementation of dynamic languages on the JVM", "Calling a static function", "A way to speed up loops", "A security feature"),
  q("What is 'Compressed Oops'?", "Using 32-bit pointers for 64-bit JVMs to save memory (up to 32GB)", "A bug fix", "A tiny object", "Small binary files"),
  q("What is 'Biased Locking'?", "Optimization for uncontended synchronization by biasing the lock to the first thread", "A type of security", "A database lock", "A way to slow down threads"),
  q("What is 'TLAB' (Thread Local Allocation Buffer)?", "A region of Eden space dedicated to a single thread for faster allocation", "A thread's private memory", "A type of cache", "A database table"),
  q("What is 'WeakReference' vs 'SoftReference'?", "SoftReferences are cleared only when memory is low; WeakReferences are cleared on next GC", "They are the same", "Weak is better", "Soft is for images"),
  q("What is 'Method Handles' API?", "A typed, directly executable reference to an underlying method", "A pointer to a function", "A way to call private methods", "A UI component"),
  q("What is 'ServiceLoader'?", "A mechanism for loading service providers", "A type of server", "A constructor for components", "A network tool"),
  q("What is 'Primitive Specialization' in Streams?", "IntStream, LongStream etc. to avoid boxing costs", "Making primitives important", "A type of casting", "A new data type"),
  q("What is 'Custom Annotation'?", "Creating your own @interface to add metadata to code", "A color in the IDE", "A comment for developers", "A database tag"),
  q("What is 'Dynamic Proxy'?", "Creating proxy instances for interfaces at runtime", "A fast server", "A lightweight object", "A type of link"),
  q("What is 'Instrumentation' API?", "Allows agents to modify Java bytecode at runtime", "Measuring speed", "Adding logs", "Testing hardware"),
  q("What is 'Record' class in Java 16?", "A concise way to define immutable data carrier classes", "A database record", "A sound file", "A type of loop")
];

export const pythonL2: SampleQuestion[] = [
  q("What is the difference between 'range' and 'xrange' in Python 2 vs 3?", "Python 3 range is like Python 2 xrange (returns an iterator)", "No difference", "xrange is faster", "range is for lists only"),
  q("What is 'Monkey Patching'?", "Extending or modifying code at runtime", "A type of bug", "Grouping modules", "Deleting functions"),
  q("What is 'Duck Typing'?", "If it walks like a duck and quacks like a duck, it is a duck (focus on behavior over type)", "Typing very fast", "A type of error", "A data structure"),
  q("What is the use of '@property' decorator?", "To define a method that can be accessed like an attribute", "To make variable private", "To speed up code", "To encrypt data"),
  q("What is 'Meta-programming'?", "Writing code that generates or manipulates other code", "Programming for Facebook", "High-level design", "A type of loop"),
  q("What are '*args' and '**kwargs'?", "Variable number of positional and keyword arguments", "A type of error", "Mathematical operators", "Module imports"),
  q("What is a 'Generator'?", "A function that returns an iterator using 'yield'", "A power source", "A type of loop", "A class definition"),
  q("What is the difference between 'deepcopy' and 'copy'?", "deepcopy recursively copies all objects; copy only the top-level", "They are identical", "copy is safer", "deepcopy is for lists only"),
  q("What is 'GIL' (Global Interpreter Lock)?", "A mutex that protects access to Python objects, preventing multiple threads from executing simultaneously", "A file lock", "A network protocol", "A security license"),
  q("What is 'MRO' (Method Resolution Order)?", "The order in which Python searches for methods in classes during inheritance (C3 linearization)", "A type of list", "A loop direction", "A database schema"),
  q("What is 'Pickle' module used for?", "Serializing and de-serializing Python objects", "Preserving data", "Creating web pages", "Handling errors"),
  q("What is the use of 'asyncio' module?", "For writing single-threaded concurrent code using coroutines", "For audio files", "For database sync", "For UI events"),
  q("What is 'Context Manager' (with statement)?", "Ensures resources are properly released after use", "A way to group variables", "A type of function", "A library for context"),
  q("What is 'List Comprehension' vs 'Generator Expression'?", "List comprehension creates a list; generator expression returns an iterator", "They are the same", "Generator is for numbers only", "List is faster"),
  q("What is 'f-string'?", "Formatted string literals introduced in Python 3.6", "A fast string", "A type of list", "A security standard"),
  q("How do you handle multiple exceptions in one block?", "except (Error1, Error2):", "except Error1 and Error2:", "catch Error1, Error2:", "handle multiple"),
  q("What does 'itertools' provide?", "Functions creating iterators for efficient looping", "Tools for UI", "A type of database", "Mathematical functions"),
  q("What is 'Virtualenv' used for?", "Creating isolated Python environments", "Running virtual machines", "A type of web server", "Connecting to cloud"),
  q("What is 'Pylint'?", "A tool for static code analysis", "A new Python version", "A database driver", "A web framework"),
  q("What is the purpose of 'sys.path'?", "A list of strings that specifies the search path for modules", "The path to the system", "A variable for memory", "A loop array"),
  q("What is 'Namedtuple'?", "A factory function for creating tuple subclasses with named fields", "A type of string", "A database record", "A fast loop"),
  q("What does 'slots' attribute in a class do?", "Reduces memory footprint by avoiding __dict__ in instances", "Adds more space", "Defines methods", "A type of loop"),
  q("What is 'Abstract Base Class' (abc module)?", "A way to define interfaces in Python", "A base for all classes", "A type of variable", "A security module"),
  q("which method is called before __init__?", "__new__", "__start__", "__create__", "__pre__"),
  q("What is 'Weakref'?", "A reference to an object that does not prevent it from being garbage collected", "A broken link", "A pointer that doesn't work", "A small variable"),
  q("What is '@classmethod' vs '@staticmethod'?", "classmethod takes 'cls' as first argument; staticmethod takes no special first argument", "They are identical", "staticmethod is for numbers", "classmethod is for strings"),
  q("How do you make a variable 'private' in a Python class?", "Using double underscore prefix (__var)", "Using private keyword", "Using const", "Using #"),
  q("What is 'Multiple Inheritance'?", "A class inheriting from more than one parent class", "Inheriting many times", "A type of loop", "A design pattern"),
  q("What is the use of 'collections' module?", "Providing specialized container data types (Counter, OrderedDict, etc.)", "Grouping files", "Managing memory", "A database tool"),
  q("What is 'Walrus Operator' (:=)?", "Assigns values to variables as part of an expression", "A mathematical symbol", "A type of loop", "A way to name functions")
];

export const pythonL3: SampleQuestion[] = [
  q("What is a 'Metaclass'?", "A class whose instances are classes (defines how classes are created)", "A large class", "A type of data", "A database manager"),
  q("What is 'Cython'?", "A programming language that as a superset of Python designed to give C-like performance", "A person who codes in Python", "A tool for UI", "A web browser"),
  q("What is 'PyPy'?", "A fast, alternative implementation of Python with a JIT compiler", "A game library", "A type of loop", "A database tool"),
  q("How does Python's Garbage Collection work?", "Reference counting and a cycle-detecting generational collector", "It doesn't have one", "Only reference counting", "Manual memory management"),
  q("What is 'Memoryview'?", "A generalized protocol to share memory between data structures without copying", "Viewing RAM", "A type of list", "A server log"),
  q("What is 'Descriptor' protocol?", "Objects that define __get__, __set__, or __delete__ to customize attribute access", "A type of documentation", "A unique ID", "A loop construct"),
  q("What is 'Asynchronous Generator'?", "A generator that can yield values using await", "A fast power source", "A type of thread", "A database query"),
  q("What is 'Garbage Collection' Generation 0, 1, 2?", "Different lifespans of objects to optimize GC frequency", "Different versions of Python", "A type of memory segment", "A security standard"),
  q("What is the 'Frame' object?", "Representing the state of an execution context in a function call", "A window for UI", "A type of variable", "A database table"),
  q("What is 'Bytecode' in Python?", "The intermediate code generated by the compiler (.pyc files)", "Coding in binary", "A type of string", "A security token"),
  q("What is 'Global Namespace' vs 'Local Namespace'?", "Global is for the module; Local is for the function", "They are the same", "Global is for all modules", "Local is for variables"),
  q("What is 'Coroutines'?", "Generalizations of subroutines that can yield and resume control", "Small functions", "A type of thread", "A database task"),
  q("What is 'Unit Testing' (unittest/pytest)?", "Testing individual units of source code", "Testing the whole app", "Checking for errors manually", "A design pattern"),
  q("What is the use of '__dict__'?", "A dictionary used to store an object's (writable) attributes", "Counting variables", "A type of list", "A security feature"),
  q("What is 'Attribute Lookup' order?", "instance -> class -> base classes (MRO)", "class -> instance", "base -> class", "random order"),
  q("What is 'Buffer Protocol'?", "Allows a C-level access to the internal data of an object", "Handling internet buffer", "A type of loop", "A database cache"),
  q("What is the difference between 'threading' and 'multiprocessing'?", "Threading shares memory; Multiprocessing has separate memory and bypasses GIL", "They are the same", "Threading is for multi-core", "Multiprocessing is slower"),
  q("What is 'Data Classes' (Python 3.7+)?", "A decorator and module for automatically adding special methods to classes", "Classes that store data", "A type of database", "A security standard"),
  q("What is 'Type Hinting' (mypy)?", "Specifying expected data types for variables and functions", "A clue for developers", "A way to speed up code", "A database schema"),
  q("What is 'Abstract Syntax Tree' (AST)?", "A tree representation of the abstract syntactic structure of source code", "A tree in a game", "A type of variable", "A loop construct"),
  q("What is the purpose of 'weakref.proxy'?", "Creates a weak reference proxy to an object", "A secure proxy", "A database connection", "A type of link"),
  q("What is 'Concurrent.futures'?", "High-level interface for asynchronously executing callables", "Future of Python", "A way to group tasks", "A database protocol"),
  q("What is 'Profiling' (cProfile)?", "Measuring execution time and resource usage to find bottlenecks", "Creating user accounts", "A security scan", "Testing hardware"),
  q("What is 'Introspection'?", "The ability of an object to know about its own type and attributes at runtime", "Looking at the mirror", "Debugging manually", "A design pattern"),
  q("What is 'Closure' in Python?", "A function object that remembers values in enclosing scopes even if they are not present in memory", "Closing a file", "The end of a loop", "A type of data"),
  q("What is the difference between 'classmethod' and 'staticmethod' inheritance?", "classmethod can be overridden and receives the calling class as first argument", "No difference in inheritance", "staticmethod is for base classes only", "classmethod is for leaf classes"),
  q("What is 'Module Reloading' (importlib.reload)?", "Reloading a previously imported module", "Restarting the app", "Updating the database", "Clearing cache"),
  q("What is 'Namespace Packages'?", "A package that is spread across multiple directories", "A group of vars", "A type of link", "A security standard"),
  q("What is 'Taint Analysis'?", "Tracking the flow of untrusted data through a program", "Cleaning the code", "Measuring speed", "A database test"),
  q("What is 'Zope Interface'?", "A library for defining and using interfaces (before ABC was added)", "A web browser", "A type of loop", "A database tool")
];

