import { type SampleQuestion } from "./sample-questions";

const q = (question_text: string, correct: string, wrong1: string, wrong2: string, wrong3: string): SampleQuestion => ({
  question_text,
  options: [
    { text: correct, is_correct: true },
    { text: wrong1, is_correct: false },
    { text: wrong2, is_correct: false },
    { text: wrong3, is_correct: false },
  ].sort(() => Math.random() - 0.5),
  marks: 1,
});

export const oopsL1: SampleQuestion[] = [
  q("What does OOP stand for?", "Object Oriented Programming", "Online Object Process", "Ordered Object Protocol", "Optical Object Program"),
  q("Which of these is NOT a pillar of OOP?", "Compilation", "Encapsulation", "Inheritance", "Polymorphism"),
  q("What is a blueprint for creating objects called?", "Class", "Function", "Variable", "Module"),
  q("Which concept allows one class to inherit properties of another?", "Inheritance", "Abstraction", "Interface", "Overloading"),
  q("What is the process of hiding implementation details called?", "Abstraction", "Inheritance", "Encapsulation", "Polymorphism"),
  q("Wrapping data and methods into a single unit is called:", "Encapsulation", "Abstraction", "Interface", "Object"),
  q("Which type of polymorphism is Method Overloading?", "Compile-time", "Runtime", "Dynamic", "Static-link"),
  q("A method that is called automatically when an object is created is a:", "Constructor", "Destructor", "Initializer", "Main method"),
  q("What is an instance of a class called?", "Object", "Value", "Variable", "Structure"),
  q("Which relationship is represented by Inheritance?", "Is-a", "Has-a", "Part-of", "Owns"),
  q("The ability of a method to behave differently for different types is:", "Polymorphism", "Inheritance", "Abstraction", "Encapsulation"),
  q("Which keyword refers to the current instance?", "this", "self", "me", "current"),
  q("A class that cannot be instantiated is called:", "Abstract class", "Interface", "Static class", "Final class"),
  q("Which concept allows multiple methods with same name but different parameters?", "Overloading", "Overriding", "Inheritance", "Polymorphism"),
  q("What is the default access modifier in C++ classes?", "Private", "Public", "Protected", "Internal"),
  q("Which pillar is primarily used for 'code reusability'?", "Inheritance", "Abstraction", "Encapsulation", "Compilation"),
  q("Static binding is also known as:", "Early binding", "Late binding", "Dynamic binding", "Runtime binding"),
  q("Can a constructor be private?", "Yes", "No", "Only in Java", "Only in C++"),
  q("The diamond problem is associated with which type of inheritance?", "Multiple", "Single", "Multilevel", "Hierarchical"),
  q("Which language is NOT object-oriented?", "C", "Java", "C++", "Python"),
  q("A function that expands at the call site rather than being called is:", "Inline", "Static", "Virtual", "Friend"),
  q("vtable is used to achieve:", "Late binding", "Early binding", "Data hiding", "Memory management"),
  q("Which access specifier is accessible in derived classes but not outside?", "Protected", "Private", "Public", "Friend"),
  q("Main difference between shallow and deep copy?", "Deep copy clones actual content", "Shallow copy clones actual content", "Deep copy is faster", "Identical"),
  q("Which operator is used to give new meaning to existing operators?", "Operator Overloading", "Method Overriding", "Friend Function", "Generic"),
  q("A class that cannot be inherited is:", "Final or Sealed class", "Abstract class", "Static class", "Derived class"),
  q("What relationship does 'has-a' represent?", "Composition", "Inheritance", "Generalization", "Association"),
  q("Syntax for pure virtual function in C++?", "= 0", "abstract", "pure()", "None"),
  q("Used for memory cleanup before object is garbage collected?", "Finalizer", "Destructor", "Constructor", "Initializer"),
  q("Extracting relevant features without background detail?", "Abstraction", "Encapsulation", "Inheritance", "Polymorphism")
];

export const oopsL2: SampleQuestion[] = [
  q("Which inheritance type leads to 'Fragile Base Class' problem?", "Implementation Inheritance", "Interface Inheritance", "Multiple Inheritance", "Single Inheritance"),
  q("In Java, which keyword is used to achieve implementation inheritance?", "extends", "implements", "instanceof", "inherits"),
  q("What is the purpose of a Copy Constructor?", "To initialize an object with another existing object", "To delete an object", "To copy data to a database", "To create a constructor for copies"),
  q("A virtual destructor is necessary when:", "A derived class is deleted through a base class pointer", "A base class has private members", "Multiple inheritance is used", "Static binding is preferred"),
  q("Method overriding is an example of:", "Dynamic Polymorphism", "Static Polymorphism", "Ad-hoc Polymorphism", "Parametric Polymorphism"),
  q("Which design pattern uses a single class to manage its own unique instance?", "Singleton", "Factory", "Observer", "Adapter"),
  q("The 'open/closed' principle states that software entities should be:", "Open for extension, closed for modification", "Closed for extension, open for modification", "Open for all", "Closed for all"),
  q("Which concept allows treating many different derived classes as their base class?", "Upcasting", "Downcasting", "Overloading", "Serialization"),
  q("A pure virtual function makes a class:", "Abstract", "Static", "Final", "Private"),
  q("In C++, if a class has at least one pure virtual function, it becomes:", "An Abstract Base Class", "A Concrete Class", "A static class", "A friend class"),
  q("Which of these is a 'strong' has-a relationship?", "Composition", "Aggregation", "Association", "Dependency"),
  q("Liskov Substitution Principle is a part of:", "SOLID principles", "ACID properties", "OOP Pillars", "Design Patterns"),
  q("Method Resolution Order (MRO) is important in which inheritance?", "Multiple", "Single", "Multilevel", "Hierarchical"),
  q("Which access modifier allows access only within the same class?", "private", "public", "protected", "internal"),
  q("Can static methods be overridden in Java?", "No", "Yes", "Only if protected", "Only if public"),
  q("What is 'Boxing' in OOP terms?", "Converting a value type to an object type", "Converting an object to a value", "Encapsulating a class", "Packing code into a dll"),
  q("Which keyword is used to stop method overriding in Java?", "final", "static", "abstract", "const"),
  q("The process of converting an object into a byte stream is:", "Serialization", "Deserialization", "Abstraction", "Aggregation"),
  q("In OOP, a 'Message' consists of:", "Receiving object, method name, and arguments", "Method name only", "Data only", "Class name only"),
  q("Coupling refers to:", "The degree of interdependence between classes", "The degree of relatedness within a class", "Memory allocation", "Number of objects created"),
  q("Cohesion refers to:", "The degree of relatedness within a module", "The interdependence between modules", "Speed of execution", "Object size"),
  q("Which pillar focuses on reducing complexity by hiding details?", "Abstraction", "Inheritance", "Polymorphism", "Reusability"),
  q("Inheritance is also known as:", "Generalization", "Specialization", "Aggregation", "Both Generalization and Specialization"),
  q("Which design pattern defines a one-to-many dependency between objects?", "Observer", "Strategy", "Decorator", "Facade"),
  q("A 'Marker Interface' in Java is an interface with:", "No methods", "Static methods only", "A single method", "Protected methods"),
  q("Which keyword is used to call a superclass constructor in Java?", "super", "this", "base", "parent"),
  q("What is an 'Inner Class'?", "A class defined inside another class", "A class in another package", "A local variable", "An inherited class"),
  q("Partial classes are supported in:", "C#", "Java", "C++", "C"),
  q("The 'Interface Segregation Principle' suggests:", "Clients should not be forced to depend on methods they do not use", "All methods should be in one interface", "Interfaces should be private", "Inheritance should be avoided"),
  q("Which concept handles 'Runtime Error' situations in OOP?", "Exception Handling", "Garbage Collection", "Encapsulation", "Polymorphism")
];

export const oopsL3: SampleQuestion[] = [
  q("Which of these is NOT a Creational Design Pattern?", "Adapter", "Singleton", "Factory", "Builder"),
  q("The 'Dependency Inversion Principle' states that:", "High-level modules should not depend on low-level modules", "Classes should depend on concrete versions", "Interfaces should be small", "Objects should be immutable"),
  q("A 'Vtable' (Virtual Table) contains:", "Function pointers for virtual methods", "Object data", "Static variables", "Class constants"),
  q("What is 'Multiple Dispatch'?", "Selecting a function based on types of multiple arguments", "Calling multiple functions at once", "Overloading", "Overriding"),
  q("Which pattern provides a way to access elements of an aggregate object sequentially?", "Iterator", "Command", "Mediator", "Proxy"),
  q("In the 'Decorator' pattern, the decorator:", "Has the same interface as the decorated object", "Inherits from the object", "Must be static", "Replaces the object"),
  q("The 'Strategy' pattern is best used for:", "Interchanging algorithms at runtime", "Creating unique instances", "Connecting incompatible interfaces", "Simplifying complex systems"),
  q("What is 'Duck Typing'?", "An object's suitability is determined by presence of methods, not inheritance", "A type of inheritance", "A way to define ducks", "A memory management trick"),
  q("In C++, 'Diamond Inheritance' is resolved using:", "Virtual Inheritance", "Multiple Inheritance", "Static binding", "Namespaces"),
  q("Which concept allows a class to have only one instance throughout the life of the application?", "Singleton Pattern", "Factory Pattern", "Abstract Class", "Static Method"),
  q("The 'Facade' pattern is used to:", "Provide a simplified interface to a complex subsystem", "Change object behavior", "Add new methods", "Ensure security"),
  q("What is 'Lazy Initialization'?", "Delaying object creation until first use", "Initializing objects in the constructor", "Using static initializers", "Clearing memory"),
  q("Which principle says a class should have only one reason to change?", "Single Responsibility Principle", "Open/Closed Principle", "DRY Principle", "KISS Principle"),
  q("What is the difference between 'Predicate' and 'Function' in Java Functional Interfaces?", "Predicate returns boolean, Function returns a value", "They are same", "Function takes no arguments", "Predicate takes no arguments"),
  q("In OOP, 'Reflection' allows:", "Examining or modifying the structure of data/code at runtime", "Mirroring objects", "Improving performance", "Reducing memory"),
  q("The 'Command' pattern is often used for:", "Undo/Redo operations", "Formatting text", "Sorting lists", "Mathematical calculations"),
  q("A 'Weak Reference' in Java:", "Allows an object to be garbage collected even if referenced", "Is a strong pointer", "Is for high priority objects", "Prevents memory leaks"),
  q("Which relationship is represented by 'A Car has a Driver'?", "Association", "Composition", "Aggregation", "Inheritance"),
  q("What is 'Covariant Return Type'?", "Allowing an overriding method to return a more specific type", "Returning multiple values", "Returning void", "Static return type"),
  q("The 'Template Method' pattern defines:", "The skeleton of an algorithm in a method", "How to create objects", "Memory layouts", "UI templates"),
  q("What is 'Double Dispatch'?", "A mechanism to dispatch function calls based on two objects' types", "Calling a function twice", "A security feature", "Overloading twice"),
  q("The 'Chain of Responsibility' pattern:", "Passes a request along a chain of handlers", "Is for database connections", "Manages object life", "Is a creational pattern"),
  q("A 'Mixin' is:", "A class that contains methods for use by other classes without inheritance", "A mixture of variables", "A type of compiler", "A memory pool"),
  q("Which keyword in C# is used to indicate that a method is intended to override a base member?", "override", "virtual", "new", "sealed"),
  q("The 'Bridge' pattern is used to:", "Decouple an abstraction from its implementation", "Connect two servers", "Bridge two networks", "Inherit from two classes"),
  q("What is 'RAII' (Resource Acquisition Is Initialization)?", "A C++ technique where resource life is tied to object life", "A Java garbage collector", "A design pattern", "A web protocol"),
  q("Which pattern is used to separate the internal representation of a complex object from its construction?", "Builder", "Factory", "Prototype", "Singleton"),
  q("The 'Flyweight' pattern is used for:", "Reducing memory usage by sharing state among similar objects", "High speed execution", "Reducing file size", "Lightweight UI"),
  q("What is 'Inversion of Control' (IoC)?", "A design principle where a framework calls custom code", "Reversing loops", "Changing object polarity", "Inheritance reversal"),
  q("The 'State' pattern allows:", "An object to alter its behavior when its internal state changes", "Storing data in a database", "Handling UI states only", "Saving session info")
];

export const gkL1: SampleQuestion[] = [
  q("What is the capital of Japan?", "Tokyo", "Kyoto", "Osaka", "Seoul"),
  q("Which element has chemical symbol 'O'?", "Oxygen", "Gold", "Osmium", "Iron"),
  q("Who wrote 'Romeo and Juliet'?", "William Shakespeare", "Charles Dickens", "Mark Twain", "Jane Austen"),
  q("What is the largest mammal in the world?", "Blue Whale", "Elephant", "Giraffe", "Orca"),
  q("How many continents are there on Earth?", "7", "5", "6", "8"),
  q("Which planet is known as the Red Planet?", "Mars", "Jupiter", "Venus", "Saturn"),
  q("What is the currency of United Kingdom?", "Pound Sterling", "Euro", "Dollar", "Yen"),
  q("Who is known as the 'Father of Computers'?", "Charles Babbage", "Alan Turing", "Bill Gates", "Steve Jobs"),
  q("Which is the smallest country in the world?", "Vatican City", "Monaco", "Nauru", "Tuvalu"),
  q("What is the hardest natural substance on Earth?", "Diamond", "Gold", "Iron", "Platinum"),
  q("In which year did World War II end?", "1945", "1939", "1918", "1950"),
  q("Which organ in human body is responsible for pumping blood?", "Heart", "Lungs", "Brain", "Liver"),
  q("Who painted the 'Mona Lisa'?", "Leonardo da Vinci", "Pablo Picasso", "Vincent van Gogh", "Michelangelo"),
  q("What is the largest ocean on Earth?", "Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"),
  q("Which country is known as the 'Land of the Rising Sun'?", "Japan", "China", "South Korea", "Thailand"),
  q("What is the chemical symbol for Gold?", "Au", "Ag", "Fe", "Cu"),
  q("Who discovered Penicillin?", "Alexander Fleming", "Marie Curie", "Isaac Newton", "Albert Einstein"),
  q("What is the capital of France?", "Paris", "Lyon", "Marseille", "Nice"),
  q("Which gas do plants absorb from atmosphere for photosynthesis?", "Carbon Dioxide", "Oxygen", "Nitrogen", "Hydrogen"),
  q("How many strings does a standard violin have?", "4", "6", "3", "5"),
  q("Which is the longest river in the world?", "Nile", "Amazon", "Yangtze", "Mississippi"),
  q("Who was the first man to walk on the moon?", "Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "John Glenn"),
  q("What is the national animal of India?", "Tiger", "Lion", "Elephant", "Leopard"),
  q("Which continent is the Sahara Desert located in?", "Africa", "Asia", "South America", "Australia"),
  q("What is the value of Pi (π) to two decimal places?", "3.14", "3.16", "3.12", "3.18"),
  q("Who is the author of 'Harry Potter' series?", "J.K. Rowling", "George R.R. Martin", "J.R.R. Tolkien", "Stephen King"),
  q("Which part of plant carries out photosynthesis?", "Leaf", "Root", "Stem", "Flower"),
  q("What is the capital of Italy?", "Rome", "Milan", "Venice", "Florence"),
  q("How many legs does a spider have?", "8", "6", "10", "12"),
  q("Which element is essential for human bones?", "Calcium", "Iron", "Zinc", "Magnesium")
];

export const gkL2: SampleQuestion[] = [
  q("Which Indian state has the longest coastline?", "Gujarat", "Andhra Pradesh", "Tamil Nadu", "Maharashtra"),
  q("Who was the first woman Prime Minister of India?", "Indira Gandhi", "Sonia Gandhi", "Pratibha Patil", "Sarojini Naidu"),
  q("Which planet has the maximum number of moons?", "Saturn", "Jupiter", "Saturn (current leader)", "Uranus"),
  q("What is the name of the nearest galaxy to Milky Way?", "Andromeda", "Triangulum", "Sombrero", "Cartwheel"),
  q("Who invented the World Wide Web (WWW)?", "Tim Berners-Lee", "Bill Gates", "Steve Jobs", "Larry Page"),
  q("Which layer of atmosphere absorbs ultraviolet rays?", "Ozone layer", "Ionosphere", "Troposphere", "Mesosphere"),
  q("What is the chemical name of common salt?", "Sodium Chloride", "Sodium Bicarbonate", "Potassium Chloride", "Calcium Carbonate"),
  q("Who was the first President of Independent India?", "Dr. Rajendra Prasad", "Dr. S. Radhakrishnan", "Dr. Zakir Hussain", "Dr. A.P.J. Abdul Kalam"),
  q("Which is the largest desert in Asia?", "Gobi", "Thar", "Arabian", "Taklamakan"),
  q("What is the SI unit of electric current?", "Ampere", "Volt", "Ohm", "Watt"),
  q("Who was the founder of Mughal Empire in India?", "Babur", "Akbar", "Humayun", "Arabs"),
  q("Which instrument is used to measure earthquake intensity?", "Seismograph", "Barometer", "Thermometer", "Hygrometer"),
  q("What is the capital of Canada?", "Ottawa", "Toronto", "Vancouver", "Montreal"),
  q("Which day is celebrated as International Women's Day?", "March 8", "April 5", "June 2", "October 24"),
  q("Who wrote the Indian National Anthem?", "Rabindranath Tagore", "Bankim Chandra Chattopadhyay", "Sarojini Naidu", "Mahatma Gandhi"),
  q("Which metal is liquid at room temperature?", "Mercury", "Silver", "Copper", "Aluminum"),
  q("What is the largest internal organ in human body?", "Liver", "Heart", "Lungs", "Brain"),
  q("Who was the first Indian to win a Nobel Prize?", "Rabindranath Tagore", "C.V. Raman", "Mother Teresa", "Amartya Sen"),
  q("Which city is known as the 'Pink City' of India?", "Jaipur", "Udaipur", "Jodhpur", "Bikaner"),
  q("What is the chemical formula of water?", "H2O", "CO2", "O2", "NaCl"),
  q("Which festival is also known as the 'Festival of Colors'?", "Holi", "Diwali", "Eid", "Christmas"),
  q("What is the capital of Spain?", "Madrid", "Barcelona", "Seville", "Valencia"),
  q("Which is the largest hot desert in the world?", "Sahara", "Gobi", "Thar", "Kalahari"),
  q("Who is the author of 'Discovery of India'?", "Jawaharlal Nehru", "Mahatma Gandhi", "Subhas Chandra Bose", "Sardar Patel"),
  q("What is the full form of NASA?", "National Aeronautics and Space Administration", "National Aerospace and Science Agency", "Native American Space Alliance", "None"),
  q("Which gland is known as the 'Master Gland'?", "Pituitary", "Thyroid", "Adrenal", "Pancreas"),
  q("What is the study of birds called?", "Ornithology", "Entomology", "Zoology", "Biology"),
  q("Which gas is used for ripening fruits?", "Ethylene", "Methane", "Oxygen", "Nitrogen"),
  q("What is the national flower of India?", "Lotus", "Rose", "Jasmine", "Lily"),
  q("Who is the current Prime Minister of India?", "Narendra Modi", "Rahul Gandhi", "Amit Shah", "Manmohan Singh")
];

export const gkL3: SampleQuestion[] = [
  q("Who was the first Indian woman to climb Mount Everest?", "Bachendri Pal", "Santosh Yadav", "Arunima Sinha", "Dickey Dolma"),
  q("Which layer of Sun is visible during a total solar eclipse?", "Corona", "Photosphere", "Chromosphere", "Core"),
  q("What is the name of the mission that landed humans on moon?", "Apollo 11", "Gemini 4", "Vostok 1", "Sputnik 1"),
  q("Which is the oldest Veda in Indian history?", "Rig Veda", "Sama Veda", "Yajur Veda", "Atharva Veda"),
  q("Who is the father of Indian Space Program?", "Vikram Sarabhai", "Homi J. Bhabha", "Satish Dhawan", "A.P.J. Abdul Kalam"),
  q("What is the chemical name of Vitamin C?", "Ascorbic Acid", "Retinol", "Thiamine", "Calciferol"),
  q("Which is the largest gland in the human body?", "Liver", "Thyroid", "Pancreas", "Adrenal"),
  q("Who won the first ever Nobel Prize in Physics?", "Wilhelm Röntgen", "Albert Einstein", "Marie Curie", "Niels Bohr"),
  q("What is the currency of Russia?", "Rouble", "Euro", "Dollar", "Pound"),
  q("Which canal connects the Atlantic and Pacific oceans?", "Panama Canal", "Suez Canal", "Erie Canal", "Kiel Canal"),
  q("In which year did the Titanic sink?", "1912", "1905", "1918", "1922"),
  q("What is the deepest point in the world's oceans?", "Mariana Trench", "Puerto Rico Trench", "Java Trench", "Tonga Trench"),
  q("Who was the author of the book 'Wealth of Nations'?", "Adam Smith", "John Maynard Keynes", "Karl Marx", "David Ricardo"),
  q("Which is the smallest bone in the human body?", "Stapes", "Malleus", "Incus", "Femur"),
  q("What is the capital of Australia?", "Canberra", "Sydney", "Melbourne", "Perth"),
  q("Who was the first person to sail around the world?", "Ferdinand Magellan", "Christopher Columbus", "Vasco da Gama", "Captain Cook"),
  q("Which country is the largest producer of coffee in the world?", "Brazil", "Vietnam", "Colombia", "Ethiopia"),
  q("What is the SI unit of frequency?", "Hertz", "Volt", "Watt", "Joule"),
  q("Who developed the theory of evolution?", "Charles Darwin", "Gregor Mendel", "Jean-Baptiste Lamarck", "Alfred Wallace"),
  q("Which gas is known as 'Laughing Gas'?", "Nitrous Oxide", "Carbon Monoxide", "Nitrogen Dioxide", "Sulfur Dioxide"),
  q("What is the name of the Japanese parliament?", "Diet", "Duma", "Cortes", "Congress"),
  q("Which is the highest waterfall in the world?", "Angel Falls", "Niagara Falls", "Victoria Falls", "Iguazu Falls"),
  q("Who is known as the 'Lady with the Lamp'?", "Florence Nightingale", "Mother Teresa", "Sarojini Naidu", "Helen Keller"),
  q("What is the capital of Brazil?", "Brasília", "Rio de Janeiro", "São Paulo", "Salvador"),
  q("Which organ is affected by Rickets?", "Bones", "Skin", "Eyes", "Hair"),
  q("Who won the Nobel Peace Prize in 1979?", "Mother Teresa", "Nelson Mandela", "Martin Luther King Jr.", "Malala Yousafzai"),
  q("What is the name of the first Indian artificial satellite?", "Aryabhata", "Rohini", "INSAT-1A", "Bhaskara"),
  q("Which metal was first used by man?", "Copper", "Iron", "Gold", "Silver"),
  q("What is the chemical symbol for Silver?", "Ag", "Au", "Pb", "Sn"),
  q("Who is the author of 'The God of Small Things'?", "Arundhati Roy", "Vikram Seth", "Salman Rushdie", "Anita Desai")
];
