import { type SampleQuestion } from "./sample-questions";

const q = (question_text: string, correct: string, wrong1: string, wrong2: string, wrong3: string): SampleQuestion => ({
  question_text,
  options: [
    { text: correct, is_correct: true },
    { text: wrong1, is_correct: false },
    { text: wrong2, is_correct: false },
    { text: wrong3, is_correct: false },
  ].sort(() => Math.random() - 0.5),
  marks: 1,
});

export const jsL1: SampleQuestion[] = [
  q("What does DOM stand for?", "Document Object Model", "Digital Object Method", "Display Object Management", "Document Oriented Model"),
  q("Which keyword is used to declare a block-scoped variable?", "let", "var", "const", "both let and const"),
  q("Which of these is NOT a primitive data type in JS?", "Array", "String", "Number", "Boolean"),
  q("What is the result of 2 + '2'?", "'22'", "4", "Error", "NaN"),
  q("How do you write a 'Hello World' in an alert box?", "alert('Hello World')", "msg('Hello World')", "p('Hello World')", "console.log('Hello World')"),
  q("Which operator is used for strict equality?", "===", "==", "=", "!=="),
  q("What is the correct syntax for a for loop?", "for (let i = 0; i < n; i++)", "for i in n", "for (i <= n; i++)", "for (let i = 0 to n)"),
  q("Which method adds an element to the end of an array?", "push()", "pop()", "shift()", "unshift()"),
  q("How do you create a function in JavaScript?", "function myFunction() {}", "new function() {}", "def myFunction() {}", "create myFunction() {}"),
  q("What does 'typeof NaN' return?", "'number'", "'NaN'", "'undefined'", "'object'"),
  q("Which keyword refers to the current object?", "this", "self", "me", "current"),
  q("How do you write a multiline comment in JS?", "/* comment */", "// comment", "<!-- comment -->", "# comment"),
  q("Which method converts a JSON string to a JS object?", "JSON.parse()", "JSON.stringify()", "JSON.toObject()", "JSON.convert()"),
  q("What is the correct way to check if 'myVar' is NOT null?", "myVar !== null", "myVar != null", "myVar is not null", "!myVar"),
  q("Which event occurs when a user clicks on an HTML element?", "onclick", "onchange", "onmouseover", "onmouseclick"),
  q("How do you find the number with the highest value of x and y?", "Math.max(x, y)", "Math.ceil(x, y)", "top(x, y)", "Math.high(x, y)"),
  q("Which statement is used to exit a loop?", "break", "exit", "stop", "return"),
  q("What is the window object?", "The browser's window that contains the DOM", "A CSS selector", "A database connection", "A type of variable"),
  q("How do you call a function named 'myFunction'?", "myFunction()", "call myFunction()", "start myFunction()", "execute myFunction()"),
  q("What is the use of 'isNaN()' function?", "To determine if a value is an illegal number", "To check for null", "To check value is 0", "To check value is string"),
  q("Which company developed JavaScript?", "Netscape", "Microsoft", "Google", "Oracle"),
  q("What will 3 > 2 > 1 return?", "false", "true", "Error", "1"),
  q("How do you add a comment in JS?", "//", "/*", "--", "#"),
  q("What is an 'Undefined' value in JS?", "A variable that has been declared but not assigned a value", "A value that doesn't exist", "A type of error", "A keyword"),
  q("Which array method returns a new array with all elements that pass a test?", "filter()", "map()", "forEach()", "find()"),
  q("What is the use of 'slice()' method?", "To select a part of an array and return it as a new array", "To remove elements", "To add elements", "To sort elements"),
  q("Which symbol is used for template literals?", "Backticks (`)", "Quotes (')", "Double quotes (\")", "Slashes (/)"),
  q("What is a 'Closure'?", "A function with access to its outer scope even after it has closed", "A way to close the browser", "A private variable", "An end of a loop"),
  q("What is the default value of a boolean variable?", "false", "true", "null", "undefined"),
  q("Which method used to round a number to the nearest integer?", "Math.round()", "Math.ceil()", "Math.floor()", "Math.trunc()")
];

export const reactL1: SampleQuestion[] = [
  q("What is React?", "A JavaScript library for building user interfaces", "A CSS framework", "A database management system", "A server-side language"),
  q("Who developed React?", "Meta (Facebook)", "Google", "Microsoft", "Twitter"),
  q("What is JSX?", "JavaScript XML", "JavaScript Extension", "JSON XML", "Java Syntax Extension"),
  q("What is a Component in React?", "A reusable piece of UI", "A type of variable", "A database table", "A CSS selector"),
  q("Which hook is used to manage state in a functional component?", "useState", "useEffect", "useContext", "useReducer"),
  q("What is the purpose of useEffect hook?", "To perform side effects in functional components", "To manage state", "To create refs", "To optimize performance"),
  q("What are Props?", "Properties passed to components", "Internal state of a component", "A type of CSS", "A JavaScript library"),
  q("How many elements can a React component return?", "One single root element", "Any number of elements", "Exactly two", "As many as needed without a parent"),
  q("What is the 'Virtual DOM'?", "A lightweight copy of the real DOM", "A new type of browser", "A replacement for the DOM", "A CSS engine"),
  q("How do you write a comment in JSX?", "{/* comment */}", "// comment", "<!-- comment -->", "/* comment */"),
  q("Which keyword is used to create a class component?", "class", "function", "const", "define"),
  q("What is 'Lifting State Up'?", "Moving state to the closest common ancestor", "Deleting state", "Using global variables", "Moving state to a child component"),
  q("What is the use of 'key' prop in lists?", "To uniquely identify elements for efficient updates", "To style items", "To store data", "To sort items"),
  q("What is the children prop?", "A prop that allows components to be nested", "A list of numbers", "A CSS property", "A way to create loops"),
  q("Which hook returns the previous value of a state?", "None by default (needs custom implementation/ref)", "usePrevious", "useHistory", "useMemo"),
  q("What is React Fragment used for?", "To group multiple elements without adding an extra node to the DOM", "To fragment the database", "To create routes", "To handle errors"),
  q("What is the use of React Router?", "To handle navigation in a single-page application", "To route database queries", "To route CSS styles", "To handle server requests"),
  q("What is Redux?", "A state management library", "A UI library", "A testing framework", "A build tool"),
  q("What is a Hook?", "A function that lets you 'hook into' React state and lifecycle features", "A CSS selector", "A database trigger", "A way to catch errors"),
  q("Can you use hooks in class components?", "No", "Yes", "Only with a HOC", "Only in the constructor"),
  q("What is the use of 'useMemo' hook?", "To memoize expensive calculations", "To manage state", "To create refs", "To handle effects"),
  q("What is 'Prop Drilling'?", "Passing data through multiple layers of components", "A way to drill holes in UI", "A database optimization", "A type of loop"),
  q("Which method is used to render a React app in the DOM (React 18+)?", "createRoot().render()", "ReactDOM.render()", "React.render()", "root.render()"),
  q("What is the use of 'useRef' hook?", "To create a persistable reference that doesn't trigger re-renders", "To manage state", "To perform effects", "To handle context"),
  q("What is 'Controlled Component'?", "A component where form data is handled by React state", "A secure component", "A component with no props", "A static component"),
  q("What is an 'uncontrolled component'?", "A component where form data is handled by the DOM", "A component out of control", "A component with bugs", "A global component"),
  q("What is the purpose of 'React.memo'?", "A higher-order component for memoizing components", "To store data", "To manage context", "To create routes"),
  q("What is 'Higher-Order Component' (HOC)?", "A function that takes a component and returns a new component", "A top-level component", "A CSS class", "A database model"),
  q("What is the context API used for?", "To share data globally without prop drilling", "To manage local state", "To handle events", "To perform API calls"),
  q("What is 'Strict Mode' in React?", "A tool for highlighting potential problems in an application", "A secure way to write JS", "A way to enforce data types", "A production-only feature")
];

export const jsL2: SampleQuestion[] = [
  q("What is the difference between '==' and '==='?", "'===' checks both value and type, '==' checks only value", "No difference", "'==' is faster", "'===' is for strings only"),
  q("What is 'Hoisting' in JavaScript?", "Variable and function declarations are moved to the top of their scope during compilation", "Calling a function before it script is loaded", "A way to lift state", "Increasing memory limit"),
  q("What is a 'Promise' in JS?", "An object representing the eventual completion or failure of an asynchronous operation", "A guarantee of security", "A type of loop", "A way to declare variables"),
  q("What does 'Array.map()' return?", "A new array with the results of calling a provided function on every element", "The length of the array", "The original array modified", "The first element"),
  q("What is the purpose of 'async/await'?", "To handle asynchronous code in a more readable, synchronous-looking way", "To speed up code execution", "To create threads", "To handle errors only"),
  q("What is 'Event Bubbling'?", "Events starting from the target element and moving up the DOM tree", "Events moving down the tree", "Events occurring simultaneously", "Creating popup bubbles"),
  q("What is 'Event Delegation'?", "Attaching a single event listener to a parent element to manage events for its children", "Assigning events to delegates", "Deleting events", "Calling events from another script"),
  q("What is 'Bind' method used for?", "To create a new function that, when called, has its 'this' keyword set to a provided value", "To bind two variables", "To concatenate strings", "To lock a variable"),
  q("What is a 'Higher-Order Function'?", "A function that takes another function as an argument or returns a function", "A function in the global scope", "A function with many parameters", "A mathematical function"),
  q("What is 'Strict Mode' ('use strict') in JS?", "A way to opt-into a restricted variant of JavaScript that catches common coding bloopers", "A way to make JS faster", "A type of CSS", "A security protocol"),
  q("What is the use of 'spread' operator (...)?", "To expand an iterable into individual elements", "To compress an array", "To multiply numbers", "To catch errors"),
  q("What is 'Destructuring' in ES6?", "Extracting multiple properties/elements from objects/arrays into distinct variables", "Deleting objects", "Merging arrays", "Removing unused variables"),
  q("What is 'Lexical Scoping'?", "A function's access to variables is determined by its physical location in the source code", "A scope that changes at runtime", "A global scope", "A type of memory management"),
  q("What is the difference between 'null' and 'undefined'?", "null is an assigned empty value, undefined means a variable was declared but not assigned", "They are identical", "undefined is assigned, null is default", "null is a number, undefined is a string"),
  q("Which method is used to combine two or more arrays?", "concat()", "join()", "merge()", "append()"),
  q("What does 'Object.freeze()' do?", "Prevents any modification to an existing object", "Makes an object read-only for current session", "Deletes an object", "Encrypts an object"),
  q("What is an 'IIFE'?", "Immediately Invoked Function Expression", "Internal Iteration Function Element", "Identical Interface Forwarding Entry", "Integrated Interface Flow Engine"),
  q("What is the 'Call' method used for?", "To call a function with a given 'this' value and arguments provided individually", "To call a service", "To trigger a callback", "To define a function"),
  q("Which method is used to search for a value in an array and return its first index?", "indexOf()", "findIndex()", "search()", "locate()"),
  q("What is the purpose of 'Object.keys()'?", "Returns an array of a given object's own enumerable string-keyed property names", "Returns all values", "Counts keys", "Merges keys"),
  q("What is 'Prototype' in JS?", "An object from which other objects inherit properties", "A draft version of a code", "A type of function", "A debugging tool"),
  q("How do you prevent the default behavior of an event?", "event.preventDefault()", "event.stopPropagation()", "event.stop()", "event.cancel()"),
  q("What is 'Currying'?", "Converting a function that takes multiple arguments into a sequence of functions that each take a single argument", "A way to cook code", "A type of loop", "Merging two scripts"),
  q("What is the use of 'reduce()' array method?", "To reduce an array to a single value by applying a function", "To shorten array length", "To remove duplicates", "To sort the array"),
  q("What is 'Temporal Dead Zone' (TDZ)?", "The state where 'let' and 'const' variables are unreachable before their declaration", "A time limit for code execution", "A memory leak", "A type of error"),
  q("which statement is used to handle exceptions?", "try...catch", "do...handle", "begin...error", "if...error"),
  q("What is the purpose of 'Object.assign()'?", "To copy values of all enumerable own properties from source objects to a target object", "To rename an object", "To delete an object", "To check object types"),
  q("What is 'Rest Parameter' syntax (...args)?", "Allows a function to accept an indefinite number of arguments as an array", "Allows to spread an array", "Is used to reset variables", "Combines two functions"),
  q("What is a 'Web Worker'?", "A script that runs in the background, independent of the main UI thread", "A person who works on websites", "A type of browser extension", "A cloud server"),
  q("What is 'Debouncing'?", "Limiting the rate at which a function can fire (executing after a delay of silence)", "Grouping multiple events", "Handling double clicks", "A type of state management")
];

export const jsL3: SampleQuestion[] = [
  q("What is the 'Event Loop' in JavaScript?", "The mechanism that allows JS to perform non-blocking I/O operations by offloading tasks to the kernel", "A way to write infinite loops", "A CSS animation property", "A database synchronization tool"),
  q("What are 'Generator functions'?", "Functions that can be exited and later re-entered, keeping their context (yield)", "Functions that generate electricity", "Functions that create CSS", "Automatic class generators"),
  q("What is 'Tail Call Optimization' (TCO)?", "An ES6 feature that allows functions to call themselves without growing the stack (in specific conditions)", "Optimizing the end of an array", "A way to speed up loops", "A memory management tool"),
  q("What is a 'Proxy' object?", "An object that wraps another object and allows you to intercept and redefine fundamental operations (get, set, etc.)", "A server that hides IP", "A lightweight object", "A type of ref"),
  q("What is 'Reflect' API used for?", "Providing methods for interceptable JavaScript operations, similar to proxy traps", "Mirroring an object", "Viewing private variables", "Handling UI reflections"),
  q("What is 'Memoization'?", "An optimization technique that stores the results of expensive function calls and returns the cached result when similar inputs occur", "Memorizing variables", "Memory allocation", "Deleting unused functions"),
  q("What is 'Prototypal Inheritance'?", "A method where objects inherit directly from other objects via the prototype chain", "Inheritance using classes", "Inheritance from a database", "A type of coding style"),
  q("What is the difference between 'WeakMap' and 'Map'?", "WeakMap keys must be objects and are weakly held (eligible for garbage collection)", "WeakMap is slower", "Map has no size property", "WeakMap allows duplicate keys"),
  q("What is 'Execution Context'?", "The environment in which JavaScript code is executed (Global, Function, or Eval)", "Specifying the compiler", "A type of security layer", "The UI state"),
  q("What is the 'Shadow DOM'?", "A private, encapsulated DOM (used in Web Components) that is separate from the main document DOM", "A darker version of UI", "A backup of the DOM", "A hidden database"),
  q("What is 'Microtask' vs 'Macrotask'?", "Microtasks (Promises) are executed immediately after the current task; Macrotasks (setTimeout) are queued for the next loop", "Microtask is smaller in size", "Macrotask is for servers", "They are the same"),
  q("What is 'Tree Shaking'?", "Dead code elimination during the bundling process (removing unused exports)", "Updating the DOM tree", "A file compression method", "Removing hidden files"),
  q("What is 'Module Pattern'?", "A design pattern used to wrap a set of variables and functions into a single scope (encapsulation)", "A way to import modules", "A CSS organization tool", "A database structure"),
  q("What is 'Functional Programming' in JS?", "A paradigm based on pure functions, immutability, and avoiding side effects", "Programming that works", "Using only functions and no classes", "A type of UI design"),
  q("What is 'Symbol' data type in ES6?", "A unique and immutable primitive value often used as object property keys", "A mathematical symbol", "A type of string", "A reference pointer"),
  q("What is 'BigInt'?", "A numeric primitive for representing integers larger than 2^53 - 1", "A very large variable name", "A type of floating point", "An external library"),
  q("What is 'Polyfill'?", "A piece of code used to provide modern functionality on older browsers that do not natively support it", "A type of paint", "A database gap filler", "A multi-threaded script"),
  q("What is 'Throttling'?", "Ensuring a function is called at most once in a specified time interval", "Stopping a function", "Merging functions", "Speeding up execution"),
  q("What is 'WebAssembly' (Wasm)?", "A binary instruction format for a stack-based virtual machine, enabling high-performance code on the web", "A new JS version", "A server language", "A CSS tool"),
  q("What is 'Temporal' API (proposed/experimental)?", "A modern replacement for the Date object with better time zones and DST handling", "An API for temporary variables", "A way to measure speed", "A database time tool"),
  q("What is 'CORS'?", "Cross-Origin Resource Sharing - a mechanism that uses HTTP headers to allow one origin to access resources from a different origin", "A way to sort code", "A CSS rule", "A database connection"),
  q("What is 'Content Security Policy' (CSP)?", "An added layer of security that helps detect and mitigate certain types of attacks, including XSS", "A policy for content writers", "A CSS framework", "A database schema"),
  q("What is 'Shallow Equality' check?", "Checking if the top-level properties are the same", "Checking every nested property", "Checking the data types only", "Comparing memory addresses strictly"),
  q("What is 'Deep Equality' check?", "Recursively comparing all nested properties of two objects", "Checking only if they point to the same memory", "Checking only if keys exist", "Comparing the size of objects"),
  q("What is 'Service Worker'?", "A script that browser runs in background, used for offline support, push notifications, and background sync", "A person who fixes servers", "A type of API", "A database worker"),
  q("What is 'Shadowing' in variable scope?", "When a variable in an inner scope has the same name as an outer scope variable, hiding it", "A visual shadow effect", "Increasing variable size", "Copying a variable"),
  q("What is 'Pure Function'?", "A function where the return value is determined only by its input and has no side effects", "A function with no errors", "A function in an abstract class", "A function with no return"),
  q("What is 'Transpilation'?", "Converting source code from one high-level language to another (e.g., Babel converts ES6 to ES5)", "Compiling to machine code", "Running code in a browser", "Sending code to server"),
  q("What is 'Intersection Observer' API?", "A way to asynchronously observe changes in the intersection of a target element with an ancestor or viewport", "Observing intersections in arrays", "Merging two observers", "A CSS selector tool"),
  q("What is 'Optional Chaining' (?.)?", "Allows reading the value of a property deep within a chain of connected objects without validation of every reference", "A way to chain functions", "Optional variable assignment", "A loop construct")
];

export const reactL2: SampleQuestion[] = [
  q("What is the difference between 'useEffect' and 'useLayoutEffect'?", "useLayoutEffect runs synchronously after all DOM mutations", "No difference", "useEffect is for calculations", "useLayoutEffect is for side effects"),
  q("What is 'PureComponent'?", "A component that implements shouldComponentUpdate with shallow prop and state comparison", "A component with no props", "An abstract component", "A functional component"),
  q("What is 'React.memo' used for?", "To prevent unnecessary re-renders of a component if its props haven't changed", "To memoize state", "To store data", "To handle effects"),
  q("What is 'useCallback' hook used for?", "To memoize function instances across renders", "To manage state", "To create refs", "To perform side effects"),
  q("What is the 'Context' API used for?", "To handle global state without prop drilling", "To manage local state", "To define routes", "To handle API calls"),
  q("How do you handle errors in React components?", "Error Boundaries (componentDidCatch and getDerivedStateFromError)", "try/catch inside render", "Checking props", "Using window.onerror"),
  q("What are 'Portals' in React?", "A way to render children into a DOM node that exists outside the DOM hierarchy of the parent", "A way to move data between apps", "A navigation tool", "A type of route"),
  q("What is the use of 'useReducer' hook?", "A more powerful alternative to useState for complex state logic", "To reduce array size", "To handle UI effects", "To create refs"),
  q("What is 'Reconciliation' in React?", "The process of updating the UI to match the latest state using the Virtual DOM diffing algorithm", "Logging in users", "Scaling the app", "Compiling the code"),
  q("What is the 'useContext' hook?", "Accesses the value of a context without using a Consumer", "Creates a new context", "Deletes a context", "Manages state locally"),
  q("What is 'Keys' in React Reconciliation?", "Hints for identifying which items have changed, been added, or removed in a list", "Encryption keys", "Secret values", "Database IDs"),
  q("What is 'Hydration' in Server-Side Rendering (SSR)?", "The process of attaching event listeners to the static HTML sent from the server", "Downloading images", "Filling the database", "Compiling JS to HTML"),
  q("What is 'Code Splitting'?", "Splitting code into smaller bundles to improve performance (often using React.lazy)", "Writing code in multiple files", "A type of bug", "Deleting unused code"),
  q("What is 'Suspense' component?", "Allows waiting for some code to load and declaratively specify a loading state", "A way to pause execution", "A bug handling tool", "A class for data fetching"),
  q("What is 'React.forwardRef'?", "A technique for automatically passing a ref through a component to one of its children", "Moving a ref to a parent", "Deleting a ref", "A hook for references"),
  q("What is the use of 'useImperativeHandle'?", "Customizes the instance value that is exposed to parent components when using ref", "Forces a re-render", "Handles imperative commands", "Creates a new hook"),
  q("What is a 'Higher-Order Component' (HOC)?", "A function that takes a component and returns a new component", "A component with many props", "A specialized class", "An internal React component"),
  q("What does 'lifting state up' mean?", "Moving shared state to the closest common ancestor", "Moving state to a child", "Deleting state", "Moving state to a global store"),
  q("What is the difference between 'controlled' and 'uncontrolled' inputs?", "Controlled inputs have their value managed by state; uncontrolled use refs", "Controlled are safer", "Uncontrolled are faster", "No difference"),
  q("What is 'Fragment' useful for?", "Returning multiple elements without adding an extra wrapper node to the DOM", "Splitting code", "Handling errors", "Managing transition states"),
  q("What is the 'useEffect' dependency array for?", "Controlling when the effect should re-run based on changing values", "Storing the effect results", "Listing all used variables", "Optimizing the server"),
  q("What happens when you call 'setState' (or the update function in useState)?", "React schedules an update and triggers a re-render of the component and its children", "The component re-renders immediately and synchronously", "Only the changed element updates in real DOM", "The page refreshes"),
  q("What is the purpose of 'SyntheticEvent'?", "A cross-browser wrapper around the browser's native event for consistency", "An artificial event", "A performance-focused event", "A way to simulate clicks"),
  q("What are 'Children' in React components?", "The content passed between the opening and closing tags of a component", "The props of a component", "The methods of a component", "The sub-components"),
  q("How do you render a list of data in React?", "Using the .map() function to return an array of elements", "Using a for loop in JSX", "Using the <List> tag", "Using while loops"),
  q("What is 'Prop Types'?", "A library for type-checking React props (now mostly replaced by TypeScript)", "A way to style props", "A professional version of React", "A database property"),
  q("What is the difference between class and functional components since hooks were introduced?", "Functional components with hooks can do almost everything class components can, but are generally more concise", "Functional components are slower", "Class components are deprecated", "Functional components can't have state"),
  q("What is 'React DevTools'?", "A browser extension for inspecting React component hierarchies", "A built-in IDE", "A command-line tool", "A production monitoring tool"),
  q("What is 'Batching' in React 18?", "Grouping multiple state updates into a single re-render for better performance", "Running multiple effects", "Batching API calls", "Loading multiple components"),
  q("What is 'useId' hook (React 18)?", "Generating unique IDs for accessibility attributes", "Logging in users", "Identifying components", "Database IDs")
];

export const reactL3: SampleQuestion[] = [
  q("What is 'Concurrent React' (Concurrent Mode)?", "A set of features that help React stay responsive by allowing it to interrupt a long-running render", "Running React on multiple servers", "Using multi-threading in Web Workers", "A way to send multiple API requests"),
  q("What is the 'useTransition' hook (React 18)?", "Allows marking some state updates as non-urgent transitions", "Handling CSS transitions", "Moving between routes", "A way to animate components"),
  q("What is 'useDeferredValue' hook?", "Allows deferring updating a part of the UI that is not urgent", "Delaying a function call", "Speeding up API responses", "A way to handle late state"),
  q("What is 'Server Components' (RSC)?", "Components that run and render only on the server, reducing the amount of JS sent to the client", "Components for backend only", "A new type of server", "A way to connect to databases directly"),
  q("What is 'Automatic Batching' in React 18?", "Batching state updates even inside promises, timeouts, and native event handlers", "Automatically updating the database", "Batching CSS changes", "A script that runs on startup"),
  q("What is the 'Diffing Algorithm' complexity in React?", "O(n)", "O(n^3)", "O(log n)", "O(1)"),
  q("How does React handle the 'Diamond Problem' of state updates?", "By ensuring each component re-renders at most once per batch of updates", "Using internal locks", "It doesn't handle it", "By crashing specifically"),
  q("What is 'SSR' (Server-Side Rendering)?", "Generating HTML on the server and sending it to the client", "Rendering on the client", "Rendering on a static site", "Rendering only images"),
  q("What is 'SSG' (Static Site Generation)?", "Building the entire site as static HTML files at build time", "Generating code at runtime", "A way to generate styles", "Server-managed state"),
  q("What is 'ISR' (Incremental Static Regeneration)?", "Creating or updating static pages after build time, in the background", "A way to regenerate the team", "Updating only JS files", "Increasing speed of routes"),
  q("What is 'Atomic State' (Jotai/Recoil)?", "A state management philosophy where state is split into tiny pieces (atoms)", "A very secure state", "State stored in a database", "A way to group state"),
  q("In React 18, what is 'useSyncExternalStore' used for?", "Subscribing to external stores in a way that is compatible with concurrent rendering", "Syncing two browser windows", "External API calls", "A way to handle disk I/O"),
  q("What is 'Tearing' in concurrent rendering?", "A visual inconsistency where UI displays different values for the same state", "Breaking the UI", "A type of animation", "Removing components"),
  q("What is 'useInsertionEffect' useful for?", "Inserting styles into the DOM before other effects run (for CSS-in-JS libraries)", "Inserting data into arrays", "A way to add new elements", "An animation hook"),
  q("What is 'Fiber' architecture?", "A ground-up rewrite of React's core algorithm to support incremental rendering", "A faster network cable", "A type of CSS framework", "A database indexing method"),
  q("How does React's 'SyntheticEvent' system work under the hood?", "Using event delegation at the root of the application", "Binding events to every DOM node", "Using a custom event emitter", "Creating many browser threads"),
  q("What is 'Render-as-You-Fetch' pattern?", "Starting to fetch data as soon as possible, before rendering happens", "Fetching data after the component mounts", "Waiting for user click to fetch", "A server-side only technique"),
  q("What is the 'Double-Buffering' technique in React Fiber?", "React works on a 'work-in-progress' tree while the current tree is visible, then swaps them", "Using two monitors", "Storing two versions of state", "A graphics rendering trick"),
  q("What is 'Micro-Frontends'?", "An architectural style where independently deliverable frontend apps are composed into a greater whole", "Small UI components", "Using a tiny browser", "A mobile-first approach"),
  q("What is 'Framer Motion' used for?", "A popular library for complex React animations", "A frame for monitors", "A database tool", "A type of routing"),
  q("What is the use of 'Profiling' in React?", "Measuring the performance of components to find bottlenecks", "Setting user roles", "Securing the app", "Creating user profiles"),
  q("What is 'Immutability' and why is it important in React?", "Objects are not modified; instead, new objects are created. This makes change detection (diffing) fast.", "Variables cannot be changed", "It speeds up the server", "It's a security rule"),
  q("What is 'React.lazy'?	", "A function that lets you render a dynamic import as a regular component", "A component that doesn't do anything", "Slow rendering", "A hook for delay"),
  q("What is 'Suspense for Data Fetching'?", "Handling loading states for asynchronous data using Suspense boundaries", "Stopping data from arriving", "A bug in React 17", "A server-side feature"),
  q("What is 'XSS' (Cross-Site Scripting) and how does React protect against it?", "Malicious scripts injected into pages. React escapes all string values by default.", "A CSS problem", "A database protocol", "A way to share styles"),
  q("What is 'Prop-Types' vs 'TypeScript' in React?", "TypeScript provides static type checking at compile time; Prop-Types is at runtime.", "They are the same", "TypeScript is for styling", "Prop-Types is faster"),
  q("What is 'Flux' architecture?", "A pattern for unidirectional data flow (Action -> Dispatcher -> Store -> View)", "A way to speed up rendering", "A CSS framework", "A server language"),
  q("What is 'Re-rendering' vs 'Mounting'?", "Mounting is adding to DOM first time; re-rendering is updating after state change", "They are the same", "Re-rendering is faster", "Mounting happens on every change"),
  q("What is 'Keys' and why should we not use 'index' as a key for dynamic lists?", "Index as key can cause bugs and performance issues when items are reordered", "Index is too long", "Index is not unique", "Keys must be strings"),
  q("What is 'Component Lifecycle' in functional components?", "Managed via the useEffect hook to simulate mount, update, and unmount", "It doesn't exist", "Functional components are always alive", "Managed in the constructor")
];
