import { type SampleQuestion } from "./sample-questions";

const q = (question_text: string, correct: string, wrong1: string, wrong2: string, wrong3: string): SampleQuestion => ({
  question_text,
  options: [
    { text: correct, is_correct: true },
    { text: wrong1, is_correct: false },
    { text: wrong2, is_correct: false },
    { text: wrong3, is_correct: false },
  ].sort(() => Math.random() - 0.5),
  marks: 1,
});

export const sqlL1: SampleQuestion[] = [
  q("What does SQL stand for?", "Structured Query Language", "Simple Query Language", "Standard Query Logic", "System Query Language"),
  q("Which command is used to select data from a database?", "SELECT", "EXTRACT", "OPEN", "GET"),
  q("Which command is used to update data in a database?", "UPDATE", "SAVE", "MODIFY", "CHANGE"),
  q("Which command is used to delete data from a database?", "DELETE", "REMOVE", "DROP", "CLEAR"),
  q("Which command is used to insert new data?", "INSERT INTO", "ADD RECORD", "ADD NEW", "CREATE NEW"),
  q("Which keyword is used to return unique values?", "DISTINCT", "UNIQUE", "DIFFERENT", "ONLY"),
  q("Which clause is used to filter records?", "WHERE", "FROM", "IF", "WHILE"),
  q("Which operator is used to search for a specified pattern?", "LIKE", "SEARCH", "MATCH", "FIND"),
  q("What is the primary key?", "A unique identifier for each record in a table", "The first column in a table", "A password for the database", "The name of the table"),
  q("Which join returns all rows from both tables?", "FULL JOIN", "INNER JOIN", "LEFT JOIN", "RIGHT JOIN"),
  q("Which command is used to create a table?", "CREATE TABLE", "MAKE TABLE", "GENERATE TABLE", "ADD TABLE"),
  q("How do you order results in ascending order?", "ORDER BY ASC", "SORT BY ASC", "ORDER ASC", "ARRANGE ASC"),
  q("What is a foreign key?", "A field that relates to the primary key of another table", "An external password", "A key from another database", "A secondary index"),
  q("Which function is used to count the number of rows?", "COUNT()", "SUM()", "TOTAL()", "NUM()"),
  q("Which clause is used to group rows that have the same values?", "GROUP BY", "ORGANIZE BY", "COLLECT BY", "JOIN BY"),
  q("What does 'NULL' mean in SQL?", "The absence of a value", "Zero", "An empty string", "A space"),
  q("Which command deletes an entire table?", "DROP TABLE", "DELETE TABLE", "REMOVE TABLE", "CLEAR TABLE"),
  q("Which operator is used to combine multiple conditions?", "AND", "ALSO", "PLUS", "WITH"),
  q("Which join returns only the matching rows from both tables?", "INNER JOIN", "OUTER JOIN", "LEFT JOIN", "RIGHT JOIN"),
  q("Which function returns the highest value?", "MAX()", "HIGH()", "TOP()", "PEAK()"),
  q("Which command is used to add a column to a table?", "ALTER TABLE ADD", "UPDATE TABLE ADD", "CHANGE TABLE ADD", "MODIFY TABLE ADD"),
  q("What is an index useful for?", "Improving the speed of data retrieval", "Securing the data", "Reducing database size", "Connecting tables"),
  q("Which clause filters grouped results?", "HAVING", "WHERE", "FILTER", "ONLY"),
  q("Which aggregate function returns the total sum?", "SUM()", "ADD()", "TOTAL()", "COUNT()"),
  q("What happens when you use 'DELETE' without 'WHERE'?", "All records are deleted", "Nothing happens", "The table is dropped", "An error occurs"),
  q("Which SQL statement is used to give permissions?", "GRANT", "ALLOW", "GIVE", "PERMIT"),
  q("What is a view?", "A virtual table based on the result-set of an SQL statement", "A stored physical table", "A database backup", "An index"),
  q("Which SQL operator checks for a range of values?", "BETWEEN", "RANGE", "IN", "FROM-TO"),
  q("What does 'TRUNCATE' do?", "Deletes all rows but keeps the table structure", "Deletes the table and structure", "Removes only one row", "Renames the table"),
  q("Which character is a wildcard for multiple characters in LIKE?", "%", "*", "?", "_")
];

export const nodeL1: SampleQuestion[] = [
  q("What is Node.js?", "An open-source, cross-platform JavaScript runtime environment", "A JavaScript library", "A CSS framework", "A database management system"),
  q("Which engine powers Node.js?", "V8", "SpiderMonkey", "Chakra", "JavaScriptCore"),
  q("What is NPM?", "Node Package Manager", "New Python Module", "Node Power Method", "Network Protocol Manager"),
  q("Which command initializes a new Node.js project?", "npm init", "node init", "npm start", "node start"),
  q("which module is used for file system operations?", "fs", "path", "http", "events"),
  q("What is the use of 'require()' in Node.js?", "To import modules", "To export variables", "To connect to a database", "To start a server"),
  q("which core module is used to create a web server?", "http", "server", "net", "web"),
  q("How do you install a package globally using npm?", "npm install -g <package>", "npm install <package> --global", "npm get <package>", "node install <package>"),
  q("What is package.json used for?", "Managing project metadata and dependencies", "Storing CSS styles", "Defining database schemas", "Writing HTML templates"),
  q("What is 'Callback Hell'?", "A situation where multiple nested callbacks make code hard to read", "A server crash", "An infinite loop", "A secure callback function"),
  q("which method exports a module in CommonJS?", "module.exports", "export default", "return module", "module.send"),
  q("What is the 'Event Loop' in Node.js?", "A mechanism that handles asynchronous calls by offloading them to the system", "A for loop for events", "A way to repeat API calls", "A type of UI event"),
  q("which module is used for path manipulation?", "path", "fs", "url", "os"),
  q("What does 'node -v' do?", "Shows the current version of Node.js", "Starts the node server", "Validates the code", "Shows the node path"),
  q("What is a 'Stream' in Node.js?", "An object that lets you read or write data in chunks", "A type of database", "A server log", "A CSS property"),
  q("What is 'Middleware' in Express.js?", "Functions that have access to the request, response, and next function", "A database layer", "A front-end component", "A security patch"),
  q("which function is used to read a file asynchronously?", "fs.readFile()", "fs.readSync()", "fs.open()", "fs.get()"),
  q("What is 'Express.js'?", "A web application framework for Node.js", "A rapid database", "A fast compiler", "A JavaScript syntax extension"),
  q("What is the use of 'process.env'?", "Accessing environment variables", "Running processes", "Debugging code", "Defining constants"),
  q("which tool is used to automatically restart a Node app after changes?", "nodemon", "restart-js", "node-auto", "watchman"),
  q("How do you handle errors in asynchronous code using Express?", "Next(error) function", "Try/Catch only", "Window.onerror", "Throwing a string"),
  q("What is 'Libuv'?", "A multi-platform support library with focus on asynchronous I/O", "A node module", "A database driver", "A CSS library"),
  q("which module provides utilities for URL parsing?", "url", "path", "http", "os"),
  q("What is 'REPL' in Node.js?", "Read-Eval-Print Loop", "Run-Execute-Process-Log", "Real-time Event Processing Layer", "Regular Expression Parsing Link"),
  q("What is 'Event Emitter'?", "A class that facilitates communication between objects in Node.js", "A UI button", "A database trigger", "A network router"),
  q("What is 'Buffer' class used for?", "Handling binary data", "Caching strings", "Sorting arrays", "Storing images"),
  q("what is the default port for most node development servers?", "3000", "80", "443", "8080"),
  q("What does 'npm install' without arguments do?", "Installs all dependencies listed in package.json", "Installs the latest node version", "Clears the cache", "Initializes the project"),
  q("How do you access command-line arguments in Node.js?", "process.argv", "os.args", "args.list", "node.params"),
  q("which module provides basic operating system related utility functions?", "os", "system", "hw", "platform")
];

export const cppL1: SampleQuestion[] = [
  q("Who developed C++?", "Bjarne Stroustrup", "James Gosling", "Dennis Ritchie", "Guido van Rossum"),
  q("What is C++?", "An extension of C that supports object-oriented programming", "A scripting language", "A purely functional language", "A markup language"),
  q("Which header file is used for input-output in C++?", "iostream", "stdio.h", "conio.h", "input.h"),
  q("What is the extension of a C++ source file?", ".cpp", ".cc", ".c", ".h"),
  q("How do you print 'Hello World' in C++?", "cout << 'Hello World';", "print('Hello World');", "printf('Hello World');", "System.out.println('Hello World');"),
  q("What is a class in C++?", "A user-defined data type that holds data and functions", "A group of variables", "A type of loop", "A function"),
  q("What is an object?", "An instance of a class", "A blueprint", "A primitive type", "A memory address"),
  q("Which keyword is used for Inheritance?", "Public / Private / Protected specifiers", "extends", "inherits", "base"),
  q("What is Polymorphism?", "The ability of an object to take on multiple forms", "Many classes", "Copying an object", "Deleting data"),
  q("Which operator is used for input from the user?", ">>", "<<", ">", "<"),
  q("What is the default access modifier in a class?", "private", "public", "protected", "friend"),
  q("What is a constructor?", "A special member function initialized when an object is created", "A static method", "A destructor", "A main function"),
  q("What is a destructor?", "A member function called when an object is destroyed", "An initializer", "A memory leak", "A type of operator"),
  q("Which keyword prevents a variable from being modified?", "const", "final", "static", "fix"),
  q("What is a pointer?", "A variable that stores the memory address of another variable", "A data type", "A loop", "A function"),
  q("How do you declare a pointer to an integer?", "int* ptr;", "int ptr;", "pointer ptr;", "int &ptr;"),
  q("What is the 'new' operator used for?", "To allocate memory dynamically on the heap", "To create a class", "To import a module", "To add an element"),
  q("What is the 'delete' operator used for?", "To deallocate memory that was allocated by new", "To delete a file", "To clear the screen", "To remove an item from a list"),
  q("What is a Reference in C++?", "An alias for an existing variable", "A pointer", "A type of object", "A copy"),
  q("What is the size of an 'int' on most 64-bit systems?", "4 bytes", "2 bytes", "8 bytes", "1 byte"),
  q("Which operator is used for logic AND?", "&&", "&", "||", "AND"),
  q("What is an inline function?", "A function whose code is replaced at the call site at compile time", "A long function", "A recursive function", "A library function"),
  q("What is a 'friend' function?", "A function that has access to the private members of a class", "A member function", "A global function", "A protected function"),
  q("What is 'namespace' used for?", "To group classes/functions and prevent name collisions", "To define variables", "To create threads", "To handle memory"),
  q("which operator is used to access members of a structure/class via a pointer?", "->", ".", "::", "*"),
  q("What does 'STL' stand for?", "Standard Template Library", "Static Tool Link", "Standard Tool Language", "Simple Text Layout"),
  q("Which container in STL provides a dynamic array?", "vector", "list", "stack", "queue"),
  q("What is the output of 5 / 2 in C++?", "2", "2.5", "3", "2.0"),
  q("How do you write a comment in C++?", "// or /* */", "#", "<!-- -->", "--"),
  q("What is a Virtual function?", "A function that is redefined in a derived class for runtime polymorphism", "A slow function", "A private function", "A helper function")
];

export const sqlL2: SampleQuestion[] = [
  q("What is the difference between TRUNCATE and DELETE?", "TRUNCATE is a DDL command that resets the table; DELETE is a DML command that removes rows", "No difference", "DELETE is faster", "TRUNCATE can use WHERE"),
  q("What is a 'Composite Key'?", "A primary key that consists of two or more columns", "A key with many values", "A foreign key", "A type of index"),
  q("What is 'Normalization'?", "The process of organizing data to reduce redundancy and improve data integrity", "Scaling the database", "Converting data to strings", "Indexing the table"),
  q("What is 'Denormalization'?", "The process of adding redundant data to improve read performance", "Removing all data", "Creating a new schema", "Deleting indexes"),
  q("What is a 'Stored Procedure'?", "A prepared SQL code that you can save, so the code can be reused over and over again", "A type of backup", "A table with many rows", "A query that runs fast"),
  q("What is a 'Trigger'?", "A special type of stored procedure that automatically runs when an event occurs", "A button in the UI", "A type of error", "A database connection"),
  q("What is the difference between UNION and UNION ALL?", "UNION removes duplicates; UNION ALL keeps them", "UNION is faster", "UNION combines tables vertically; UNION ALL horizontally", "They are identical"),
  q("What is a 'Transaction'?", "A sequence of operations performed as a single logical unit of work", "Giving money to someone", "A type of log", "A query result"),
  q("What does 'ACID' stand for?", "Atomicity, Consistency, Isolation, Durability", "Access, Control, Intelligence, Data", "Always Connected In Database", "Advanced Code In Design"),
  q("What is 'Isolation Level'?", "Defines how transaction integrity is visible to other users and systems", "The speed of the query", "The number of users", "A backup level"),
  q("What is 'Cursor'?", "A database object used to retrieve data from a result set one row at a time", "A mouse pointer", "A type of error", "A table alias"),
  q("What is 'Self JOIN'?", "A regular join, but the table is joined with itself", "A join with no conditions", "A join with a system table", "A nested join"),
  q("What is 'Referential Integrity'?", "A property that requires every value of one attribute (column) to exist as a value of another attribute", "Checking for typos", "Securing the password", "Backup strategy"),
  q("What is 'Index' types?", "Clustered and Non-clustered", "Fast and Slow", "Large and Small", "Internal and External"),
  q("What is the difference between Clustered and Non-clustered index?", "Clustered index defines the physical order of data; Non-clustered does not", "Non-clustered is faster", "Only one non-clustered allowed", "They are the same"),
  q("What is 'View' updateability?", "Some views can be updated if they reference only one table without aggregates", "Views can never be updated", "All views are updated automatically", "Views are for read only"),
  q("What is 'Common Table Expression' (CTE)?", "A temporary named result set that you can reference within a SELECT, INSERT, UPDATE, or DELETE", "A type of table", "A permanent view", "A database connection"),
  q("What is 'Execution Plan'?", "A roadmap that tells you how the SQL engine will execute a query", "A list of queries", "A backup schedule", "A developer's plan"),
  q("What is 'B-Tree' in SQL?", "A tree data structure used to provide efficient indexing", "A binary tree", "A type of table", "A security layer"),
  q("What is 'Deadlock' in SQL?", "A situation where two or more transactions are waiting for each other to release locks", "A query that never ends", "A database crash", "A file system error"),
  q("What is 'Sharding'?", "A database partitioning pattern that separates very large databases into smaller parts", "Splitting a table", "Adding more RAM", "Encrypting the data"),
  q("What is 'NoSQL'?", "Non-relational database systems (e.g., MongoDB, Cassandra)", "Not Only SQL", "No Security Level", "A type of SQL"),
  q("Which clause is used for pagination in PostgreSQL?", "LIMIT and OFFSET", "TOP", "FETCH FIRST", "ROWS ONLY"),
  q("What is 'Materialized View'?", "A database object that contains the results of a query and is physically stored", "A view that updates in real-time", "A view with no data", "A type of index"),
  q("What is 'Full Text Search'?", "A technique for searching a single computer-stored document or a collection in a full-text database", "Searching for strings", "A fast query", "A type of index"),
  q("What is 'Checkpoint' in database?", "The process of writing all changed data blocks from memory to disk", "A point where you save code", "A security gate", "A type of error"),
  q("What is 'Write-Ahead Logging' (WAL)?", "A family of techniques for providing atomicity and durability in database systems", "Logging every click", "A backup system", "A type of index"),
  q("What is 'Cartesian Product' (CROSS JOIN)?", "A join that returns all possible combinations of rows from both tables", "A join with no matching", "A join that results in zero rows", "A join with many tables"),
  q("What is 'Window Function'?", "Perform a calculation across a set of table rows that are somehow related to the current row", "A function for UI", "A function that runs in a small window", "A type of aggregate"),
  q("What is 'Database Partitioning'?", "Dividing a database into distinct parts for manageability and performance", "Deleting half of the database", "Merging two databases", "A type of index")
];

export const nodeL2: SampleQuestion[] = [
  q("What is the purpose of 'Buffer' in Node.js?", "To handle binary data directly", "To speed up strings", "To store integers", "To cache images"),
  q("What is 'Event-Driven' architecture?", "A design pattern where the flow is determined by events such as user actions or messages", "An architecture for events only", "A slow design", "A database model"),
  q("What is the difference between 'setImmediate' and 'process.nextTick'?", "process.nextTick executes before setImmediate (at the end of current phase)", "setImmediate is faster", "They are identical", "nextTick is for UI"),
  q("What is 'Cluster' module?", "Allows you to create child processes that all share server ports", "A group of databases", "A way to sort files", "A network tool"),
  q("What is 'Streams' types?", "Readable, Writable, Duplex, and Transform", "Fast and Slow", "Binary and Text", "Internal and External"),
  q("What is 'Middleware' in Express?", "Functions that execute during the request-response cycle", "A type of database", "A security tool", "A frontend component"),
  q("What is 'JWT'?", "JSON Web Token - used for secure transmission of information between parties", "A JavaScript tool", "A database engine", "A network protocol"),
  q("What is 'Cors'?", "Cross-Origin Resource Sharing - allows restricted resources to be requested from another domain", "A type of error", "A database connection", "A rapid system"),
  q("What is 'Helmet.js'?", "A module for Express that helps secure apps by setting various HTTP headers", "A CSS library", "A tool for images", "A database manager"),
  q("What is 'Mongoose'?", "An ODM (Object Data Modeling) library for MongoDB and Node.js", "A fast server", "A type of loop", "A security tool"),
  q("What is 'Async/Await' in Node.js?", "Syntactic sugar for handling Promises", "A way to stop the event loop", "A database query", "A UI event"),
  q("What is 'Error-First Callback' convention?", "A style where the first argument of the callback is an error object", "Handling errors at the end", "Throwing errors", "A security standard"),
  q("What is 'REPL' in depth?", "Read-Eval-Print Loop - an interactive shell for Node.js", "Recycle-Energy-Power-Log", "Real-time Event Processing Loop", "Regular Expression Parsing Link"),
  q("What is the purpose of 'os' module?", "To provide operating system-related utility functions and information", "To open files", "To install apps", "To connect to hardware"),
  q("What is 'Child Process' module?", "Provides the ability to spawn child processes in a manner that is similar but not identical to popen", "A small node app", "A database thread", "A type of loop"),
  q("What is 'Worker Threads'?", "Enables the use of threads that execute JavaScript in parallel", "Small workers on the server", "A type of database", "A network protocol"),
  q("What is 'Unit Testing' in Node (Mocha/Jest)?", "Testing individual components for correctness", "Testing the entire system", "Manual testing", "A design pattern"),
  q("What is 'Dotenv'?", "A zero-dependency module that loads environment variables from a .env file", "A type of image", "A code formatter", "A database engine"),
  q("What is 'Passport.js'?", "Authentication middleware for Node.js", "A way to travel with node", "A security tool for cloud", "A database connector"),
  q("What is 'Socket.io'?", "A library that enables real-time, bidirectional and event-based communication", "A type of database", "A file system tool", "A UI component"),
  q("What is the use of 'util.promisify'? ", "Converts a regular function that takes a callback into a function that returns a promise", "Speeds up code", "Handles errors", "Deletes functions"),
  q("What is 'Memory Leak' in Node.js?", "A failure to release memory that is no longer needed", "A physical hole in RAM", "A fast database", "A type of error"),
  q("How do you debug a Node.js application?", "Using --inspect flag or VS Code debugger", "Using console.log only", "Reading documentation", "Restarting the app"),
  q("What is 'Package-lock.json'?", "Ensures that the exact versions of dependencies are installed every time", "A lock for the project", "A security file", "A list of developers"),
  q("What is 'Module.exports' vs 'Exports'?", "module.exports is the actual object that is returned; exports is a reference to it", "They are identical", "exports is for functions only", "module.exports is for objects only"),
  q("What is 'Nvm'?", "Node Version Manager - tools for managing multiple Node.js versions", "New Version Manual", "Network Value Mode", "Node Volume Manager"),
  q("What is 'Express Generator'?", "A tool to quickly create an application skeleton", "Generating code dynamically", "A database tool", "A UI builder"),
  q("What is 'Morgan' middleware?", "An HTTP request logger middleware for Node.js", "A type of database", "A security tool", "A frontend library"),
  q("What is 'Body-parser'?", "A middleware to parse incoming request bodies in a middleware before your handlers", "Parsing the HTML", "Cleaning the database", "A networking tool"),
  q("What is 'Microservices' architecture in Node.js?", "Dividing a large application into small, independent services", "Using small computers", "A type of database", "A design pattern for UI")
];

export const cppL2: SampleQuestion[] = [
  q("What is 'RAII' in C++?", "Resource Acquisition Is Initialization - resource management pattern", "Rapid AI Integration", "Real-time Access Interface", "Range At Initial Index"),
  q("What is 'Abstract Class' in C++?", "A class that has at least one pure virtual function", "A class with no data", "A class that is hidden", "A base for all code"),
  q("What is a 'Pure Virtual Function'?", "A virtual function with '= 0' that must be overridden in derived classes", "A function that has no code", "A fast function", "A private function"),
  q("What is 'Multiple Inheritance' diamond problem?", "Ambiguity when a class inherits from two classes that both inherit from the same base class", "A security risk", "A memory leak", "A type of error"),
  q("What is 'Virtual Base Class'?", "A way to prevent multiple instances of a base class in multiple inheritance", "A class for VR", "A base for all objects", "A type of template"),
  q("What is 'Template' in C++?", "A blueprint for creating a generic class or function", "A type of file", "A preset code", "A design pattern"),
  q("What is 'Exception Handling' in C++?", "Using try, catch, and throw to manage runtime errors", "Checking for typos", "A security scan", "A way to stop the app"),
  q("What is 'Smart Pointer'?", "An object that manages a pointer and ensures memory is released (e.g., unique_ptr, shared_ptr)", "A pointer that thinks", "A type of variable", "A database link"),
  q("What is 'STL Container' types?", "Sequence, Associative, and Unordered Associative", "Large and Small", "Internal and External", "Fast and Slow"),
  q("What is 'Vector' vs 'List' in STL?", "Vector is a dynamic array; List is a doubly linked list", "No difference", "List is faster for random access", "Vector is for integers only"),
  q("What is 'Lambda' in C++11?", "An anonymous function defined in-place", "A variable type", "A loop construct", "A class member"),
  q("What is 'Move Semantics' (rvalue references)?", "Efficiently moving resources from temporary objects instead of copying", "Moving variables across files", "A type of loop", "A security standard"),
  q("What is 'Standard Template Library' (STL)?", "A library of container classes, algorithms, and iterators", "A tool for UI", "A database engine", "A network protocol"),
  q("What is 'Operator Overloading'?", "Redefining the behavior of operators for user-defined types", "Using too many operators", "A type of error", "A security risk"),
  q("What is 'Function Overloading'?", "Defining multiple functions with the same name but different parameters", "Creating many functions", "A type of loop", "A design pattern"),
  q("What is 'Copy Constructor'?", "A constructor that initializes an object using another object of the same class", "A function that copies files", "A type of assignment", "A memory move"),
  q("What is 'Static' member in a class?", "A member shared by all instances of the class", "A member that doesn't change", "A private member", "A constructor"),
  q("What is 'Friend Class'?", "A class that can access private and protected members of another class", "A class that is safe", "A public class", "A global class"),
  q("What is 'Composition' vs 'Inheritance'?", "Composition is 'has-a' relationship; Inheritance is 'is-a' relationship", "They are identical", "Composition is better", "Inheritance is for UI"),
  q("What is 'Function Template'?", "A single function that can work with different data types", "A code snippet", "A type of loop", "A library function"),
  q("What is 'Namespaces'?", "Used to organize code into logical groups and to prevent name collisions", "Directories for code", "A type of variable", "A security feature"),
  q("What is 'Inline' function in detail?", "Suggests the compiler to replace function call with the actual code to save overhead", "A function on one line", "A fast function", "A library function"),
  q("What is 'Explicit' keyword?", "Prevents the compiler from using a constructor for implicit type conversions", "Shows the code clearly", "A type of variable", "A security standard"),
  q("What is 'Const' member function?", "A function that promises not to modify the object's state", "A fast function", "A function for constants", "A constructor"),
  q("What is 'Dynamic_cast'?", "Safe downcasting at runtime in C++", "Changing variable types fast", "A type of loop", "A security scan"),
  q("What is 'Static_cast'?", "Compile-time casting used for related types", "A slow cast", "Changing variable names", "A database tool"),
  q("What is 'Reinterpret_cast'?", "Casting between unrelated pointer types (dangerous)", "A safe cast", "Copying an object", "A type of encryption"),
  q("What is 'Auto' keyword in C++11?", "Type inference for variables", "Automatic variables", "A type of loop", "A security standard"),
  q("What is 'Initial list' in constructor?", "Initializing members before the constructor body runs", "A list of variables", "A type of loop", "A data structure"),
  q("What is 'Override' keyword?", "Ensures that a virtual function actually overrides a base class function", "Replacing a function", "Deleting a function", "A type of variable")
];

export const sqlL3: SampleQuestion[] = [
  q("What is 'Explain Analyze' in PostgreSQL?", "Executes the query and shows the actual execution time and plan", "Just shows the plan", "Analyzes the database for errors", "A security scan"),
  q("What is 'Query Rewriting' in query optimization?", "The process of transforming a query into an equivalent but more efficient form", "Changing the user's input", "Formatting the SQL", "Naming the query"),
  q("What is 'Index-Only Scan'?", "A scan where all required data is retrieved directly from the index without visiting the table", "A scan of only one column", "A fast type of sequential scan", "A scan of the primary key"),
  q("What is 'Multiversion Concurrency Control' (MVCC)?", "A method used to provide concurrent access to data without locking", "Using many versions of SQL", "A type of backup", "A security protocol"),
  q("What is 'Partial Index'?", "An index built over a subset of a table specified by a conditional expression", "An index that is not finished", "An index of the first few rows", "A type of foreign key"),
  q("What is 'Bitmap Index'?", "An index that uses bit arrays (bitmaps) to answer queries by performing bitwise logical operations", "An index for images", "A type of B-tree", "A fast sequential index"),
  q("What is 'Database Hinter'?", "Providing hints to the optimizer on how to execute a query", "A help menu", "A developer's tool", "A type of log"),
  q("What is 'Logical Decoding'?", "The process of extracting all persistent changes to a database's tables into a coherent format", "Decoding a password", "A type of query optimization", "A backup mode"),
  q("What is 'Foreign Data Wrapper' (FDW)?", "Allows access to data stored in external data sources as if they were local tables", "A type of table alias", "A security wrapper", "A network tool"),
  q("What is 'Vacuum' in PostgreSQL?", "Reclaims storage occupied by dead tuples and updates statistics", "Cleaning the server hardware", "Deleting the whole database", "A type of backup"),
  q("What is 'Write Amplification' in databases?", "The phenomenon where more data is written to the storage media than the logical amount written by the application", "Making the database larger", "Adding more logs", "A type of error"),
  q("What is 'Hot Standby'?", "A backup server that is always running and can take over immediately if the primary fails", "A server that is very hot", "A backup on a DVD", "A manual backup"),
  q("What is 'Point-in-Time Recovery' (PITR)?", "The process of restoring a database to a specific moment in time", "Restoring from a point", "A type of error handling", "Scaling the database"),
  q("What is 'Streaming Replication'?", "Continuously sending WAL records from a primary server to standbys", "Watching movies on the database", "Copying data once a day", "A type of index"),
  q("What is 'Table Inheritance' in PostgreSQL?", "A feature that allows a table to inherit columns and constraints from a parent table", "Copying a table", "A type of relationship", "A database schema"),
  q("What is 'Ad-hoc Query'?", "A non-predefined query created for a single, specific purpose", "A query with errors", "A fast query", "A type of view"),
  q("What is 'OLAP' vs 'OLTP'?", "OLAP is for analytical processing; OLTP is for transactional processing", "They are the same", "OLAP is faster", "OLTP is for reports"),
  q("What is 'Dimensional Modeling'?", "A data modeling technique optimized for data warehousing (Star/Snowflake schema)", "Modeling in 3D", "A type of class diagram", "A database design for apps"),
  q("What is 'Cardinality' in SQL?", "The number of unique values in a column relative to the total number of rows", "The name of a table", "The speed of the query", "A security level"),
  q("What is 'SARGable' query?", "Search ARGument-able - a query that can take advantage of an index", "A query with no where clause", "A type of error", "A fast join"),
  q("What is 'Hashed Join'?", "A join algorithm that builds a hash table on the fly to match rows", "A secure join", "A join using MD5", "A slow join"),
  q("What is 'Nested Loop Join'?", "A join algorithm that iterates through rows of one table and searches the other for matches", "A loop inside a join", "A join that never ends", "A fast join"),
  q("What is 'Sort Merge Join'?", "A join algorithm that sorts both tables by the join key and then merges them", "A join that sorts automatically", "A type of union", "A join for strings only"),
  q("What is 'Predicate Pushdown'?", "Moving filters closer to the data source to reduce data volume early", "Pushing code to production", "Formatting the SQL", "A security measure"),
  q("What is 'Query Plan Caching'?", "Storing the execution plan of a query to reuse it for future executions", "Caching the query result", "Scaling the database", "A developer's tool"),
  q("What is 'Read Consistency'?", "Ensuring that a user sees a consistent state of the data during a transaction", "Reading very fast", "A type of backup", "A security level"),
  q("What is 'Two-Phase Commit' (2PC)?", "A protocol for ensuring atomic transactions in a distributed system", "Committing code twice", "A type of backup", "A security gate"),
  q("What is 'Sparse Index'?", "An index that only contains entries for some of the search-key values", "A thin index", "An index for many columns", "A type of B-tree"),
  q("What is 'Covering Index'?", "An index that includes all the columns requested by a query", "An index that hides data", "A type of primary key", "A backup index"),
  q("What is 'Fill Factor' in SQL?", "Determines the percentage of space on each leaf-level page to be filled with data for indexing", "The size of the table", "The number of rows", "A backup level")
];

export const nodeL3: SampleQuestion[] = [
  q("What is the 'UV_THREADPOOL_SIZE'?", "Environment variable that controls the number of threads in Libuv's pool", "The size of node apps", "The number of users", "A database limit"),
  q("What is 'Heap Snapshot'?", "A point-in-time capture of the memory usage of a Node.js process", "A picture of the server", "A type of log", "A fast database"),
  q("What is 'Flame Graph'?", "A visualization tool for profiling software to identify performance bottlenecks", "A graph of fire", "A type of chart", "A database schema"),
  q("What is 'Memory Leak' detection using 'heapdump'?", "Generating heap snapshots to find objects that aren't being garbage collected", "Checking for physical leaks", "Reading logs", "A security scan"),
  q("What is 'Streaming' video in Node.js?", "Sending video data in chunks to the client for continuous playback", "Downloading a movie", "A type of database", "A networking tool"),
  q("What is 'Domain' module (deprecated)?", "A way to handle errors in different execution contexts", "Buying a website", "A type of variable", "A security feature"),
  q("What is 'Clustering' vs 'Worker Threads'?", "Clustering uses multiple processes (separate memory); Worker Threads use multiple threads (shared memory)", "They are identical", "Clustering is for UI", "Worker threads are slower"),
  q("What is 'V8 Garbage Collection' phases?", "Scavenge (Young Gen) and Mark-Sweep-Compact (Old Gen)", "Daily and Weekly", "Fast and Slow", "Internal and External"),
  q("What is 'Microservices' communication (gRPC/RabbitMQ)?", "Ways for independent services to talk to each other in a distributed system", "Talking on the phone", "A type of database", "A frontend tool"),
  q("What is 'Server-Side Rendering' (SSR)?", "Rendering the initial HTML on the server before sending it to the client", "Drawing images with node", "A type of CSS", "A database query"),
  q("What is 'Backpressure' in Node.js streams?", "A mechanism to signal the producer to slow down when the consumer is overwhelmed", "Pressing the back button", "A type of error", "A networking tool"),
  q("What is 'Piping' in streams?", "Connecting the output of one stream directly to the input of another", "Using pipes for cooling", "A way to speed up memory", "A database query flow"),
  q("What is 'Middleware' order importance?", "Middleware executes in the order it is defined", "Order doesn't matter", "Alphabetical order", "Random order"),
  q("What is 'Security Headers' using 'cms'?", "Content Security Policy to prevent XSS and other attacks", "Adding names to headers", "Encrypting the server", "A type of logo"),
  q("What is 'Dependency Injection' in Node.js?", "A design pattern where objects receive their dependencies from the outside", "Infecting the app", "Adding more modules", "A type of loop"),
  q("What is 'Event Loop' phases in detail?", "Timers, Pending Callbacks, Idle/Prepare, Poll, Check, Close Callbacks", "Start, Run, Stop", "Daily cycle", "Fast and Slow"),
  q("What is 'I/O Polling'?", "The process by which the event loop waits for new I/O events", "Asking the user for input", "A type of error", "A networking tool"),
  q("What is 'Zero-copy' in Node.js?", "Techniques to pass data between parts of a system without copying it in memory", "Having no code", "A fast way to delete data", "A type of backup"),
  q("What is 'V8 Optimization' (JIT)?", "Optimizing frequently executed code into efficient machine code", "Optimizing images", "Scaling the database", "A developer's tool"),
  q("What is 'Profiling' with --prof?", "Built-in profiler that records V8's behavior during execution", "Creating user accounts", "A security scan", "Testing hardware"),
  q("What is 'UncaughtException' event?", "Emitted when an exception bubbles all the way back to the event loop", "A handled error", "A type of success", "A UI component"),
  q("What is 'Graceful Shutdown'?", "Cleaning up resources (closing DB, servers) before exiting the process", "Stopping the app fast", "A type of crash", "A security feature"),
  q("What is 'PM2'?", "A production process manager for Node.js applications with a built-in load balancer", "A new node version", "A database engine", "A network protocol"),
  q("What is 'Profiling' with Chrome DevTools?", "Connecting Chrome to a running Node process for debugging and profiling", "Using Chrome to browse", "A type of chart", "A database tool"),
  q("What is 'C++ Addons' for Node.js?", "Dynamically-linked shared objects that provide glue between C++ and JavaScript", "Adding more code", "A type of plugin", "A database connector"),
  q("What is 'N-API'?", "An API for building native addons that is independent from the underlying JS engine", "A new networking tool", "A type of chart", "A security standard"),
  q("What is 'Global State' in Node.js?", "Avoiding shared mutable state to prevent race conditions and memory leaks", "A state in USA", "A type of loop", "A database table"),
  q("What is 'Circuit Breaker' pattern?", "A design pattern used to detect failures and encapsulate logic of preventing a failure from recurring", "A fuse in hardware", "A type of switch", "A database index"),
  q("What is 'Load Balancing' algorithms?", "Round Robin, Least Connections used to distribute traffic", "Balancing the computer's weight", "A type of loop", "A security standard"),
  q("What is 'Containerization' (Docker) for Node.js?", "Packaging the application and its environment into a single unit", "Putting node in a box", "A type of database", "A shipping tool")
];

export const cppL3: SampleQuestion[] = [
  q("What is 'SFINAE' in C++?", "Substitution Failure Is Not An Error - template metaprogramming technique", "A type of error", "A fast function", "A database link"),
  q("What is 'Perfect Forwarding'?", "Using std::forward to pass arguments to another function while preserving their lvalue/rvalue-ness", "Fast delivery", "A type of loop", "A security standard"),
  q("What is 'Metaprogramming' with templates?", "Executing code at compile time to generate or manipulate code", "Programming for Facebook", "High-level design", "A type of loop"),
  q("What is 'CRTP' (Curiously Recurring Template Pattern)?", "A class X inherits from a class template instantiated with X", "A type of loop", "A design pattern for UI", "A security risk"),
  q("What is 'Memory Model' in C++11?", "Specifies how multiple threads access the same memory locations", "The size of RAM", "A type of memory chip", "A database schema"),
  q("What is 'Atomic' operations?", "Operations that execute as a single, indivisible unit", "Small operations", "Operations that explode", "Constant operations"),
  q("What is 'Lock-free' programming?", "Designing data structures that don't use mutexes or locks to prevent deadlocks", "Programming without keys", "A fast loop", "A database query"),
  q("What is 'Type Traits'?", "A way to query properties of types at compile time", "A type of person", "A character in a game", "A database field"),
  q("What is 'Concepts' in C++20?", "A way to specify constraints on template parameters", "New ideas for code", "A type of class", "A design pattern"),
  q("What is 'Coroutines' in C++20?", "Functions that can suspend and resume execution", "Small functions", "A type of thread", "A database task"),
  q("What is 'Modules' in C++20?", "A modern alternative to header files for organizing code", "A group of libraries", "A type of class", "A way to load jars"),
  q("What is 'Placement New'?", "A version of the new operator that allows constructing an object at a specific memory location", "Placing an object on a map", "A type of loop", "A memory move"),
  q("What is 'Alignment' in C++ memory management?", "The requirement that memory addresses be multiples of a certain value", "Aligning text in UI", "A type of variable", "A security standard"),
  q("What is 'Volatile' keyword in depth?", "Tells the compiler that a variable's value may be changed by something outside the program", "Makes variable constant", "Deletes variable", "Thread-safe only for writes"),
  q("What is 'Strict Aliasing' rule?", "A rule that prevents access to an object via a pointer of a different type", "A type of error", "A security scan", "A fast way to code"),
  q("What is 'NRVO' (Named Return Value Optimization)?", "A compiler optimization that eliminates the copy of a function's return value", "A type of loop", "A design pattern", "A memory move"),
  q("What is 'ADL' (Argument Dependent Lookup)?", "Searching for a function in the namespace of its arguments", "Searching for files", "A type of variable", "A security feature"),
  q("What is 'Inline Namespace'?", "A namespace whose members are treated as if they were in the parent namespace", "A namespace on one line", "A fast namespace", "A library function"),
  q("What is 'User-Defined Literals'?", "Allowing users to define their own suffixes for constants (e.g., 10_km)", "Naming variables freely", "A type of string", "A security standard"),
  q("What is 'Variadic Templates'?", "Templates that can take an arbitrary number of arguments", "Templates with different names", "A type of loop", "A design pattern"),
  q("What is 'Fold Expressions'?", "Applying a binary operator to all elements of a parameter pack", "Folding the code", "A type of loop", "A mathematical operator"),
  q("What is 'CTAD' (Class Template Argument Deduction)?", "Allows the compiler to deduce template arguments from constructor calls", "Deducing types automatically", "A type of loop", "A design pattern"),
  q("What is 'Range-based for loop' internals?", "Iterating using begin() and end() member functions", "A for loop for numbers only", "A fast loop", "A security standard"),
  q("What is 'Zero-Overhead Principle'?", "You don't pay for what you don't use, and what you use is as efficient as humanly possible", "Having no code", "A fast way to delete data", "A type of backup"),
  q("What is 'Tuple' implementation details?", "Recursive template structure to hold multiple types", "A type of string", "A database record", "A fast loop"),
  q("What is 'Standard Library' algorithms (sort, find)?", "A collection of generic algorithms for common tasks", "Tools for UI", "A database engine", "A network protocol"),
  q("What is 'Exception Safety' levels?", "Basic, Strong, and No-throw guarantees", "Checking for typos", "A security scan", "A way to stop the app"),
  q("What is 'Pimpl' idiom?", "Pointer to Implementation - a way to hide implementation details and reduce compilation times", "A type of error", "A design pattern", "A library function"),
  q("What is 'Static_assert'?", "Compile-time assertion to check conditions", "A slow assert", "Changing variable names", "A database tool"),
  q("What is 'Explicit Specialization' of templates?", "Providing a specific implementation for a particular type", "Showing the code clearly", "A type of variable", "A security standard")
];


